// SPDX-License-Identifier: GPL-2.0
/* Copyright (c) 2018 The Linux Foundation. All rights reserved. */

#include <linux/debugfs.h>
#include <linux/delay.h>
#include <linux/interconnect.h>
#include <linux/pm_opp.h>

#include <drm/drm_file.h>

#include "a2xx_gpu.h"
#include "a2xx_debug.h"
#include "msm_gem.h"
#include "msm_mmu.h"

extern bool hang_debug;

/*
 * DIAGNOSTIC: when set to true, skip emitting the cross-context
 * sanitizer preamble (8x ALU/TEX/Bool/Loop scrub). Used to determine
 * whether the deterministic 0xc000428b MMU page fault is generated by
 * the kernel preamble or by user-space (Mesa) IB content.
 *
 *   echo 1 > /sys/module/msm/parameters/a2xx_skip_preamble  - disable
 *   echo 0 > /sys/module/msm/parameters/a2xx_skip_preamble  - re-enable
 *
 * Defaults to false (preamble emitted).
 */
bool a2xx_skip_preamble = false;
module_param(a2xx_skip_preamble, bool, 0644);
MODULE_PARM_DESC(a2xx_skip_preamble,
		 "skip a2xx cross-context sanitizer preamble (0=emit, 1=skip)");

/*
 * Track the last user IB1 across submits so the MMU fault handler can
 * dump its contents for forensic analysis of the 0xc000428b fault. The
 * pointer is valid only while the BO refcount we hold is alive (we
 * keep a kgem ref). We update it in a2xx_submit (sleepable context)
 * and read it from the IRQ handler (atomic context) - reads never
 * dereference NULL.
 */
static struct {
	u64 ib1_iova;
	u32 ib1_size;
	u32 *ib1_kvaddr;
	struct drm_gem_object *ib1_bo;
} a2xx_last_ib;

static void a2xx_dump(struct msm_gpu *gpu);
static bool a2xx_idle(struct msm_gpu *gpu);

/*
 * Memory bandwidth vote in icc units (kBps), proportional to GPU clock with
 * 8 bytes/cycle on the 64-bit memory bus. Legacy webOS msm_bus voted
 * ab=ib=2008 MB/s for grp3d_max — set both avg and peak so the AFAB
 * aggregator (sum of avg, max of peak) sees the GPU's full demand and
 * scales fabric clock appropriately.
 */
static u32 a2xx_icc_bw_for_freq(unsigned long freq_hz)
{
	return Bps_to_icc(freq_hz) * 8;
}

/*
 * a2xx_emit_sanitizer_preamble - reset GPU-internal SRAM state at
 * cross-context boundaries.
 *
 * The Adreno 2xx hardware was designed for the legacy KGSL "thick
 * state machine" paradigm: shader-constant SRAMs (vec4 ALU, texture-
 * fetch, boolean, loop) and other GPU-internal SRAMs (SQ instruction
 * cache, GPR file, VPC vertex param cache) retain their contents
 * across PM4 cmdstream submissions. KGSL handled this by issuing a
 * PM4_LOAD_CONSTANT_CONTEXT bulk-restore from per-context shadow
 * memory at every context switch.
 *
 * Mainline freedreno + msm DRM does not implement per-context shadow
 * memory and PM4_LOAD_CONSTANT_CONTEXT hangs in this code path
 * (likely IOVA/ringbuffer-execution-context related, see
 * reports/gpu-internal-state-nondeterminism.md). The result was
 * stale shader-constant data leaking across DRM-client transitions,
 * producing 9-of-10 distinct pixel outputs from byte-identical PM4
 * cmdstreams in gl-capture diagnostic runs.
 *
 * Workaround: at every cross-context boundary, emit standard
 * CP_SET_CONSTANT zero-fill packets directly from the kernel
 * ringbuffer (BEFORE the user's IB1) to wipe the four constant-
 * memory banks to a known state. Bracketed by WAIT_FOR_IDLE +
 * CACHE_FLUSH_AND_INV_EVENT so the user's IB sees a settled GPU.
 *
 * This avoids:
 *   - The PM4_LOAD_CONSTANT_CONTEXT hang (no DMA path used)
 *   - The race we observed when the same writes were emitted from
 *     userspace Mesa (kernel writes complete before user IB starts;
 *     no ordering ambiguity with per-batch clear-color writes)
 *
 * Cost: ~1300 dwords of cmdstream once per cross-context boundary;
 * zero overhead for sequential same-context submits.
 */
/*
 * Lazily allocate a 32 KB shadow buffer for the cross-context
 * sanitizer.  Layout (8 KB-aligned regions):
 *
 *   shadow_iova + 0      ALU bank shadow  (2048 dwords / 8192 bytes)
 *   shadow_iova + 0x2000 TEX bank shadow  ( 192 dwords /  768 bytes
 *                                          padded to 8 KB)
 *
 * CP_LOAD_CONSTANT_CONTEXT masks its address operand with 0xFFFFE000,
 * so each region must be independently 8 KB-aligned.  Reserving 32 KB
 * total guarantees we get two consecutive 8 KB-aligned slots even if
 * the IOMMU hands us a non-8KB-aligned base IOVA.
 *
 * Returns 0 on success, sets a2xx_gpu->shadow_bo / shadow_iova /
 * shadow_tex_iova / shadow_vaddr.  On failure returns -errno; the
 * caller falls back to CP_SET_CONSTANT zero-fills (ALU only).
 */
static int a2xx_alloc_shadow(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	struct drm_gem_object *bo;
	uint64_t iova;
	void *vaddr;

	if (a2xx_gpu->shadow_bo)
		return 0;

	vaddr = msm_gem_kernel_new(gpu->dev, SZ_32K,
				   MSM_BO_WC | MSM_BO_GPU_READONLY,
				   gpu->vm, &bo, &iova);
	if (IS_ERR(vaddr))
		return PTR_ERR(vaddr);

	/* Round IOVA up to 8 KB; corresponding offset in the BO maps
	 * 1:1 (linear pinned IOVA range), so the kernel-vaddr is just
	 * shifted by the same amount. */
	uint64_t aligned_iova = ALIGN(iova, SZ_8K);
	uint64_t offset = aligned_iova - iova;

	a2xx_gpu->shadow_bo = bo;
	a2xx_gpu->shadow_iova = aligned_iova;
	a2xx_gpu->shadow_tex_iova = aligned_iova + SZ_8K;
	a2xx_gpu->shadow_vaddr = vaddr + offset;

	dev_info(gpu->dev->dev,
		 "a2xx shadow: raw_iova=%pad alu_iova=%pad tex_iova=%pad ring_iova=%pad\n",
		 &iova, &aligned_iova, &a2xx_gpu->shadow_tex_iova,
		 &gpu->rb[0]->iova);

	/* Zero ALU shadow (slots 1, 2 are pre-populated below) +
	 * TEX shadow (vertex/texture fetch descriptors all zero).
	 *
	 * The 0xDEADBEEF sentinel diagnostic in commit 84de002555e3
	 * confirmed the kernel CP_LOAD_CONSTANT_CONTEXT for TEX does
	 * broadcast to all 8 SQ wavefront slots - a 0xDEADBEEF fill
	 * broke every one of the 8 cycle outputs, while a zero fill
	 * leaves a known-good baseline that Mesa's per-draw inline
	 * CP_SET_CONSTANT (active-slot-only) fixes up to varying
	 * degrees depending on which slot is active when the user IB
	 * runs. The Mesa-side fix (re-emit fetch descriptors so all 8
	 * slots see them) is the next part.
	 */
	memset(a2xx_gpu->shadow_vaddr, 0, SZ_16K);

	/*
	 * Pre-populate the SoC-reserved ALU slots with values the
	 * fixed-function vertex pipeline relies on. Sampled from the
	 * legacy webOS proprietary stack (KGSL + Qualcomm libGLESv2)
	 * via gpu-regdump-webos -- see reports/fb-captures/
	 * webos-soc-reference.txt.
	 *
	 * Only slots 1 and 2 hold non-zero SoC values; all other slots
	 * in 0..31 read as zero on the proprietary stack and are left
	 * zero here. The decoded values are mathematical constants that
	 * appear to be used by the viewport-transform / LOD-bias /
	 * fixed-function math units:
	 *
	 *   ALU[1] = (19984.0f, 1.0f, 0.5f, 0.0f)
	 *   ALU[2] = (2.0f, 0.75f, 0.375f, 0.25f)
	 *
	 * Without these in the shadow, PM4_LOAD_CONSTANT_CONTEXT would
	 * blindly write zero into slots 1/2 and break the vertex
	 * pipeline (rendering goes degenerate / black). With them, the
	 * packet's bulk-restore brings the GPU into the same starting
	 * state as a fresh KGSL context.
	 */
	{
		u32 *alu = (u32 *)a2xx_gpu->shadow_vaddr;
		/* slot 1 */
		alu[1 * 4 + 0] = 0x469c4000;  /* 19984.0f */
		alu[1 * 4 + 1] = 0x3f800000;  /* 1.0f */
		alu[1 * 4 + 2] = 0x3f000000;  /* 0.5f */
		alu[1 * 4 + 3] = 0x00000000;
		/* slot 2 */
		alu[2 * 4 + 0] = 0x40000000;  /* 2.0f */
		alu[2 * 4 + 1] = 0x3f400000;  /* 0.75f */
		alu[2 * 4 + 2] = 0x3ec00000;  /* 0.375f */
		alu[2 * 4 + 3] = 0x3e800000;  /* 0.25f */
	}

	return 0;
}

static void a2xx_emit_sanitizer_preamble(struct msm_gpu *gpu,
					 struct msm_ringbuffer *ring)
{
	/*
	 * IMPORTANT: ALU constant slots 0-31 hold SoC-reserved system
	 * constants the hardware fixed-function pipeline uses (vertex
	 * transform helpers, viewport math, sampling LOD bias).
	 * gl-cap-and-regdump-webos sampled the proprietary-stack values:
	 *   slot 0 = (0,0,0,0)
	 *   slot 1 = (0x469c4000, 1.0, 0.5, 0)
	 *   slot 2 = (2.0, 0.75, 0.375, 0.25)
	 * Zeroing these breaks the vertex pipeline (transforms produce
	 * degenerate/clipped output).
	 *
	 * Mesa places user constants at:
	 *   VS_CONST_BASE = 0x20 (vec4 slot 32, dword offset 0x80)
	 *   PS_CONST_BASE = 0x120 (vec4 slot 288, dword offset 0x480)
	 * These plus everything between them is user-controlled and
	 * safe to wipe.  Cap at slot 511 (offset 0x7FC) - end of the
	 * 256-vec4 PS user range.
	 *
	 * Bool and loop are pure user-state - safe to wipe entirely.
	 */
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	const unsigned USER_ALU_OFFSET = 0x80;   /* slot 32 = VS_CONST_BASE */
	const unsigned USER_ALU_DWORDS = 1920;   /* slots 32..511 = 480 vec4 */
	const unsigned BOOL_CONSTANTS  = 8;
	const unsigned LOOP_CONSTANTS  = 56;
	/*
	 * have_shadow: take the LOAD_CONSTANT_CONTEXT path if the shadow
	 * BO was allocated successfully. The shadow is pre-populated with
	 * SoC-reserved ALU defaults (slots 1, 2) confirmed stable across
	 * 10 webOS runs - see a2xx_alloc_shadow().
	 */
	bool have_shadow = a2xx_gpu->shadow_bo != NULL;
	unsigned i;

	/*
	 * 8x SLOT-SCRUB LOOP - wrap the entire constant-restore + flush
	 * sequence in 8 iterations to scrub all 8 hypothesized internal
	 * SQ wavefront / SRAM slots on Adreno 220.
	 *
	 * Empirical evidence (100-run gl-cap-and-regdump-mainline test
	 * with LSM killed, current-mesa with sysmem-force reverted):
	 *   - Per-submit output is fully deterministic, period 8.
	 *   - 2/8 cycle positions render the gradient correctly.
	 *   - 6/8 cycle positions show a 3x2 grid of GMEM tile bins
	 *     where some tiles render correctly and others have flat
	 *     solid colors (vertex-interpolation broken on those tiles).
	 *
	 * The classic Yamato/Leia "thick state machine" hardware has 8
	 * internal slots/wavefronts, each with its own shadow constant
	 * SRAM. CP_SET_CONSTANT and CP_LOAD_CONSTANT_CONTEXT only write
	 * to the CURRENTLY-ACTIVE slot, so a single per-submit restore
	 * leaves 7 slots poisoned with residue from prior DRM clients.
	 * As GMEM tile-binning replays the cmdstream once per tile, the
	 * tile-to-slot mapping rotates and we see the constants surface
	 * differently in each bin.
	 *
	 * Cycling the full restore sequence 8 times (with a CP_EVENT_WRITE
	 * CACHE_FLUSH_AND_INV + WAIT_FOR_IDLE between iterations to force
	 * the hardware to retire and rotate) ensures every internal slot
	 * gets a clean ALU/Bool/Loop bank before the user's first draw.
	 */
	const unsigned ALU_CONSTANTS = 2048;
	const unsigned TEX_CONSTANTS = 192;   /* 32 fetch slots * 6 dwords */
	unsigned slot;

	/* Drain anything in flight from the previous client. */
	OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
	OUT_RING(ring, 0);

	for (slot = 0; slot < 8; slot++) {
		if (have_shadow) {
			/*
			 * Bulk-load the entire ALU constant bank (512 vec4 =
			 * 2048 dwords) from the kernel-pinned shadow buffer.
			 * The shadow is pre-populated with the SoC-reserved
			 * ALU defaults captured from webOS (slots 1, 2) plus
			 * zeros for the user range.
			 */
			OUT_PKT3(ring, CP_LOAD_CONSTANT_CONTEXT, 3);
			OUT_RING(ring, lower_32_bits(a2xx_gpu->shadow_iova));
			OUT_RING(ring, (0 << 24) | (0 << 16) | 0);
			OUT_RING(ring, ALU_CONSTANTS);

			/*
			 * Bulk-load the TEX (texture/vertex fetch) bank from
			 * the zero-filled shadow region 8 KB above the ALU
			 * region. KGSL emits the same packet at every context
			 * restore (kgsl_drawctxt.c "Texture Constants" path):
			 * type=1 (TEX), offset=0, count=192 dwords.
			 *
			 * Without this, residue from prior DRM clients in TEX
			 * SRAM bleeds into vertex-attribute fetches and shows
			 * up as a single colour channel reading back as zero
			 * on 5/8 internal slot positions (observed empirically
			 * in the 100-cap test before this addition).
			 */
			OUT_PKT3(ring, CP_LOAD_CONSTANT_CONTEXT, 3);
			OUT_RING(ring, lower_32_bits(a2xx_gpu->shadow_tex_iova));
			OUT_RING(ring, (0 << 24) | (1 << 16) | 0);
			OUT_RING(ring, TEX_CONSTANTS);
		} else {
			/* Inline CP_SET_CONSTANT zero-fill fallback. */
			OUT_PKT3(ring, CP_SET_CONSTANT, 1 + USER_ALU_DWORDS);
			OUT_RING(ring, (0 << 16) | USER_ALU_OFFSET);
			for (i = 0; i < USER_ALU_DWORDS; i++)
				OUT_RING(ring, 0);
		}

		/* Bool bank (8 dwords). */
		OUT_PKT3(ring, CP_SET_CONSTANT, 1 + BOOL_CONSTANTS);
		OUT_RING(ring, (2 << 16) | 0);
		for (i = 0; i < BOOL_CONSTANTS; i++)
			OUT_RING(ring, 0);

		/* Loop bank (56 dwords). */
		OUT_PKT3(ring, CP_SET_CONSTANT, 1 + LOOP_CONSTANTS);
		OUT_RING(ring, (3 << 16) | 0);
		for (i = 0; i < LOOP_CONSTANTS; i++)
			OUT_RING(ring, 0);

		/*
		 * Flush + invalidate + WFI between iterations forces the
		 * hardware to retire the current slot's writes and rotate
		 * to the next slot for the next CP_LOAD_CONSTANT_CONTEXT.
		 */
		OUT_PKT3(ring, CP_EVENT_WRITE, 1);
		OUT_RING(ring, CACHE_FLUSH_AND_INV_EVENT);
		OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
		OUT_RING(ring, 0);
	}
}

static void a2xx_submit(struct msm_gpu *gpu, struct msm_gem_submit *submit)
{
	struct msm_ringbuffer *ring = submit->ring;
	unsigned int i;
	int wptr_delay;

	/* Debug: log submit details */
	a2xx_debug_log_submit(gpu, submit);

	/*
	 * Cross-context-boundary state-leak workaround: if this submit is
	 * from a different DRM client than the previous one on this ring,
	 * inject a sanitizer preamble that bulk-restores Mesa's user
	 * shader-constant range from a kernel-pinned shadow BO via
	 * PM4_LOAD_CONSTANT_CONTEXT (ALU bank) and CP_SET_CONSTANT (bool
	 * + loop).  This matches the KGSL context-restore path on the
	 * legacy 2.6 kernel.  See a2xx_emit_sanitizer_preamble().
	 */
	if (ring->cur_ctx_seqno != submit->queue->ctx->seqno &&
	    !a2xx_skip_preamble) {
		(void)a2xx_alloc_shadow(gpu);  /* lazy-init, fall back to
						* inline writes if it fails */
		a2xx_emit_sanitizer_preamble(gpu, ring);
	}

	for (i = 0; i < submit->nr_cmds; i++) {
		switch (submit->cmd[i].type) {
		case MSM_SUBMIT_CMD_IB_TARGET_BUF:
			/* ignore IB-targets */
			break;
		case MSM_SUBMIT_CMD_CTX_RESTORE_BUF:
			/* ignore if there has not been a ctx switch: */
			if (ring->cur_ctx_seqno == submit->queue->ctx->seqno)
				break;
			fallthrough;
		case MSM_SUBMIT_CMD_BUF:
			OUT_PKT3(ring, CP_INDIRECT_BUFFER_PFD, 2);
			OUT_RING(ring, lower_32_bits(submit->cmd[i].iova));
			OUT_RING(ring, submit->cmd[i].size);
			OUT_PKT2(ring);
			break;
		}
	}

	/*
	 * Track the FIRST user IB1 of this submit for forensic dump on
	 * MMU fault. Replace any previous capture (release prior kvaddr
	 * mapping) so we always have the most recent submit available.
	 */
	for (i = 0; i < submit->nr_cmds; i++) {
		struct drm_gem_object *ib_bo;
		void *kvaddr;

		if (submit->cmd[i].type != MSM_SUBMIT_CMD_BUF)
			continue;

		if (a2xx_last_ib.ib1_bo) {
			msm_gem_put_vaddr(a2xx_last_ib.ib1_bo);
			a2xx_last_ib.ib1_bo     = NULL;
			a2xx_last_ib.ib1_kvaddr = NULL;
		}

		ib_bo = submit->bos[submit->cmd[i].idx].obj;
		/* Try regular path first (takes lock internally). If the BO
		 * was marked DONTNEED or is dma-buf imported, fall back to
		 * the lock-required "active" variant that accepts any madv
		 * state - documented for fault-dump scenarios. */
		kvaddr = msm_gem_get_vaddr(ib_bo);
		if (IS_ERR(kvaddr)) {
			long err1 = PTR_ERR(kvaddr);
			msm_gem_lock(ib_bo);
			kvaddr = msm_gem_get_vaddr_active(ib_bo);
			msm_gem_unlock(ib_bo);
			dev_info(gpu->dev->dev,
				 "a2xx IB1 vaddr fallback: regular=%ld active=%s\n",
				 err1,
				 IS_ERR(kvaddr) ? "ERR" : (kvaddr ? "OK" : "NULL"));
		}
		dev_info(gpu->dev->dev,
			 "a2xx capture IB1: cmd[%u] type=%u idx=%u iova=%016llx size=%u kvaddr=%s\n",
			 i, submit->cmd[i].type, submit->cmd[i].idx,
			 submit->cmd[i].iova, submit->cmd[i].size,
			 IS_ERR(kvaddr) ? "ERR" : (kvaddr ? "OK" : "NULL"));
		if (!IS_ERR_OR_NULL(kvaddr)) {
			a2xx_last_ib.ib1_iova   = submit->cmd[i].iova;
			a2xx_last_ib.ib1_size   = submit->cmd[i].size;
			a2xx_last_ib.ib1_kvaddr = (u32 *)kvaddr;
			a2xx_last_ib.ib1_bo     = ib_bo;
		}
		break;
	}

	/*
	 * EXPERIMENTAL: force the low nibble of the seqno written to
	 * CP_SCRATCH_REG2 to a value in the empirically-determined
	 * "stable rendering" set.
	 *
	 * 50-run gl-capture analysis on Adreno 220 / HP TouchPad showed
	 * pixel output is fully deterministic given submit->seqno & 0xF
	 * (perfect 16-cycle pattern). 9 of 16 lo-nibbles produce the
	 * "stable" rendering hash (lo = 0, 3, 4, 5, b, c, d, e, f); the
	 * other 7 produce different per-position broken renderings:
	 *
	 *   lo=1: 78d9...  lo=2: 9f34...
	 *   lo=6: 4d4c...  lo=7: 24c2...  lo=8: 0b59...
	 *   lo=9: 6b08...  lo=a: 7b74...
	 *
	 * The seqno value is written to CP_SCRATCH_REG2 (debug-only HW
	 * register, mainline doesn't depend on it for fence tracking -
	 * fence completion uses the CACHE_FLUSH_TS event below which
	 * stores into rbmemptr(ring, fence) memory). So masking the
	 * lo-nibble of what we write to SCRATCH_REG2 is functionally
	 * a no-op - except that the GPU's internal state machinery
	 * apparently uses some bits of this register, producing the
	 * 16-cycle variance we observe.
	 *
	 * Mask the seqno to (seqno & ~0xF) so SCRATCH_REG2 always lands
	 * in the lo=0 "stable" slot. The CACHE_FLUSH_TS path below
	 * keeps the unmasked seqno so fence completion still works.
	 *
	 * If this collapses the 50-run variance to a single hash, we've
	 * confirmed SCRATCH_REG2's low bits drive a HW state machine
	 * that affects rendering.
	 */
	OUT_PKT0(ring, REG_AXXX_CP_SCRATCH_REG2, 1);
	OUT_RING(ring, submit->seqno & ~0xFu);

	/* wait for idle before cache flush/interrupt */
	OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
	OUT_RING(ring, 0x00000000);

	OUT_PKT3(ring, CP_EVENT_WRITE, 3);
	OUT_RING(ring, CACHE_FLUSH_TS);
	OUT_RING(ring, rbmemptr(ring, fence));
	OUT_RING(ring, submit->seqno);   /* unmasked - fence tracking */
	OUT_PKT3(ring, CP_INTERRUPT, 1);
	OUT_RING(ring, 0x80000000);

	/* Debug: force cache flush before notifying GPU */
	a2xx_debug_cache_flush();

	/* Debug: optional delay before WPTR write */
	wptr_delay = a2xx_debug_get_wptr_delay();
	if (wptr_delay > 0)
		udelay(wptr_delay);

	adreno_flush(gpu, ring, REG_AXXX_CP_RB_WPTR);
}

static bool a2xx_me_init(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	struct msm_ringbuffer *ring = gpu->rb[0];

	OUT_PKT3(ring, CP_ME_INIT, 18);

	/* All fields present (bits 9:0) */
	OUT_RING(ring, 0x000003ff);
	/* Disable/Enable Real-Time Stream processing (present but ignored) */
	OUT_RING(ring, 0x00000000);
	/* Enable (2D <-> 3D) implicit synchronization (present but ignored) */
	OUT_RING(ring, 0x00000000);

	OUT_RING(ring, REG_A2XX_RB_SURFACE_INFO - 0x2000);
	OUT_RING(ring, REG_A2XX_PA_SC_WINDOW_OFFSET - 0x2000);
	OUT_RING(ring, REG_A2XX_VGT_MAX_VTX_INDX - 0x2000);
	OUT_RING(ring, REG_A2XX_SQ_PROGRAM_CNTL - 0x2000);
	OUT_RING(ring, REG_A2XX_RB_DEPTHCONTROL - 0x2000);
	OUT_RING(ring, REG_A2XX_PA_SU_POINT_SIZE - 0x2000);
	OUT_RING(ring, REG_A2XX_PA_SC_LINE_CNTL - 0x2000);
	OUT_RING(ring, REG_A2XX_PA_SU_POLY_OFFSET_FRONT_SCALE - 0x2000);

	/* Vertex and Pixel Shader Start Addresses in instructions
	 * (3 DWORDS per instruction) */
	OUT_RING(ring, 0x80000180);
	/* Maximum Contexts */
	OUT_RING(ring, 0x00000001);
	/* Write Confirm Interval and The CP will wait the
	 * wait_interval * 16 clocks between polling  */
	OUT_RING(ring, 0x00000000);
	/* NQ and External Memory Swap */
	OUT_RING(ring, 0x00000000);
	/* protected mode error checking (0x1f2 is REG_AXXX_CP_INT_CNTL) */
	if (a2xx_gpu->protection_disabled)
		OUT_RING(ring, 0x00000000);
	else
		OUT_RING(ring, 0x200001f2);
	/* Disable header dumping and Header dump address */
	OUT_RING(ring, 0x00000000);
	/* Header dump size */
	OUT_RING(ring, 0x00000000);

	if (!a2xx_gpu->protection_disabled) {
		/* enable protected mode */
		OUT_PKT3(ring, CP_SET_PROTECTED_MODE, 1);
		OUT_RING(ring, 1);
	}

	adreno_flush(gpu, ring, REG_AXXX_CP_RB_WPTR);
	return a2xx_idle(gpu);
}

static int a2xx_hw_init(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	dma_addr_t pt_base, tran_error;
	uint32_t *ptr, len;
	int i, ret;

	a2xx_gpummu_params(to_msm_vm(gpu->vm)->mmu, &pt_base, &tran_error);

	DBG("%s", gpu->name);

	/* halt ME to avoid ucode upload issues on a20x */
	gpu_write(gpu, REG_AXXX_CP_ME_CNTL, AXXX_CP_ME_CNTL_HALT);

	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE1, 0xfffffffe);
	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, 0xffffffff);

	/* note: kgsl uses 0x00000001 after first reset on a22x */
	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0xffffffff);
	msleep(30);
	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0x00000000);

	if (adreno_is_a225(adreno_gpu))
		gpu_write(gpu, REG_A2XX_SQ_FLOW_CONTROL, 0x18000000);

	/* note: kgsl uses 0x0000ffff for a20x */
	gpu_write(gpu, REG_A2XX_RBBM_CNTL, 0x00004442);

	/* MPU: physical range */
	gpu_write(gpu, REG_A2XX_MH_MMU_MPU_BASE, 0x00000000);
	gpu_write(gpu, REG_A2XX_MH_MMU_MPU_END, 0xfffff000);

	/*
	 * Match legacy webOS KGSL: configure ALL MH MMU client ports to
	 * BEH_TRAN_FLT (translate, fault on miss) instead of BEH_TRAN_RNG
	 * (translate, silently bypass on miss).
	 *
	 * Legacy msm8660_defconfig had CONFIG_MSM_KGSL_MMU_PAGE_FAULT=y, which
	 * sets MMU_CONFIG=2 = BEH_TRAN_FLT in kgsl_yamato.c YAMATO_MMU_CONFIG.
	 *
	 * BEH_TRAN_RNG is dangerous: an out-of-range / unmapped GPU access is
	 * silently passed through to raw physical address space, so the GPU
	 * reads garbage memory instead of faulting. On Adreno 220 this maps
	 * onto the intermittent faceted-rendering glmark2 symptom — the GPU
	 * pulls garbage in place of real vertex/normal/uniform data and we
	 * see no kernel-side warning.
	 *
	 * BEH_TRAN_FLT will turn those silent garbage reads into visible
	 * MH page faults via the MH interrupt path, which both eliminates
	 * the wrong-data outcome and gives us real diagnostics.
	 */
	gpu_write(gpu, REG_A2XX_MH_MMU_CONFIG, A2XX_MH_MMU_CONFIG_MMU_ENABLE |
		A2XX_MH_MMU_CONFIG_RB_W_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_W_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R0_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R1_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R2_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R3_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R4_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_VGT_R0_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_VGT_R1_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_TC_R_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_PA_W_CLNT_BEHAVIOR(BEH_TRAN_FLT));

	/* same as parameters in adreno_gpu */
	gpu_write(gpu, REG_A2XX_MH_MMU_VA_RANGE, SZ_16M |
		A2XX_MH_MMU_VA_RANGE_NUM_64KB_REGIONS(0xfff));

	gpu_write(gpu, REG_A2XX_MH_MMU_PT_BASE, pt_base);
	gpu_write(gpu, REG_A2XX_MH_MMU_TRAN_ERROR, tran_error);

	gpu_write(gpu, REG_A2XX_MH_MMU_INVALIDATE,
		A2XX_MH_MMU_INVALIDATE_INVALIDATE_ALL |
		A2XX_MH_MMU_INVALIDATE_INVALIDATE_TC);

	gpu_write(gpu, REG_A2XX_MH_ARBITER_CONFIG,
		A2XX_MH_ARBITER_CONFIG_SAME_PAGE_LIMIT(16) |
		A2XX_MH_ARBITER_CONFIG_L1_ARB_ENABLE |
		A2XX_MH_ARBITER_CONFIG_L1_ARB_HOLD_ENABLE |
		A2XX_MH_ARBITER_CONFIG_PAGE_SIZE(1) |
		A2XX_MH_ARBITER_CONFIG_TC_REORDER_ENABLE |
		A2XX_MH_ARBITER_CONFIG_TC_ARB_HOLD_ENABLE |
		A2XX_MH_ARBITER_CONFIG_IN_FLIGHT_LIMIT_ENABLE |
		A2XX_MH_ARBITER_CONFIG_IN_FLIGHT_LIMIT(8) |
		A2XX_MH_ARBITER_CONFIG_CP_CLNT_ENABLE |
		A2XX_MH_ARBITER_CONFIG_VGT_CLNT_ENABLE |
		A2XX_MH_ARBITER_CONFIG_TC_CLNT_ENABLE |
		A2XX_MH_ARBITER_CONFIG_RB_CLNT_ENABLE |
		A2XX_MH_ARBITER_CONFIG_PA_CLNT_ENABLE);
	if (!adreno_is_a20x(adreno_gpu))
		gpu_write(gpu, REG_A2XX_MH_CLNT_INTF_CTRL_CONFIG1, 0x00032f07);

	gpu_write(gpu, REG_A2XX_SQ_VS_PROGRAM, 0x00000000);
	gpu_write(gpu, REG_A2XX_SQ_PS_PROGRAM, 0x00000000);

	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE1, 0); /* 0x200 for msm8960? */
	/* A22x (Leia) requires 0x1a0 for proper clock gating per Palm kernel */
	if (!adreno_is_a20x(adreno_gpu))
		gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, 0x1a0);
	else
		gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, 0);

	/* A22X: Initialize GRAS and LRZ/VSC control registers to 0.
	 * KGSL initializes all registers via 18KB shadow memory, but freedreno
	 * doesn't have shadowing. Without explicit initialization, these
	 * registers can have random values causing intermittent rendering
	 * issues (e.g., faceted vs smooth surfaces in glmark2).
	 */
	if (!adreno_is_a20x(adreno_gpu)) {
		gpu_write(gpu, REG_A2XX_A220_RB_LRZ_VSC_CONTROL, 0);
		gpu_write(gpu, REG_A2XX_A220_GRAS_CONTROL, 0);
	}

	/* Initialize SQ_INTERPOLATOR_CNTL to 0xffffffff (all smooth interpolation).
	 * Debug logging revealed that the first submit happens before Mesa sets
	 * this register, leaving it at 0x00000000 (all flat shading). This causes
	 * intermittent faceted rendering when the GPU state from the first draw
	 * affects subsequent draws.
	 */
	gpu_write(gpu, REG_A2XX_SQ_INTERPOLATOR_CNTL, 0xffffffff);

	/* Initialize SQ_GPR_MANAGEMENT to allocate 64 GPRs each for VS/PS.
	 * KGSL initializes this to 0x00040400. Without proper initialization,
	 * random values from GPU power-on could starve one shader type of GPRs.
	 */
	gpu_write(gpu, REG_A2XX_SQ_GPR_MANAGEMENT, 0x00040400);

	/* note: gsl doesn't set this */
	gpu_write(gpu, REG_A2XX_RBBM_DEBUG, 0x00080000);

	gpu_write(gpu, REG_A2XX_RBBM_INT_CNTL,
		A2XX_RBBM_INT_CNTL_RDERR_INT_MASK);
	gpu_write(gpu, REG_AXXX_CP_INT_CNTL,
		AXXX_CP_INT_CNTL_T0_PACKET_IN_IB_MASK |
		AXXX_CP_INT_CNTL_OPCODE_ERROR_MASK |
		AXXX_CP_INT_CNTL_PROTECTED_MODE_ERROR_MASK |
		AXXX_CP_INT_CNTL_RESERVED_BIT_ERROR_MASK |
		AXXX_CP_INT_CNTL_IB_ERROR_MASK |
		AXXX_CP_INT_CNTL_IB1_INT_MASK |
		AXXX_CP_INT_CNTL_RB_INT_MASK);
	gpu_write(gpu, REG_A2XX_SQ_INT_CNTL, 0);
	gpu_write(gpu, REG_A2XX_MH_INTERRUPT_MASK,
		A2XX_MH_INTERRUPT_MASK_AXI_READ_ERROR |
		A2XX_MH_INTERRUPT_MASK_AXI_WRITE_ERROR |
		A2XX_MH_INTERRUPT_MASK_MMU_PAGE_FAULT);

	for (i = 3; i <= 5; i++)
		if ((SZ_16K << i) == adreno_gpu->info->gmem)
			break;
	gpu_write(gpu, REG_A2XX_RB_EDRAM_INFO, i);

	/* Set up performance counter 1 to count busy cycles for devfreq
	 * RBBM1_RB_BUSY counts when render backend is active (graphics work)
	 */
	gpu_write(gpu, REG_A2XX_RBBM_PERFCOUNTER1_SELECT, RBBM1_RB_BUSY);

	ret = adreno_hw_init(gpu);
	if (ret)
		return ret;

	gpu_write(gpu, REG_AXXX_CP_RB_CNTL,
		MSM_GPU_RB_CNTL_DEFAULT | AXXX_CP_RB_CNTL_NO_UPDATE);

	gpu_write(gpu, REG_AXXX_CP_RB_BASE, lower_32_bits(gpu->rb[0]->iova));

	/* NOTE: PM4/micro-engine firmware registers look to be the same
	 * for a2xx and a3xx.. we could possibly push that part down to
	 * adreno_gpu base class.  Or push both PM4 and PFP but
	 * parameterize the pfp ucode addr/data registers..
	 */

	/* Load PM4: */
	ptr = (uint32_t *)(adreno_gpu->fw[ADRENO_FW_PM4]->data);
	len = adreno_gpu->fw[ADRENO_FW_PM4]->size / 4;
	DBG("loading PM4 ucode version: %x", ptr[1]);

	/*
	 * New firmware files seem to have GPU and firmware version in this
	 * word (0x20xxxx for A200, 0x220xxx for A220, 0x225xxx for A225).
	 * Older firmware files, which lack protection support, have 0 instead.
	 */
	if (ptr[1] == 0) {
		dev_warn(gpu->dev->dev,
			 "Legacy firmware detected, disabling protection support\n");
		a2xx_gpu->protection_disabled = true;
	}

	gpu_write(gpu, REG_AXXX_CP_DEBUG,
			AXXX_CP_DEBUG_MIU_128BIT_WRITE_ENABLE);
	gpu_write(gpu, REG_AXXX_CP_ME_RAM_WADDR, 0);
	for (i = 1; i < len; i++)
		gpu_write(gpu, REG_AXXX_CP_ME_RAM_DATA, ptr[i]);

	/* Load PFP: */
	ptr = (uint32_t *)(adreno_gpu->fw[ADRENO_FW_PFP]->data);
	len = adreno_gpu->fw[ADRENO_FW_PFP]->size / 4;
	DBG("loading PFP ucode version: %x", ptr[5]);

	gpu_write(gpu, REG_A2XX_CP_PFP_UCODE_ADDR, 0);
	for (i = 1; i < len; i++)
		gpu_write(gpu, REG_A2XX_CP_PFP_UCODE_DATA, ptr[i]);

	gpu_write(gpu, REG_AXXX_CP_QUEUE_THRESHOLDS, 0x000C0804);

	/*
	 * Clear any pending CP interrupts before starting the micro engine.
	 * This matches the KGSL driver sequence and ensures the CP starts
	 * with a clean interrupt state, which is important for recovery.
	 */
	gpu_write(gpu, REG_AXXX_CP_INT_ACK, 0xFFFFFFFF);

	/*
	 * Reset ring pointers immediately before starting the ME.
	 * This matches the KGSL sequence where rb->rptr = rb->wptr = 0
	 * is set just before clearing ME_HALT. Critical for recovery.
	 */
	gpu->rb[0]->cur = gpu->rb[0]->next = gpu->rb[0]->start;
	gpu->rb[0]->memptrs->rptr = 0;
	gpu_write(gpu, REG_AXXX_CP_RB_WPTR, 0);

	/* clear ME_HALT to start micro engine */
	gpu_write(gpu, REG_AXXX_CP_ME_CNTL, 0);

	/*
	 * DIAGNOSTIC: dump key A2XX state at end of every hw_init. Fires once
	 * per pm_resume cycle, so each session start prints exactly one line.
	 * Use this to compare register state across sessions (kmscube on fresh
	 * boot vs kmscube after surface-manager).
	 */
	{
		static unsigned int hw_init_seq;

		pr_info("a2xx hw_init seq=%u: PT_BASE=%08x MMU_CONFIG=%08x "
			"TRAN_ERROR=%08x RBBM_STATUS=%08x "
			"PM_OVERRIDE1=%08x PM_OVERRIDE2=%08x "
			"SQ_INTERP=%08x SQ_GPR_MGMT=%08x\n",
			++hw_init_seq,
			gpu_read(gpu, REG_A2XX_MH_MMU_PT_BASE),
			gpu_read(gpu, REG_A2XX_MH_MMU_CONFIG),
			gpu_read(gpu, REG_A2XX_MH_MMU_TRAN_ERROR),
			gpu_read(gpu, REG_A2XX_RBBM_STATUS),
			gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE1),
			gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE2),
			gpu_read(gpu, REG_A2XX_SQ_INTERPOLATOR_CNTL),
			gpu_read(gpu, REG_A2XX_SQ_GPR_MANAGEMENT));
	}

	return a2xx_me_init(gpu) ? 0 : -EINVAL;
}

static void a2xx_recover(struct msm_gpu *gpu)
{
	int i;

	adreno_dump_info(gpu);

	for (i = 0; i < 8; i++) {
		printk("CP_SCRATCH_REG%d: %u\n", i,
			gpu_read(gpu, REG_AXXX_CP_SCRATCH_REG0 + i));
	}

	/* dump registers before resetting gpu, if enabled: */
	if (hang_debug)
		a2xx_dump(gpu);

	/*
	 * Perform a full GPU reset matching the sequence in a2xx_hw_init()
	 * and the legacy KGSL driver. A partial reset (0x1 = CP only) is
	 * insufficient when the GPU is truly hung.
	 *
	 * The sequence is:
	 * 1. Halt the micro engine to stop any in-flight operations
	 * 2. Power on all blocks via PM_OVERRIDE to ensure they can be reset
	 * 3. Assert full reset on ALL blocks (0xffffffff), not just CP
	 * 4. Wait 30ms for the reset to complete (per KGSL driver)
	 * 5. Deassert reset
	 */
	gpu_write(gpu, REG_AXXX_CP_ME_CNTL, AXXX_CP_ME_CNTL_HALT);

	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE1, 0xfffffffe);
	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, 0xffffffff);

	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0xffffffff);
	msleep(30);
	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0);

	adreno_recover(gpu);
}

static void a2xx_destroy(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);

	DBG("%s", gpu->name);

	if (a2xx_gpu->shadow_bo) {
		msm_gem_kernel_put(a2xx_gpu->shadow_bo, gpu->vm);
		a2xx_gpu->shadow_bo = NULL;
	}

	adreno_gpu_cleanup(adreno_gpu);

	kfree(a2xx_gpu);
}

/*
 * Mask of all RBBM_STATUS bits that indicate the GPU is busy.
 * Derived from the webOS KGSL driver which checks RBBM_STATUS == 0x110
 * for idle (only CMDFIFO_AVAIL and HIRQ_PENDING are allowed to be set).
 * All these bits must be clear for the gfx3d_axi_clk to halt properly.
 */
#define A2XX_RBBM_BUSY_MASK ( \
	A2XX_RBBM_STATUS_TC_BUSY | \
	A2XX_RBBM_STATUS_CPRQ_PENDING | \
	A2XX_RBBM_STATUS_CFRQ_PENDING | \
	A2XX_RBBM_STATUS_PFRQ_PENDING | \
	A2XX_RBBM_STATUS_VGT_BUSY_NO_DMA | \
	A2XX_RBBM_STATUS_RBBM_WU_BUSY | \
	A2XX_RBBM_STATUS_CP_NRT_BUSY | \
	A2XX_RBBM_STATUS_MH_BUSY | \
	A2XX_RBBM_STATUS_MH_COHERENCY_BUSY | \
	A2XX_RBBM_STATUS_SX_BUSY | \
	A2XX_RBBM_STATUS_TPC_BUSY | \
	A2XX_RBBM_STATUS_SC_CNTX_BUSY | \
	A2XX_RBBM_STATUS_PA_BUSY | \
	A2XX_RBBM_STATUS_VGT_BUSY | \
	A2XX_RBBM_STATUS_SQ_CNTX17_BUSY | \
	A2XX_RBBM_STATUS_SQ_CNTX0_BUSY | \
	A2XX_RBBM_STATUS_RB_CNTX_BUSY | \
	A2XX_RBBM_STATUS_GUI_ACTIVE)

static bool a2xx_idle(struct msm_gpu *gpu)
{
	uint32_t status;

	/* wait for ringbuffer to drain: */
	if (!adreno_idle(gpu, gpu->rb[0]))
		return false;

	/* then wait for GPU to finish: */
	if (spin_until(!(gpu_read(gpu, REG_A2XX_RBBM_STATUS) &
			A2XX_RBBM_STATUS_GUI_ACTIVE))) {
		DRM_ERROR("%s: timeout waiting for GPU to idle!\n", gpu->name);

		/* TODO maybe we need to reset GPU here to recover from hang? */
		return false;
	}

	/*
	 * Wait for ALL busy bits to clear, not just the obvious ones.
	 * The webOS KGSL driver waits for RBBM_STATUS == 0x110 (only
	 * CMDFIFO_AVAIL and HIRQ_PENDING set). If any busy bit remains
	 * set, the gfx3d_axi_clk branch clock cannot halt properly.
	 */
	if (spin_until(!((status = gpu_read(gpu, REG_A2XX_RBBM_STATUS)) &
			 A2XX_RBBM_BUSY_MASK))) {
		DRM_ERROR("%s: timeout waiting for GPU idle, RBBM_STATUS=%08x\n",
			  gpu->name, status);
		return false;
	}

	return true;
}

static irqreturn_t a2xx_irq(struct msm_gpu *gpu)
{
	uint32_t mstatus, status;

	mstatus = gpu_read(gpu, REG_A2XX_MASTER_INT_SIGNAL);

	if (mstatus & A2XX_MASTER_INT_SIGNAL_MH_INT_STAT) {
		uint32_t fault_addr, tran_err, rbbm_st;
		uint32_t rb_base, rb_rptr, rb_wptr;
		uint32_t ib1_base, ib1_bufsz;
		uint32_t clnt_cfg1, clnt_cfg2;

		status = gpu_read(gpu, REG_A2XX_MH_INTERRUPT_STATUS);
		fault_addr = gpu_read(gpu, REG_A2XX_MH_MMU_PAGE_FAULT);

		dev_warn(gpu->dev->dev, "MH_INT: %08X\n", status);
		dev_warn(gpu->dev->dev, "MMU_PAGE_FAULT: %08X\n", fault_addr);

		if (status & A2XX_MH_INTERRUPT_MASK_MMU_PAGE_FAULT) {
			/*
			 * Extra diagnostics for the deterministic
			 * 0xc000428b fault. Dumps where the CP was in
			 * the cmdstream, which IB, which MH client
			 * generated the bad access, and the AXI
			 * translation-error code.
			 */
			tran_err  = gpu_read(gpu, REG_A2XX_MH_MMU_TRAN_ERROR);
			rbbm_st   = gpu_read(gpu, REG_A2XX_RBBM_STATUS);
			rb_base   = gpu_read(gpu, REG_AXXX_CP_RB_BASE);
			rb_rptr   = gpu_read(gpu, REG_AXXX_CP_RB_RPTR);
			rb_wptr   = gpu_read(gpu, REG_AXXX_CP_RB_WPTR);
			ib1_base  = gpu_read(gpu, REG_AXXX_CP_IB1_BASE);
			ib1_bufsz = gpu_read(gpu, REG_AXXX_CP_IB1_BUFSZ);
			clnt_cfg1 = gpu_read(gpu, REG_A2XX_MH_CLNT_INTF_CTRL_CONFIG1);
			clnt_cfg2 = gpu_read(gpu, REG_A2XX_MH_CLNT_INTF_CTRL_CONFIG2);

			dev_warn(gpu->dev->dev,
				 "  TRAN_ERROR=%08x RBBM_STATUS=%08x\n",
				 tran_err, rbbm_st);
			dev_warn(gpu->dev->dev,
				 "  RB_BASE=%08x RPTR=%08x WPTR=%08x\n",
				 rb_base, rb_rptr, rb_wptr);
			dev_warn(gpu->dev->dev,
				 "  IB1_BASE=%08x IB1_BUFSZ=%08x\n",
				 ib1_base, ib1_bufsz);
			dev_warn(gpu->dev->dev,
				 "  MH_CLNT_INTF_CFG1=%08x CFG2=%08x\n",
				 clnt_cfg1, clnt_cfg2);

			a2xx_gpummu_debug_fault(to_msm_vm(gpu->vm)->mmu, fault_addr);

			/*
			 * Dump up to 64 dwords of the last submitted user IB1
			 * so we can grep for the offending pointer (0xc000428b)
			 * and find which packet / descriptor placed it there.
			 */
			if (a2xx_last_ib.ib1_kvaddr && a2xx_last_ib.ib1_size) {
				u32 dwords = min(a2xx_last_ib.ib1_size, 64u);
				u32 j;

				dev_warn(gpu->dev->dev,
					 "  last IB1 iova=%016llx size=%u dwords (dumping %u)\n",
					 a2xx_last_ib.ib1_iova,
					 a2xx_last_ib.ib1_size, dwords);

				for (j = 0; j < dwords; j += 8) {
					dev_warn(gpu->dev->dev,
					    "  +%03x: %08x %08x %08x %08x %08x %08x %08x %08x\n",
					    j * 4,
					    a2xx_last_ib.ib1_kvaddr[j + 0],
					    j + 1 < dwords ? a2xx_last_ib.ib1_kvaddr[j + 1] : 0,
					    j + 2 < dwords ? a2xx_last_ib.ib1_kvaddr[j + 2] : 0,
					    j + 3 < dwords ? a2xx_last_ib.ib1_kvaddr[j + 3] : 0,
					    j + 4 < dwords ? a2xx_last_ib.ib1_kvaddr[j + 4] : 0,
					    j + 5 < dwords ? a2xx_last_ib.ib1_kvaddr[j + 5] : 0,
					    j + 6 < dwords ? a2xx_last_ib.ib1_kvaddr[j + 6] : 0,
					    j + 7 < dwords ? a2xx_last_ib.ib1_kvaddr[j + 7] : 0);
				}
			}
		}

		gpu_write(gpu, REG_A2XX_MH_INTERRUPT_CLEAR, status);
	}

	if (mstatus & A2XX_MASTER_INT_SIGNAL_CP_INT_STAT) {
		status = gpu_read(gpu, REG_AXXX_CP_INT_STATUS);

		/* only RB_INT is expected */
		if (status & ~AXXX_CP_INT_CNTL_RB_INT_MASK)
			dev_warn(gpu->dev->dev, "CP_INT: %08X\n", status);

		gpu_write(gpu, REG_AXXX_CP_INT_ACK, status);
	}

	if (mstatus & A2XX_MASTER_INT_SIGNAL_RBBM_INT_STAT) {
		status = gpu_read(gpu, REG_A2XX_RBBM_INT_STATUS);

		dev_dbg(gpu->dev->dev, "RBBM_INT: %08X\n", status);

		gpu_write(gpu, REG_A2XX_RBBM_INT_ACK, status);
	}

	msm_gpu_retire(gpu);

	return IRQ_HANDLED;
}

static const unsigned int a200_registers[] = {
	0x0000, 0x0002, 0x0004, 0x000B, 0x003B, 0x003D, 0x0040, 0x0044,
	0x0046, 0x0047, 0x01C0, 0x01C1, 0x01C3, 0x01C8, 0x01D5, 0x01D9,
	0x01DC, 0x01DD, 0x01EA, 0x01EA, 0x01EE, 0x01F3, 0x01F6, 0x01F7,
	0x01FC, 0x01FF, 0x0391, 0x0392, 0x039B, 0x039E, 0x03B2, 0x03B5,
	0x03B7, 0x03B7, 0x03F8, 0x03FB, 0x0440, 0x0440, 0x0443, 0x0444,
	0x044B, 0x044B, 0x044D, 0x044F, 0x0452, 0x0452, 0x0454, 0x045B,
	0x047F, 0x047F, 0x0578, 0x0587, 0x05C9, 0x05C9, 0x05D0, 0x05D0,
	0x0601, 0x0604, 0x0606, 0x0609, 0x060B, 0x060E, 0x0613, 0x0614,
	0x0A29, 0x0A2B, 0x0A2F, 0x0A31, 0x0A40, 0x0A43, 0x0A45, 0x0A45,
	0x0A4E, 0x0A4F, 0x0C2C, 0x0C2C, 0x0C30, 0x0C30, 0x0C38, 0x0C3C,
	0x0C40, 0x0C40, 0x0C44, 0x0C44, 0x0C80, 0x0C86, 0x0C88, 0x0C94,
	0x0C99, 0x0C9A, 0x0CA4, 0x0CA5, 0x0D00, 0x0D03, 0x0D06, 0x0D06,
	0x0D08, 0x0D0B, 0x0D34, 0x0D35, 0x0DAE, 0x0DC1, 0x0DC8, 0x0DD4,
	0x0DD8, 0x0DD9, 0x0E00, 0x0E00, 0x0E02, 0x0E04, 0x0E17, 0x0E1E,
	0x0EC0, 0x0EC9, 0x0ECB, 0x0ECC, 0x0ED0, 0x0ED0, 0x0ED4, 0x0ED7,
	0x0EE0, 0x0EE2, 0x0F01, 0x0F02, 0x0F0C, 0x0F0C, 0x0F0E, 0x0F12,
	0x0F26, 0x0F2A, 0x0F2C, 0x0F2C, 0x2000, 0x2002, 0x2006, 0x200F,
	0x2080, 0x2082, 0x2100, 0x2109, 0x210C, 0x2114, 0x2180, 0x2184,
	0x21F5, 0x21F7, 0x2200, 0x2208, 0x2280, 0x2283, 0x2293, 0x2294,
	0x2300, 0x2308, 0x2312, 0x2312, 0x2316, 0x231D, 0x2324, 0x2326,
	0x2380, 0x2383, 0x2400, 0x2402, 0x2406, 0x240F, 0x2480, 0x2482,
	0x2500, 0x2509, 0x250C, 0x2514, 0x2580, 0x2584, 0x25F5, 0x25F7,
	0x2600, 0x2608, 0x2680, 0x2683, 0x2693, 0x2694, 0x2700, 0x2708,
	0x2712, 0x2712, 0x2716, 0x271D, 0x2724, 0x2726, 0x2780, 0x2783,
	0x4000, 0x4003, 0x4800, 0x4805, 0x4900, 0x4900, 0x4908, 0x4908,
	~0   /* sentinel */
};

static const unsigned int a220_registers[] = {
	0x0000, 0x0002, 0x0004, 0x000B, 0x003B, 0x003D, 0x0040, 0x0044,
	0x0046, 0x0047, 0x01C0, 0x01C1, 0x01C3, 0x01C8, 0x01D5, 0x01D9,
	0x01DC, 0x01DD, 0x01EA, 0x01EA, 0x01EE, 0x01F3, 0x01F6, 0x01F7,
	0x01FC, 0x01FF, 0x0391, 0x0392, 0x039B, 0x039E, 0x03B2, 0x03B5,
	0x03B7, 0x03B7, 0x03F8, 0x03FB, 0x0440, 0x0440, 0x0443, 0x0444,
	0x044B, 0x044B, 0x044D, 0x044F, 0x0452, 0x0452, 0x0454, 0x045B,
	0x047F, 0x047F, 0x0578, 0x0587, 0x05C9, 0x05C9, 0x05D0, 0x05D0,
	0x0601, 0x0604, 0x0606, 0x0609, 0x060B, 0x060E, 0x0613, 0x0614,
	0x0A29, 0x0A2B, 0x0A2F, 0x0A31, 0x0A40, 0x0A40, 0x0A42, 0x0A43,
	0x0A45, 0x0A45, 0x0A4E, 0x0A4F, 0x0C30, 0x0C30, 0x0C38, 0x0C39,
	0x0C3C, 0x0C3C, 0x0C80, 0x0C81, 0x0C88, 0x0C93, 0x0D00, 0x0D03,
	0x0D05, 0x0D06, 0x0D08, 0x0D0B, 0x0D34, 0x0D35, 0x0DAE, 0x0DC1,
	0x0DC8, 0x0DD4, 0x0DD8, 0x0DD9, 0x0E00, 0x0E00, 0x0E02, 0x0E04,
	0x0E17, 0x0E1E, 0x0EC0, 0x0EC9, 0x0ECB, 0x0ECC, 0x0ED0, 0x0ED0,
	0x0ED4, 0x0ED7, 0x0EE0, 0x0EE2, 0x0F01, 0x0F02, 0x2000, 0x2002,
	0x2006, 0x200F, 0x2080, 0x2082, 0x2100, 0x2102, 0x2104, 0x2109,
	0x210C, 0x2114, 0x2180, 0x2184, 0x21F5, 0x21F7, 0x2200, 0x2202,
	0x2204, 0x2204, 0x2208, 0x2208, 0x2280, 0x2282, 0x2294, 0x2294,
	0x2300, 0x2308, 0x2309, 0x230A, 0x2312, 0x2312, 0x2316, 0x2316,
	0x2318, 0x231D, 0x2324, 0x2326, 0x2380, 0x2383, 0x2400, 0x2402,
	0x2406, 0x240F, 0x2480, 0x2482, 0x2500, 0x2502, 0x2504, 0x2509,
	0x250C, 0x2514, 0x2580, 0x2584, 0x25F5, 0x25F7, 0x2600, 0x2602,
	0x2604, 0x2606, 0x2608, 0x2608, 0x2680, 0x2682, 0x2694, 0x2694,
	0x2700, 0x2708, 0x2712, 0x2712, 0x2716, 0x2716, 0x2718, 0x271D,
	0x2724, 0x2726, 0x2780, 0x2783,
	/*
	 * Extended constant-memory coverage for state-leak debugging.
	 * Covers the full A2XX shader-constant SRAM as MMIO so the
	 * /sys/kernel/debug/dri/0/gpu hangdump shows whether stale
	 * constant data leaks across DRM-client transitions.
	 *
	 *   0x4000..0x40FF  256 vec4 ALU constants (64 dwords each
	 *                   for VS at offset 0x20, PS at offset 0x120
	 *                   per Mesa's PS_CONST_BASE / VS_CONST_BASE)
	 *   0x4800..0x48BF  32 texture-fetch constants (6 dwords each)
	 *   0x4900..0x4907  8 dwords boolean constants (256 bool flags)
	 *   0x4908..0x493F  56 dwords loop control constants
	 */
	0x4000, 0x40FF, 0x4800, 0x48BF, 0x4900, 0x4907, 0x4908, 0x493F,
	~0   /* sentinel */
};

static const unsigned int a225_registers[] = {
	0x0000, 0x0002, 0x0004, 0x000B, 0x003B, 0x003D, 0x0040, 0x0044,
	0x0046, 0x0047, 0x013C, 0x013C, 0x0140, 0x014F, 0x01C0, 0x01C1,
	0x01C3, 0x01C8, 0x01D5, 0x01D9, 0x01DC, 0x01DD, 0x01EA, 0x01EA,
	0x01EE, 0x01F3, 0x01F6, 0x01F7, 0x01FC, 0x01FF, 0x0391, 0x0392,
	0x039B, 0x039E, 0x03B2, 0x03B5, 0x03B7, 0x03B7, 0x03F8, 0x03FB,
	0x0440, 0x0440, 0x0443, 0x0444, 0x044B, 0x044B, 0x044D, 0x044F,
	0x0452, 0x0452, 0x0454, 0x045B, 0x047F, 0x047F, 0x0578, 0x0587,
	0x05C9, 0x05C9, 0x05D0, 0x05D0, 0x0601, 0x0604, 0x0606, 0x0609,
	0x060B, 0x060E, 0x0613, 0x0614, 0x0A29, 0x0A2B, 0x0A2F, 0x0A31,
	0x0A40, 0x0A40, 0x0A42, 0x0A43, 0x0A45, 0x0A45, 0x0A4E, 0x0A4F,
	0x0C01, 0x0C1D, 0x0C30, 0x0C30, 0x0C38, 0x0C39, 0x0C3C, 0x0C3C,
	0x0C80, 0x0C81, 0x0C88, 0x0C93, 0x0D00, 0x0D03, 0x0D05, 0x0D06,
	0x0D08, 0x0D0B, 0x0D34, 0x0D35, 0x0DAE, 0x0DC1, 0x0DC8, 0x0DD4,
	0x0DD8, 0x0DD9, 0x0E00, 0x0E00, 0x0E02, 0x0E04, 0x0E17, 0x0E1E,
	0x0EC0, 0x0EC9, 0x0ECB, 0x0ECC, 0x0ED0, 0x0ED0, 0x0ED4, 0x0ED7,
	0x0EE0, 0x0EE2, 0x0F01, 0x0F02, 0x2000, 0x200F, 0x2080, 0x2082,
	0x2100, 0x2109, 0x210C, 0x2114, 0x2180, 0x2184, 0x21F5, 0x21F7,
	0x2200, 0x2202, 0x2204, 0x2206, 0x2208, 0x2210, 0x2220, 0x2222,
	0x2280, 0x2282, 0x2294, 0x2294, 0x2297, 0x2297, 0x2300, 0x230A,
	0x2312, 0x2312, 0x2315, 0x2316, 0x2318, 0x231D, 0x2324, 0x2326,
	0x2340, 0x2357, 0x2360, 0x2360, 0x2380, 0x2383, 0x2400, 0x240F,
	0x2480, 0x2482, 0x2500, 0x2509, 0x250C, 0x2514, 0x2580, 0x2584,
	0x25F5, 0x25F7, 0x2600, 0x2602, 0x2604, 0x2606, 0x2608, 0x2610,
	0x2620, 0x2622, 0x2680, 0x2682, 0x2694, 0x2694, 0x2697, 0x2697,
	0x2700, 0x270A, 0x2712, 0x2712, 0x2715, 0x2716, 0x2718, 0x271D,
	0x2724, 0x2726, 0x2740, 0x2757, 0x2760, 0x2760, 0x2780, 0x2783,
	0x4000, 0x4003, 0x4800, 0x4806, 0x4808, 0x4808, 0x4900, 0x4900,
	0x4908, 0x4908,
	~0   /* sentinel */
};

/* would be nice to not have to duplicate the _show() stuff with printk(): */
static void a2xx_dump(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);

	printk("======== A2XX GPU Register Dump ========\n");
	printk("GPU: %s\n", adreno_is_a20x(adreno_gpu) ? "A20X (Yamato)" : "A22X (Leia)");

	/* Status registers */
	printk("STATUS REGISTERS:\n");
	printk("  RBBM_STATUS (0x05d0) = %08x\n",
			gpu_read(gpu, REG_A2XX_RBBM_STATUS));
	printk("  CP_RB_RPTR = %08x, CP_RB_WPTR = %08x\n",
			gpu_read(gpu, REG_AXXX_CP_RB_RPTR),
			gpu_read(gpu, REG_AXXX_CP_RB_WPTR));

	/* Critical shader registers - these affect rendering quality */
	printk("SHADER REGISTERS:\n");
	printk("  SQ_GPR_MANAGEMENT (0x0d00) = %08x\n",
			gpu_read(gpu, REG_A2XX_SQ_GPR_MANAGEMENT));
	printk("  SQ_INST_STORE_MANAGMENT (0x0d02) = %08x\n",
			gpu_read(gpu, REG_A2XX_SQ_INST_STORE_MANAGMENT));
	printk("  SQ_INTERPOLATOR_CNTL (0x2182) = %08x\n",
			gpu_read(gpu, REG_A2XX_SQ_INTERPOLATOR_CNTL));

	/* Power management */
	printk("POWER MANAGEMENT:\n");
	printk("  RBBM_PM_OVERRIDE1 (0x039c) = %08x\n",
			gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE1));
	printk("  RBBM_PM_OVERRIDE2 (0x039d) = %08x\n",
			gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE2));

	/* A22X specific */
	if (!adreno_is_a20x(adreno_gpu)) {
		printk("A22X SPECIFIC:\n");
		printk("  A220_RB_LRZ_VSC_CONTROL (0x2209) = %08x\n",
				gpu_read(gpu, REG_A2XX_A220_RB_LRZ_VSC_CONTROL));
		printk("  A220_GRAS_CONTROL (0x2210) = %08x\n",
				gpu_read(gpu, REG_A2XX_A220_GRAS_CONTROL));
	}

	printk("========================================\n");
	adreno_dump(gpu);
}

static struct msm_gpu_state *a2xx_gpu_state_get(struct msm_gpu *gpu)
{
	struct msm_gpu_state *state = kzalloc(sizeof(*state), GFP_KERNEL);

	if (!state)
		return ERR_PTR(-ENOMEM);

	adreno_gpu_state_get(gpu, state);

	state->rbbm_status = gpu_read(gpu, REG_A2XX_RBBM_STATUS);

	return state;
}

static u64 a2xx_gpu_busy(struct msm_gpu *gpu, unsigned long *out_sample_rate)
{
	u64 busy_cycles;

	busy_cycles = gpu_read64(gpu, REG_A2XX_RBBM_PERFCOUNTER1_LO);
	*out_sample_rate = clk_get_rate(gpu->core_clk);

	return busy_cycles;
}

static struct drm_gpuvm *
a2xx_create_vm(struct msm_gpu *gpu, struct platform_device *pdev)
{
	struct msm_mmu *mmu = a2xx_gpummu_new(&pdev->dev, gpu);
	struct drm_gpuvm *vm;

	vm = msm_gem_vm_create(gpu->dev, mmu, "gpu", SZ_16M, 0xfff * SZ_64K, true);

	if (IS_ERR(vm) && !IS_ERR(mmu))
		mmu->funcs->destroy(mmu);

	return vm;
}

static u32 a2xx_get_rptr(struct msm_gpu *gpu, struct msm_ringbuffer *ring)
{
	ring->memptrs->rptr = gpu_read(gpu, REG_AXXX_CP_RB_RPTR);
	return ring->memptrs->rptr;
}

static int a2xx_pm_suspend(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);

	/*
	 * Idle the GPU and wait for all AXI transactions to complete.
	 * Without this the gfx3d_axi_clk branch clock cannot halt
	 * because the AXI bus is still servicing GPU requests.
	 */
	if (!a2xx_idle(gpu)) {
		dev_warn(gpu->dev->dev, "GPU didn't idle before suspend\n");

		/*
		 * GPU failed to idle normally. Halt the command processor
		 * and perform a soft reset to force the AXI interface into
		 * a quiescent state. This ensures the gfx3d_axi_clk branch
		 * clock can be disabled even if the GPU was stuck.
		 */
		gpu_write(gpu, REG_AXXX_CP_ME_CNTL, AXXX_CP_ME_CNTL_HALT);

		gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 1);
		gpu_read(gpu, REG_A2XX_RBBM_SOFT_RESET);
		gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0);

		/* Wait for reset to complete */
		udelay(100);
	}

	/*
	 * Memory barrier to ensure all AXI transactions have completed
	 * before we clear the interconnect vote. This is critical on
	 * non-coherent platforms like MSM8660.
	 */
	wmb();

	/*
	 * Clear interconnect bandwidth vote before disabling clocks.
	 * This tells the bus fabric we no longer need memory bandwidth,
	 * allowing the AXI clock to halt properly. The legacy KGSL
	 * driver did this via msm_bus_scale_client_update_request(BW_INIT).
	 */
	if (a2xx_gpu->icc_path)
		icc_set_bw(a2xx_gpu->icc_path, 0, 0);

	/*
	 * Allow time for the interconnect state change to propagate
	 * through the bus fabric before disabling clocks.
	 */
	udelay(10);

	return msm_gpu_pm_suspend(gpu);
}

static int a2xx_pm_resume(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	int ret;

	ret = msm_gpu_pm_resume(gpu);
	if (ret)
		return ret;

	/* Restore bandwidth after resume (cleared in suspend) */
	if (a2xx_gpu->icc_path) {
		u32 bw = a2xx_icc_bw_for_freq(gpu->fast_rate);

		icc_set_bw(a2xx_gpu->icc_path, bw, bw);
	}

	return 0;
}

/*
 * Set GPU frequency and bandwidth via OPP framework.
 * This is called by devfreq when scaling frequency.
 */
static void a2xx_gpu_set_freq(struct msm_gpu *gpu, struct dev_pm_opp *opp,
			      bool suspended)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	unsigned long freq = dev_pm_opp_get_freq(opp);

	/*
	 * Don't change bandwidth when suspended - pm_resume will restore it.
	 * Only update our manual ICC path bandwidth to match the new frequency.
	 */
	if (suspended)
		return;

	/*
	 * Set both avg and peak bandwidth proportional to frequency,
	 * matching the legacy webOS msm_bus grp3d_max_vectors pattern
	 * (ab = ib = clock × 8 bytes/cycle).
	 */
	if (a2xx_gpu->icc_path) {
		u32 bw = a2xx_icc_bw_for_freq(freq);

		icc_set_bw(a2xx_gpu->icc_path, bw, bw);
	}

	dev_pm_opp_set_opp(&gpu->pdev->dev, opp);
}

static const struct adreno_gpu_funcs funcs = {
	.base = {
		.get_param = adreno_get_param,
		.set_param = adreno_set_param,
		.hw_init = a2xx_hw_init,
		.pm_suspend = a2xx_pm_suspend,
		.pm_resume = a2xx_pm_resume,
		.recover = a2xx_recover,
		.submit = a2xx_submit,
		.active_ring = adreno_active_ring,
		.irq = a2xx_irq,
		.destroy = a2xx_destroy,
#if defined(CONFIG_DEBUG_FS) || defined(CONFIG_DEV_COREDUMP)
		.show = adreno_show,
#endif
#if defined(CONFIG_DEBUG_FS)
		.debugfs_init = a2xx_debugfs_init,
#endif
		.gpu_busy = a2xx_gpu_busy,
		.gpu_state_get = a2xx_gpu_state_get,
		.gpu_state_put = adreno_gpu_state_put,
		.create_vm = a2xx_create_vm,
		.get_rptr = a2xx_get_rptr,
		.gpu_set_freq = a2xx_gpu_set_freq,
	},
};

static const struct msm_gpu_perfcntr perfcntrs[] = {
/* TODO */
};

struct msm_gpu *a2xx_gpu_init(struct drm_device *dev)
{
	struct a2xx_gpu *a2xx_gpu = NULL;
	struct adreno_gpu *adreno_gpu;
	struct msm_gpu *gpu;
	struct msm_drm_private *priv = dev->dev_private;
	struct platform_device *pdev = priv->gpu_pdev;
	int ret;

	if (!pdev) {
		dev_err(dev->dev, "no a2xx device\n");
		ret = -ENXIO;
		goto fail;
	}

	a2xx_gpu = kzalloc(sizeof(*a2xx_gpu), GFP_KERNEL);
	if (!a2xx_gpu) {
		ret = -ENOMEM;
		goto fail;
	}

	adreno_gpu = &a2xx_gpu->base;
	gpu = &adreno_gpu->base;

	gpu->perfcntrs = perfcntrs;
	gpu->num_perfcntrs = ARRAY_SIZE(perfcntrs);

	ret = adreno_gpu_init(dev, pdev, adreno_gpu, &funcs, 1);
	if (ret)
		goto fail;

	/* Get interconnect path for memory bandwidth voting */
	a2xx_gpu->icc_path = devm_of_icc_get(&pdev->dev, "gfx-mem");
	if (IS_ERR(a2xx_gpu->icc_path)) {
		ret = PTR_ERR(a2xx_gpu->icc_path);
		/* Allow -ENODATA, interconnect is optional for older DTs */
		if (ret != -ENODATA) {
			DRM_DEV_ERROR(dev->dev, "failed to get interconnect path: %d\n", ret);
			goto fail;
		}
		a2xx_gpu->icc_path = NULL;
	}

	/*
	 * Set initial interconnect bandwidth to max (avg = peak), matching
	 * legacy webOS grp3d_max_vectors. Adjusted during runtime PM and
	 * devfreq scaling.
	 */
	if (a2xx_gpu->icc_path) {
		u32 bw = a2xx_icc_bw_for_freq(gpu->fast_rate);

		icc_set_bw(a2xx_gpu->icc_path, bw, bw);
	}

	if (adreno_is_a20x(adreno_gpu))
		adreno_gpu->registers = a200_registers;
	else if (adreno_is_a225(adreno_gpu))
		adreno_gpu->registers = a225_registers;
	else
		adreno_gpu->registers = a220_registers;

	return gpu;

fail:
	if (a2xx_gpu)
		a2xx_destroy(&a2xx_gpu->base.base);

	return ERR_PTR(ret);
}
