// SPDX-License-Identifier: GPL-2.0
/* Copyright (c) 2018 The Linux Foundation. All rights reserved. */

#include <linux/debugfs.h>
#include <linux/delay.h>
#include <linux/interconnect.h>
#include <linux/pm_opp.h>

#include <drm/drm_file.h>

#include "a2xx_gpu.h"
#include "a2xx_debug.h"
#include "msm_gem.h"
#include "msm_mmu.h"

extern bool hang_debug;

/*
 * DIAGNOSTIC: when set to true, skip emitting the cross-context
 * sanitizer preamble (8x ALU/TEX/Bool/Loop scrub). Used to determine
 * whether the deterministic 0xc000428b MMU page fault is generated by
 * the kernel preamble or by user-space (Mesa) IB content.
 *
 *   echo 1 > /sys/module/msm/parameters/a2xx_skip_preamble  - disable
 *   echo 0 > /sys/module/msm/parameters/a2xx_skip_preamble  - re-enable
 *
 * Defaults to false (preamble emitted).
 */
bool a2xx_skip_preamble = false;
module_param(a2xx_skip_preamble, bool, 0644);
MODULE_PARM_DESC(a2xx_skip_preamble,
		 "skip a2xx cross-context sanitizer preamble (0=emit, 1=skip)");

/*
 * Option H (per SoC-init audit 2026-05-11): replicate webOS
 * msm_clk_soc_init() boot-time GFX3D reset that mainline never does.
 *
 * webOS arch/arm/mach-msm/clock-8x60.c:2560-2567 sequence:
 *   local_clk_set_rate(GFX3D, 27 MHz);
 *   local_clk_enable(GFX3D);          // clock running
 *   writel(BIT(12), SW_RESET_CORE_REG);
 *   udelay(5);
 *   writel(0, SW_RESET_CORE_REG);
 *   local_clk_disable(GFX3D);
 *
 * The reset is asserted with the clock running so flop clock-edges
 * latch the reset value through all internal state - including the
 * SQ wavefront SRAM that survives our existing RBBM_SOFT_RESET pulse
 * and that update-27 register-invariance proved holds the 8-cycle.
 *
 * Mainline only resets GFX3D via the GDSC enable path (per-pm_runtime
 * cycle), and that path is gated by LEGACY_FOOTSWITCH SW_RESET flag
 * which is missing from msm8660's gfx3d_gdsc definition. So the
 * outer GFX3D core reset has effectively never run on this kernel.
 *
 * Run once per kernel uptime at first a2xx_hw_init. By that point
 * the GFX3D rail is on and the core clock is running (pm_runtime
 * resume has fired), matching webOS's "clock enabled during reset".
 */
bool a2xx_boot_reset_enable = true;
module_param(a2xx_boot_reset_enable, bool, 0644);
MODULE_PARM_DESC(a2xx_boot_reset_enable,
		 "one-shot MMCC SW_RESET_CORE_REG BIT(12) pulse at first "
		 "a2xx_hw_init to replicate webOS boot-time GFX3D reset. "
		 "Audit 2026-05-11 identified this as the missing SoC-init "
		 "delta vs webOS - hypothesis is it clears SQ wavefront "
		 "SRAM cleanly without GMEM disturbance (1=enable, default).");

/*
 * Number of iterations of the sanitizer-preamble constant-scrub loop.
 *
 * Empirical (2026-05-11 100-cap test with a2xx_skip_preamble=Y vs N):
 * 8 iterations advance the cycle phase by +4 slots. If slot-advance
 * scales linearly with iteration count, 16 iterations should advance
 * by +8 slots = a full cycle = every submit lands on the same slot =
 * cycle collapse to a single hash.
 *
 * Linear-scaling hypothesis is testable cheaply with this knob without
 * a kernel rebuild. If 16 collapses the cycle, we ship at 16. If it
 * just shifts to a different 8-cycle phase, scaling is non-linear and
 * we need the dummy-draw scrub instead.
 */
uint a2xx_scrub_iterations = 8;
module_param(a2xx_scrub_iterations, uint, 0644);
MODULE_PARM_DESC(a2xx_scrub_iterations,
		 "iterations of constant-scrub loop in sanitizer preamble. "
		 "Default 8 (current). Try 16 to test linear slot-advance "
		 "hypothesis (8 iter = +4 slot phase shift, so 16 iter "
		 "would be +8 = full cycle = collapse to single hash).");

/*
 * Option G (real): kernel-side dummy-draw scrub of SQ wavefront slots.
 *
 * Prior experiments showed constant-load scrubs (Mesa 0081, kernel 8x
 * loop) and reset pulses (Option H) all leave the 8-cycle intact -
 * the cycle's seat is in internal SQ wavefront SRAM that only an actual
 * DRAW packet can advance. Per Gemini AI's analysis, each CP_DRAW_INDX
 * is one of the few PM4 packets that DEFINITIVELY consumes a wavefront
 * slot. 8 dummy draws => 8 slot advances => all slots touched with our
 * scrub state => cycle should collapse to one hash.
 *
 * Previous Mesa-side attempt (patch 0070) hung the GPU using
 * SQ_PROGRAM_CNTL with VS_REGS=63 + RECTLIST. Per Gemini, 32 GPRs is
 * safer than 63. KGSL's gmem2sys_vtx_pgm/frag_pgm uses minimal regs
 * with a known-working SQ_PROGRAM_CNTL Leia value 0x10018001, so we
 * lift those verbatim.
 *
 * State setup based on KGSL build_gmem2sys_cmds (kgsl_drawctxt.c:646-
 * 853): valid shaders, scissor=tiny, color writes masked off (so the
 * draws produce no visible output), POINTLIST count=1 (minimum cost).
 *
 * Default OFF for safety - flip to Y to test, leave OFF if it hangs.
 */
bool a2xx_dummy_draw_enable = false;
module_param(a2xx_dummy_draw_enable, bool, 0644);
MODULE_PARM_DESC(a2xx_dummy_draw_enable,
		 "emit 8 dummy POINT draws at end of sanitizer preamble to "
		 "advance the SQ wavefront slot pointer (Option G proper). "
		 "Default OFF - enable to test. Risk: GPU hang if state "
		 "setup is off, the original Mesa-side variant (patch 0070) "
		 "hung the GPU.");

/*
 * Option I (Gemini hypothesis A - update 28 reply): pin CP_SCRATCH_REG0..7
 * to zero at start of every sanitizer preamble.
 *
 * Theory: the period-8 render cycle is a firmware-managed "submit phase
 * counter" that lives in CP_SCRATCH_REG. The CP firmware uses (or appears
 * to use) the lower bits as a context ID indexing internal SQ/VPC SRAM
 * for varying interpolation. Since mainline never writes these registers
 * (treating them as firmware-owned), the counter increments naturally
 * across CP_INDIRECT_BUFFER calls, producing the 8-cycle.
 *
 * Pinning all 8 scratch regs to 0 at every cross-context boundary forces
 * every submit to land on the same firmware-side phase, hypothesised to
 * collapse the cycle to a single hash (ideally bit-exact 5adc3160 since
 * that's what slot 0 produces in our prior testing).
 *
 * This is the cheapest remaining test - 8 MMIO writes per preamble.
 * Either falsifies hypothesis A or confirms the cycle's root cause.
 * Default ON for the test pass.
 */
bool a2xx_scratch_reset_enable = true;
module_param(a2xx_scratch_reset_enable, bool, 0644);
MODULE_PARM_DESC(a2xx_scratch_reset_enable,
		 "zero CP_SCRATCH_REG0..7 at start of sanitizer preamble "
		 "(Option I - Gemini hypothesis A about firmware phase "
		 "counter). Default ON to test; toggle OFF for A/B control.");

/*
 * CP_REG: encode a register-write CP_SET_CONSTANT header for registers
 * in the 0x2000+ range. Mirrors Mesa freedreno's CP_REG macro
 * (freedreno_util.h:223) - the type-4 constant-context selector and
 * register-offset minus the 0x2000 base.
 *
 * Used only by the Option G dummy-draw scrub below. The existing
 * preamble code emits raw type-0 ALU / type-1 TEX / etc. constants
 * via different encodings (see scrub loop above).
 */
#define CP_REG(reg) ((0x4 << 16) | ((unsigned int)((reg) - 0x2000)))

/*
 * Scrub shaders lifted from legacy KGSL kgsl_drawctxt.c. These are
 * the smallest known-working A2XX shaders that compile to valid
 * wavefront-consuming draws on Adreno 220/Leia. We don't care about
 * their output (color writes are masked off) - we just need them to
 * be valid so DRAW_INDX doesn't crash the SQ.
 */
static const u32 a2xx_scrub_vs_pgm[] = {
	/* gmem2sys_vtx_pgm: simple "pass through position" VS */
	0x00011003, 0x00001000, 0xc2000000,
	0x00001004, 0x00001000, 0xc4000000,
	0x00001005, 0x00002000, 0x00000000,
	0x1cb81000, 0x00398a88, 0x00000003,
	0x140f803e, 0x00000000, 0xe2010100,
	0x14000000, 0x00000000, 0xe2000000,
};

static const u32 a2xx_scrub_fs_pgm[] = {
	/* gmem2sys_frag_pgm: minimal "output clear color" FS */
	0x00000000, 0x1002c400, 0x10000000,
	0x00001003, 0x00002000, 0x00000000,
	0x140f8000, 0x00000000, 0x22000000,
	0x14000000, 0x00000000, 0xe2000000,
};

#define A2XX_MMCC_GFX3D_GDSCR	0x04000188	/* MMCC + 0x188 */
#define A2XX_MMCC_GFX3D_RESET	0x04000210	/* MMCC + 0x210 */
#define A2XX_GDSCR_CLAMP	BIT(5)		/* LEGACY_FS_CLAMP_MASK */
#define A2XX_GDSCR_ENABLE	BIT(8)		/* LEGACY_FS_ENABLE_MASK */
#define A2XX_GDSCR_RETENTION	BIT(9)		/* LEGACY_FS_RETENTION_MASK */
#define A2XX_GFX3D_RESET_BIT	BIT(12)		/* GFX3D_RESET in MMCC 0x0210 */

/*
 * Pre-WPTR sync knobs (period-8 cycle investigation):
 *
 *   a2xx_rbbm_poll_enable: poll REG_A2XX_RBBM_STATUS sub-block bits before
 *     each WPTR write. Falls back to mdelay(10) on >50ms timeout. Default on.
 *
 *   a2xx_rbbm_poll_mask: which RBBM_STATUS bits to spin on. The default
 *     covers the sub-blocks Gemini's analysis identified as the "real" idle
 *     signal (GUI_ACTIVE drops too early and is decorative):
 *       0x00010000  CP_NRT_BUSY      (CP non-render traffic, sync tokens)
 *       0x00040000  MH_BUSY          (memory hub - cache evictions etc.)
 *       0x00080000  MH_COHERENCY_BUSY
 *       0x08000000  SQ_CNTX17_BUSY   (shader context)
 *       0x10000000  SQ_CNTX0_BUSY
 *       0x40000000  RB_CNTX_BUSY     (render backend)
 *     Set 0x80000000 to revert to legacy GUI_ACTIVE behaviour, or any
 *     other combination to A/B without rebuilding.
 *
 *   a2xx_wptr_poll_enable: enable legacy KGSL WPTR-polling mode (CP polls a
 *     coherent memory mirror of WPTR rather than relying solely on the
 *     register write). Programs RB_CNTL.POLL_EN, RB_WPTR_BASE, RB_WPTR_DELAY
 *     at hw_init and writes ring->memptrs->wptr on each submit. Requires
 *     hw_init to take effect (sysrq b reboot or rmmod/insmod the gpu).
 *     Default off (set true to test). KNOWN BROKEN: hangs at ME_INIT,
 *     under investigation.
 *
 *   a2xx_wptr_poll_delay: value programmed into REG_AXXX_CP_RB_WPTR_DELAY
 *     when WPTR-polling is enabled. KGSL uses 0; an alternate value
 *     0x70000010 was commented in the legacy source. Default 0.
 */
bool a2xx_rbbm_poll_enable = true;
module_param(a2xx_rbbm_poll_enable, bool, 0644);
MODULE_PARM_DESC(a2xx_rbbm_poll_enable,
		 "poll RBBM_STATUS sub-block bits before WPTR write (0=skip, 1=poll)");

uint a2xx_rbbm_poll_mask =
	A2XX_RBBM_STATUS_CP_NRT_BUSY |
	A2XX_RBBM_STATUS_MH_BUSY |
	A2XX_RBBM_STATUS_MH_COHERENCY_BUSY |
	A2XX_RBBM_STATUS_SQ_CNTX17_BUSY |
	A2XX_RBBM_STATUS_SQ_CNTX0_BUSY |
	A2XX_RBBM_STATUS_RB_CNTX_BUSY;
module_param(a2xx_rbbm_poll_mask, uint, 0644);
MODULE_PARM_DESC(a2xx_rbbm_poll_mask,
		 "bitmask of RBBM_STATUS bits to spin on (default: CP_NRT|MH|MH_COH|SQ_CNTX0/17|RB_CNTX)");

bool a2xx_wptr_poll_enable = false;
module_param(a2xx_wptr_poll_enable, bool, 0644);
MODULE_PARM_DESC(a2xx_wptr_poll_enable,
		 "enable legacy KGSL WPTR-polling mode (0=disabled, 1=enabled, applied at hw_init)");

uint a2xx_wptr_poll_delay = 0;
module_param(a2xx_wptr_poll_delay, uint, 0644);
MODULE_PARM_DESC(a2xx_wptr_poll_delay,
		 "value for REG_AXXX_CP_RB_WPTR_DELAY when WPTR-polling enabled (KGSL: 0)");

/*
 * Track the last user IB1 across submits for forensic dump on MMU
 * fault. Only the IOVA + size are saved; the kvirt resolution is
 * deferred to fault time and uses a gpummu page-table walk
 * (a2xx_gpummu_iova_to_kvirt) which doesn't require GEM locking.
 */
static struct {
	u64 ib1_iova;
	u32 ib1_size;
} a2xx_last_ib;

static void a2xx_dump(struct msm_gpu *gpu);
static bool a2xx_idle(struct msm_gpu *gpu);
static void a2xx_pulse_gfx3d_reset(struct msm_gpu *gpu);

/*
 * Memory bandwidth vote in icc units (kBps), proportional to GPU clock with
 * 8 bytes/cycle on the 64-bit memory bus. Legacy webOS msm_bus voted
 * ab=ib=2008 MB/s for grp3d_max — set both avg and peak so the AFAB
 * aggregator (sum of avg, max of peak) sees the GPU's full demand and
 * scales fabric clock appropriately.
 */
static u32 a2xx_icc_bw_for_freq(unsigned long freq_hz)
{
	return Bps_to_icc(freq_hz) * 8;
}

/*
 * a2xx_emit_sanitizer_preamble - reset GPU-internal SRAM state at
 * cross-context boundaries.
 *
 * The Adreno 2xx hardware was designed for the legacy KGSL "thick
 * state machine" paradigm: shader-constant SRAMs (vec4 ALU, texture-
 * fetch, boolean, loop) and other GPU-internal SRAMs (SQ instruction
 * cache, GPR file, VPC vertex param cache) retain their contents
 * across PM4 cmdstream submissions. KGSL handled this by issuing a
 * PM4_LOAD_CONSTANT_CONTEXT bulk-restore from per-context shadow
 * memory at every context switch.
 *
 * Mainline freedreno + msm DRM does not implement per-context shadow
 * memory and PM4_LOAD_CONSTANT_CONTEXT hangs in this code path
 * (likely IOVA/ringbuffer-execution-context related, see
 * reports/gpu-internal-state-nondeterminism.md). The result was
 * stale shader-constant data leaking across DRM-client transitions,
 * producing 9-of-10 distinct pixel outputs from byte-identical PM4
 * cmdstreams in gl-capture diagnostic runs.
 *
 * Workaround: at every cross-context boundary, emit standard
 * CP_SET_CONSTANT zero-fill packets directly from the kernel
 * ringbuffer (BEFORE the user's IB1) to wipe the four constant-
 * memory banks to a known state. Bracketed by WAIT_FOR_IDLE +
 * CACHE_FLUSH_AND_INV_EVENT so the user's IB sees a settled GPU.
 *
 * This avoids:
 *   - The PM4_LOAD_CONSTANT_CONTEXT hang (no DMA path used)
 *   - The race we observed when the same writes were emitted from
 *     userspace Mesa (kernel writes complete before user IB starts;
 *     no ordering ambiguity with per-batch clear-color writes)
 *
 * Cost: ~1300 dwords of cmdstream once per cross-context boundary;
 * zero overhead for sequential same-context submits.
 */
/*
 * Lazily allocate a 32 KB shadow buffer for the cross-context
 * sanitizer.  Layout (8 KB-aligned regions):
 *
 *   shadow_iova + 0      ALU bank shadow  (2048 dwords / 8192 bytes)
 *   shadow_iova + 0x2000 TEX bank shadow  ( 192 dwords /  768 bytes
 *                                          padded to 8 KB)
 *
 * CP_LOAD_CONSTANT_CONTEXT masks its address operand with 0xFFFFE000,
 * so each region must be independently 8 KB-aligned.  Reserving 32 KB
 * total guarantees we get two consecutive 8 KB-aligned slots even if
 * the IOMMU hands us a non-8KB-aligned base IOVA.
 *
 * Returns 0 on success, sets a2xx_gpu->shadow_bo / shadow_iova /
 * shadow_tex_iova / shadow_vaddr.  On failure returns -errno; the
 * caller falls back to CP_SET_CONSTANT zero-fills (ALU only).
 */
static int a2xx_alloc_shadow(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	struct drm_gem_object *bo;
	uint64_t iova;
	void *vaddr;

	if (a2xx_gpu->shadow_bo)
		return 0;

	vaddr = msm_gem_kernel_new(gpu->dev, SZ_32K,
				   MSM_BO_WC | MSM_BO_GPU_READONLY,
				   gpu->vm, &bo, &iova);
	if (IS_ERR(vaddr))
		return PTR_ERR(vaddr);

	/* Round IOVA up to 8 KB; corresponding offset in the BO maps
	 * 1:1 (linear pinned IOVA range), so the kernel-vaddr is just
	 * shifted by the same amount. */
	uint64_t aligned_iova = ALIGN(iova, SZ_8K);
	uint64_t offset = aligned_iova - iova;

	a2xx_gpu->shadow_bo = bo;
	a2xx_gpu->shadow_iova = aligned_iova;
	a2xx_gpu->shadow_tex_iova = aligned_iova + SZ_8K;
	a2xx_gpu->shadow_vaddr = vaddr + offset;

	dev_info(gpu->dev->dev,
		 "a2xx shadow: raw_iova=%pad alu_iova=%pad tex_iova=%pad ring_iova=%pad\n",
		 &iova, &aligned_iova, &a2xx_gpu->shadow_tex_iova,
		 &gpu->rb[0]->iova);

	/* Zero ALU shadow (slots 1, 2 are pre-populated below). */
	memset(a2xx_gpu->shadow_vaddr, 0, SZ_8K);

	/*
	 * EXP1: Fill the TEX shadow with a "valid 4-channel RGBA"
	 * default descriptor pattern (instead of zero), repeated for
	 * all 32 fetch slots.
	 *
	 * Hypothesis (per Gemini analysis): for VFETCH instructions,
	 * the SQ fetch unit consults dwords 2-5 of the slot to validate
	 * format / channel selection. With dwords 2-5 zeroed, the unit
	 * may interpret the slot as a 2-component (RG) descriptor
	 * defaulting one or two channels (Blue, Alpha) to zero - which
	 * matches our empirical "missing red OR blue, never green"
	 * symptom on 6/7 broken cycle positions.
	 *
	 * Pattern lifted from KGSL's sys2gmem_tex_const[] in
	 * kgsl_drawctxt.c (legacy webOS kernel reference). Encodes:
	 *   - Format=8888_WZYX (32-bit RGBA)
	 *   - DstSel=XYZW (all 4 channels selected)
	 *   - MagFilt/MinFilt=Point, Mip=BaseMap
	 *   - Dim=2D
	 *
	 * Mesa's per-draw CP_SET_CONSTANT to vbuf slot 20+ overwrites
	 * dwords 0-1 (base address + size) for the active slot; dwords
	 * 2-5 stay at this kernel-set valid default.
	 */
	{
		static const u32 valid_tex_const[6] = {
			0x00000002,                               /* d0: pitch (TBD by Mesa) */
			0x00000800,                               /* d1: Format=8888_WZYX, ReqSize=256bit, NearestClamp=OGL */
			0,                                        /* d2: width/height (TBD by Mesa) */
			(0u << 1) | (1u << 4) | (2u << 7)
				| (3u << 10) | (2u << 23),        /* d3: NumFormat=RF, DstSel=XYZW, MagFilt/MinFilt=Point, Mip=BaseMap */
			0,                                        /* d4: VolMag/VolMin=Point, MinMipLvl=0, MaxMipLvl=1 */
			(1u << 9),                                /* d5: BorderColor=ABGRBlack, Dim=2D */
		};
		u32 *tex = (u32 *)(a2xx_gpu->shadow_vaddr + SZ_8K);
		unsigned i;
		for (i = 0; i < 32; i++)
			memcpy(&tex[i * 6], valid_tex_const, sizeof(valid_tex_const));
	}

	/*
	 * Pre-populate the SoC-reserved ALU slots with values the
	 * fixed-function vertex pipeline relies on. Sampled from the
	 * legacy webOS proprietary stack (KGSL + Qualcomm libGLESv2)
	 * via gpu-regdump-webos -- see reports/fb-captures/
	 * webos-soc-reference.txt.
	 *
	 * Only slots 1 and 2 hold non-zero SoC values; all other slots
	 * in 0..31 read as zero on the proprietary stack and are left
	 * zero here. The decoded values are mathematical constants that
	 * appear to be used by the viewport-transform / LOD-bias /
	 * fixed-function math units:
	 *
	 *   ALU[1] = (19984.0f, 1.0f, 0.5f, 0.0f)
	 *   ALU[2] = (2.0f, 0.75f, 0.375f, 0.25f)
	 *
	 * Without these in the shadow, PM4_LOAD_CONSTANT_CONTEXT would
	 * blindly write zero into slots 1/2 and break the vertex
	 * pipeline (rendering goes degenerate / black). With them, the
	 * packet's bulk-restore brings the GPU into the same starting
	 * state as a fresh KGSL context.
	 */
	{
		u32 *alu = (u32 *)a2xx_gpu->shadow_vaddr;
		/* slot 1 */
		alu[1 * 4 + 0] = 0x469c4000;  /* 19984.0f */
		alu[1 * 4 + 1] = 0x3f800000;  /* 1.0f */
		alu[1 * 4 + 2] = 0x3f000000;  /* 0.5f */
		alu[1 * 4 + 3] = 0x00000000;
		/* slot 2 */
		alu[2 * 4 + 0] = 0x40000000;  /* 2.0f */
		alu[2 * 4 + 1] = 0x3f400000;  /* 0.75f */
		alu[2 * 4 + 2] = 0x3ec00000;  /* 0.375f */
		alu[2 * 4 + 3] = 0x3e800000;  /* 0.25f */
	}

	return 0;
}

static void a2xx_emit_sanitizer_preamble(struct msm_gpu *gpu,
					 struct msm_ringbuffer *ring)
{
	/*
	 * IMPORTANT: ALU constant slots 0-31 hold SoC-reserved system
	 * constants the hardware fixed-function pipeline uses (vertex
	 * transform helpers, viewport math, sampling LOD bias).
	 * gl-cap-and-regdump-webos sampled the proprietary-stack values:
	 *   slot 0 = (0,0,0,0)
	 *   slot 1 = (0x469c4000, 1.0, 0.5, 0)
	 *   slot 2 = (2.0, 0.75, 0.375, 0.25)
	 * Zeroing these breaks the vertex pipeline (transforms produce
	 * degenerate/clipped output).
	 *
	 * Mesa places user constants at:
	 *   VS_CONST_BASE = 0x20 (vec4 slot 32, dword offset 0x80)
	 *   PS_CONST_BASE = 0x120 (vec4 slot 288, dword offset 0x480)
	 * These plus everything between them is user-controlled and
	 * safe to wipe.  Cap at slot 511 (offset 0x7FC) - end of the
	 * 256-vec4 PS user range.
	 *
	 * Bool and loop are pure user-state - safe to wipe entirely.
	 */
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	const unsigned USER_ALU_OFFSET = 0x80;   /* slot 32 = VS_CONST_BASE */
	const unsigned USER_ALU_DWORDS = 1920;   /* slots 32..511 = 480 vec4 */
	const unsigned BOOL_CONSTANTS  = 8;
	const unsigned LOOP_CONSTANTS  = 56;
	/*
	 * have_shadow: take the LOAD_CONSTANT_CONTEXT path if the shadow
	 * BO was allocated successfully. The shadow is pre-populated with
	 * SoC-reserved ALU defaults (slots 1, 2) confirmed stable across
	 * 10 webOS runs - see a2xx_alloc_shadow().
	 */
	bool have_shadow = a2xx_gpu->shadow_bo != NULL;
	unsigned i;

	/*
	 * 8x SLOT-SCRUB LOOP - wrap the entire constant-restore + flush
	 * sequence in 8 iterations to scrub all 8 hypothesized internal
	 * SQ wavefront / SRAM slots on Adreno 220.
	 *
	 * Empirical evidence (100-run gl-cap-and-regdump-mainline test
	 * with LSM killed, current-mesa with sysmem-force reverted):
	 *   - Per-submit output is fully deterministic, period 8.
	 *   - 2/8 cycle positions render the gradient correctly.
	 *   - 6/8 cycle positions show a 3x2 grid of GMEM tile bins
	 *     where some tiles render correctly and others have flat
	 *     solid colors (vertex-interpolation broken on those tiles).
	 *
	 * The classic Yamato/Leia "thick state machine" hardware has 8
	 * internal slots/wavefronts, each with its own shadow constant
	 * SRAM. CP_SET_CONSTANT and CP_LOAD_CONSTANT_CONTEXT only write
	 * to the CURRENTLY-ACTIVE slot, so a single per-submit restore
	 * leaves 7 slots poisoned with residue from prior DRM clients.
	 * As GMEM tile-binning replays the cmdstream once per tile, the
	 * tile-to-slot mapping rotates and we see the constants surface
	 * differently in each bin.
	 *
	 * Cycling the full restore sequence 8 times (with a CP_EVENT_WRITE
	 * CACHE_FLUSH_AND_INV + WAIT_FOR_IDLE between iterations to force
	 * the hardware to retire and rotate) ensures every internal slot
	 * gets a clean ALU/Bool/Loop bank before the user's first draw.
	 */
	const unsigned ALU_CONSTANTS = 2048;
	const unsigned TEX_CONSTANTS = 192;   /* 32 fetch slots * 6 dwords */
	unsigned slot;

	/* Drain anything in flight from the previous client. */
	OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
	OUT_RING(ring, 0);

	/*
	 * Option I (Gemini hypothesis A): pin CP_SCRATCH_REG0..7 = 0.
	 *
	 * Emit as PM4 TYPE0 register writes so the CP processes them in
	 * the cmdstream (not via MMIO from CPU side, which would race the
	 * CP's own scratch usage). 8 consecutive registers at 0x578-0x57F
	 * can be written with one OUT_PKT0 burst.
	 */
	if (a2xx_scratch_reset_enable) {
		OUT_PKT0(ring, REG_AXXX_CP_SCRATCH_REG0, 8);
		for (i = 0; i < 8; i++)
			OUT_RING(ring, 0);
		OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
		OUT_RING(ring, 0);
	}

	for (slot = 0; slot < a2xx_scrub_iterations; slot++) {
		/*
		 * EXPERIMENTAL "dummy advance": CP_INVALIDATE_STATE with
		 * mask 0x7fff (invalidate ALL hw state classes) at the top
		 * of each scrub iteration. Per Gemini-AI's analysis of the
		 * Adreno 220 SQ wavefront slot scheduler, packets that
		 * "consume a slot" advance the scheduler's allocation
		 * pointer; CP_INVALIDATE_STATE is one of the candidates.
		 *
		 * Mask 0x7fff = vertex shader (0x100) + pixel shader (0x200)
		 * + all the other internal state-class bits the hardware
		 * tracks. Mesa freedreno's old patch 0036 used this exact
		 * mask before a shader upload.
		 *
		 * If this rotates the slot pointer, the subsequent
		 * CP_LOAD_CONSTANT_CONTEXT writes will land on different
		 * slots across the 8 iterations, scrubbing all of them
		 * (rather than re-writing the same slot 8 times).
		 *
		 * Followed by WFI to ensure the invalidate is fully retired
		 * before the next packet. CP_INVALIDATE_STATE alone may not
		 * stall.
		 */
		OUT_PKT3(ring, CP_INVALIDATE_STATE, 1);
		OUT_RING(ring, 0x00007fff);
		OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
		OUT_RING(ring, 0);

		if (have_shadow) {
			/*
			 * Bulk-load the entire ALU constant bank (512 vec4 =
			 * 2048 dwords) from the kernel-pinned shadow buffer.
			 * The shadow is pre-populated with the SoC-reserved
			 * ALU defaults captured from webOS (slots 1, 2) plus
			 * zeros for the user range.
			 */
			OUT_PKT3(ring, CP_LOAD_CONSTANT_CONTEXT, 3);
			OUT_RING(ring, lower_32_bits(a2xx_gpu->shadow_iova));
			OUT_RING(ring, (0 << 24) | (0 << 16) | 0);
			OUT_RING(ring, ALU_CONSTANTS);

			/*
			 * Bulk-load the TEX (texture/vertex fetch) bank from
			 * the zero-filled shadow region 8 KB above the ALU
			 * region. KGSL emits the same packet at every context
			 * restore (kgsl_drawctxt.c "Texture Constants" path):
			 * type=1 (TEX), offset=0, count=192 dwords.
			 *
			 * Without this, residue from prior DRM clients in TEX
			 * SRAM bleeds into vertex-attribute fetches and shows
			 * up as a single colour channel reading back as zero
			 * on 5/8 internal slot positions (observed empirically
			 * in the 100-cap test before this addition).
			 */
			OUT_PKT3(ring, CP_LOAD_CONSTANT_CONTEXT, 3);
			OUT_RING(ring, lower_32_bits(a2xx_gpu->shadow_tex_iova));
			OUT_RING(ring, (0 << 24) | (1 << 16) | 0);
			OUT_RING(ring, TEX_CONSTANTS);
		} else {
			/* Inline CP_SET_CONSTANT zero-fill fallback. */
			OUT_PKT3(ring, CP_SET_CONSTANT, 1 + USER_ALU_DWORDS);
			OUT_RING(ring, (0 << 16) | USER_ALU_OFFSET);
			for (i = 0; i < USER_ALU_DWORDS; i++)
				OUT_RING(ring, 0);
		}

		/* Bool bank (8 dwords). */
		OUT_PKT3(ring, CP_SET_CONSTANT, 1 + BOOL_CONSTANTS);
		OUT_RING(ring, (2 << 16) | 0);
		for (i = 0; i < BOOL_CONSTANTS; i++)
			OUT_RING(ring, 0);

		/* Loop bank (56 dwords). */
		OUT_PKT3(ring, CP_SET_CONSTANT, 1 + LOOP_CONSTANTS);
		OUT_RING(ring, (3 << 16) | 0);
		for (i = 0; i < LOOP_CONSTANTS; i++)
			OUT_RING(ring, 0);

		/*
		 * Flush + invalidate + WFI between iterations forces the
		 * hardware to retire the current slot's writes and rotate
		 * to the next slot for the next CP_LOAD_CONSTANT_CONTEXT.
		 */
		OUT_PKT3(ring, CP_EVENT_WRITE, 1);
		OUT_RING(ring, CACHE_FLUSH_AND_INV_EVENT);
		OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
		OUT_RING(ring, 0);
	}

	/*
	 * Option G (real): 8 dummy POINT draws to advance the SQ wavefront
	 * slot pointer. Each CP_DRAW_INDX definitively consumes one slot;
	 * 8 of them = full cycle = all slots touched = subsequent user
	 * draws land on slot 0 deterministically = cycle collapse.
	 *
	 * Default OFF (a2xx_dummy_draw_enable). Risk: GPU hang if state
	 * setup is wrong (Mesa patch 0070 had this fail with VS_REGS=63).
	 * We use KGSL's Leia SQ_PROGRAM_CNTL=0x10018001 which has worked
	 * for the gmem2sys quad render path. Safety guards:
	 *   - Scissor = (0,0)-(1,1): rasterizer rejects almost all pixels
	 *   - RB_COLOR_MASK = 0: no RB color writes even if pixel passes
	 *   - RB_DEPTHCONTROL = 0/8: no depth test
	 *   - POINTLIST count=1: minimum-cost primitive
	 *   - VS+FS uploaded inline via CP_IM_LOAD_IMMEDIATE (no BO needed)
	 *
	 * The user IB will re-emit all this state, so we don't restore -
	 * we just need to leave the GPU not-hung.
	 */
	if (a2xx_dummy_draw_enable) {
		const u32 vs_dwords = ARRAY_SIZE(a2xx_scrub_vs_pgm);
		const u32 fs_dwords = ARRAY_SIZE(a2xx_scrub_fs_pgm);
		unsigned d, idx;

		/* Drain any pending state from the constant scrub above. */
		OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
		OUT_RING(ring, 0);

		/* Invalidate all state classes before reconfiguring. */
		OUT_PKT3(ring, CP_INVALIDATE_STATE, 1);
		OUT_RING(ring, 0x00007fff);

		/* Upload scrub VS via CP_IM_LOAD_IMMEDIATE (target=0=VS). */
		OUT_PKT3(ring, CP_IM_LOAD_IMMEDIATE, 2 + vs_dwords);
		OUT_RING(ring, 0); /* 0 = vertex shader */
		OUT_RING(ring, vs_dwords);
		for (idx = 0; idx < vs_dwords; idx++)
			OUT_RING(ring, a2xx_scrub_vs_pgm[idx]);

		/* Upload scrub FS (target=1=PS). */
		OUT_PKT3(ring, CP_IM_LOAD_IMMEDIATE, 2 + fs_dwords);
		OUT_RING(ring, 1); /* 1 = pixel shader */
		OUT_RING(ring, fs_dwords);
		for (idx = 0; idx < fs_dwords; idx++)
			OUT_RING(ring, a2xx_scrub_fs_pgm[idx]);

		/* SET_SHADER_BASES: VS base=0, PS base=0x180, valid bit set. */
		OUT_PKT3(ring, CP_SET_SHADER_BASES, 1);
		OUT_RING(ring, 0x80000180);

		/* SQ_PROGRAM_CNTL: lift KGSL Leia value (gmem2sys path). */
		OUT_PKT3(ring, CP_SET_CONSTANT, 3);
		OUT_RING(ring, CP_REG(REG_A2XX_SQ_PROGRAM_CNTL));
		OUT_RING(ring, 0x10018001); /* SQ_PROGRAM_CNTL */
		OUT_RING(ring, 0x00000008); /* SQ_CONTEXT_MISC */

		OUT_PKT3(ring, CP_SET_CONSTANT, 2);
		OUT_RING(ring, CP_REG(REG_A2XX_PA_CL_VTE_CNTL));
		OUT_RING(ring, 0x00000b00); /* premultiplied X/Y/Z by W */

		OUT_PKT3(ring, CP_SET_CONSTANT, 2);
		OUT_RING(ring, CP_REG(REG_A2XX_PA_SU_SC_MODE_CNTL));
		OUT_RING(ring, 0x00080240); /* no cull, point provoking last */

		/* Scissor = (0,0)-(1,1): rasterizer rejects ~all pixels. */
		OUT_PKT3(ring, CP_SET_CONSTANT, 3);
		OUT_RING(ring, CP_REG(REG_A2XX_PA_SC_SCREEN_SCISSOR_TL));
		OUT_RING(ring, 0);                       /* TL = (0,0) */
		OUT_RING(ring, (1 << 16) | 1);           /* BR = (1,1) */

		OUT_PKT3(ring, CP_SET_CONSTANT, 3);
		OUT_RING(ring, CP_REG(REG_A2XX_PA_SC_WINDOW_SCISSOR_TL));
		OUT_RING(ring, (1U << 31) | 0);          /* TL = (0,0), disable */
		OUT_RING(ring, (1 << 16) | 1);           /* BR = (1,1) */

		/* Disable color writes entirely. */
		OUT_PKT3(ring, CP_SET_CONSTANT, 2);
		OUT_RING(ring, CP_REG(REG_A2XX_RB_COLOR_MASK));
		OUT_RING(ring, 0x00000000);

		/* Disable depth/stencil writes. */
		OUT_PKT3(ring, CP_SET_CONSTANT, 2);
		OUT_RING(ring, CP_REG(REG_A2XX_RB_DEPTHCONTROL));
		OUT_RING(ring, 0x00000008); /* Leia: BACKFACE_ENABLE only */

		OUT_PKT3(ring, CP_SET_CONSTANT, 2);
		OUT_RING(ring, CP_REG(REG_A2XX_RB_MODECONTROL));
		OUT_RING(ring, 0x00000000); /* no resolve, sysmem mode */

		/* Clip control: enable clipping, disable user clip planes. */
		OUT_PKT3(ring, CP_SET_CONSTANT, 2);
		OUT_RING(ring, CP_REG(REG_A2XX_PA_CL_CLIP_CNTL));
		OUT_RING(ring, 0x00010000);

		/*
		 * 8 dummy POINT draws. DRAW(POINTLIST=9, AUTO_INDEX=2,
		 * IGN=0/0, IGNORE_VIS=0, instances=0) | bit 14 set:
		 *   9 | (2 << 6) | (1 << 14) = 0x00004089
		 */
		for (d = 0; d < 8; d++) {
			OUT_PKT3(ring, CP_DRAW_INDX, 3);
			OUT_RING(ring, 0x00000000); /* viz query info */
			OUT_RING(ring, 0x00004089); /* draw initiator */
			OUT_RING(ring, 1);          /* NumIndices = 1 */

			/* Force retirement between draws so each consumes
			 * a distinct slot. */
			OUT_PKT3(ring, CP_EVENT_WRITE, 1);
			OUT_RING(ring, CACHE_FLUSH_AND_INV_EVENT);
			OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
			OUT_RING(ring, 0);
		}
	}
}

static void a2xx_submit(struct msm_gpu *gpu, struct msm_gem_submit *submit)
{
	struct msm_ringbuffer *ring = submit->ring;
	unsigned int i;
	int wptr_delay;

	/* Debug: log submit details */
	a2xx_debug_log_submit(gpu, submit);

	/*
	 * Cross-context-boundary state-leak workaround: if this submit is
	 * from a different DRM client than the previous one on this ring,
	 * inject a sanitizer preamble that bulk-restores Mesa's user
	 * shader-constant range from a kernel-pinned shadow BO via
	 * PM4_LOAD_CONSTANT_CONTEXT (ALU bank) and CP_SET_CONSTANT (bool
	 * + loop).  This matches the KGSL context-restore path on the
	 * legacy 2.6 kernel.  See a2xx_emit_sanitizer_preamble().
	 */
	if (ring->cur_ctx_seqno != submit->queue->ctx->seqno &&
	    !a2xx_skip_preamble) {
		(void)a2xx_alloc_shadow(gpu);  /* lazy-init, fall back to
						* inline writes if it fails */
		a2xx_emit_sanitizer_preamble(gpu, ring);
	}

	for (i = 0; i < submit->nr_cmds; i++) {
		switch (submit->cmd[i].type) {
		case MSM_SUBMIT_CMD_IB_TARGET_BUF:
			/* ignore IB-targets */
			break;
		case MSM_SUBMIT_CMD_CTX_RESTORE_BUF:
			/* ignore if there has not been a ctx switch: */
			if (ring->cur_ctx_seqno == submit->queue->ctx->seqno)
				break;
			fallthrough;
		case MSM_SUBMIT_CMD_BUF:
			OUT_PKT3(ring, CP_INDIRECT_BUFFER_PFD, 2);
			OUT_RING(ring, lower_32_bits(submit->cmd[i].iova));
			OUT_RING(ring, submit->cmd[i].size);
			OUT_PKT2(ring);
			break;
		}
	}

	/*
	 * Track the FIRST user IB1 of this submit for forensic dump on
	 * MMU fault. Just save the IOVA + size; the kvirt resolution
	 * happens at fault time via a page-table walk
	 * (a2xx_gpummu_iova_to_kvirt) which doesn't require GEM locking.
	 *
	 * Earlier attempts to capture kvaddr at submit time via
	 * msm_gem_get_vaddr failed (-EBUSY for DONTNEED BOs) and the
	 * msm_gem_get_vaddr_active fallback deadlocked because the
	 * submit path already holds the BO's reservation lock through
	 * drm_exec.
	 */
	for (i = 0; i < submit->nr_cmds; i++) {
		if (submit->cmd[i].type != MSM_SUBMIT_CMD_BUF)
			continue;

		a2xx_last_ib.ib1_iova = submit->cmd[i].iova;
		a2xx_last_ib.ib1_size = submit->cmd[i].size;
		break;
	}

	/*
	 * EXPERIMENTAL: force the low nibble of the seqno written to
	 * CP_SCRATCH_REG2 to a value in the empirically-determined
	 * "stable rendering" set.
	 *
	 * 50-run gl-capture analysis on Adreno 220 / HP TouchPad showed
	 * pixel output is fully deterministic given submit->seqno & 0xF
	 * (perfect 16-cycle pattern). 9 of 16 lo-nibbles produce the
	 * "stable" rendering hash (lo = 0, 3, 4, 5, b, c, d, e, f); the
	 * other 7 produce different per-position broken renderings:
	 *
	 *   lo=1: 78d9...  lo=2: 9f34...
	 *   lo=6: 4d4c...  lo=7: 24c2...  lo=8: 0b59...
	 *   lo=9: 6b08...  lo=a: 7b74...
	 *
	 * The seqno value is written to CP_SCRATCH_REG2 (debug-only HW
	 * register, mainline doesn't depend on it for fence tracking -
	 * fence completion uses the CACHE_FLUSH_TS event below which
	 * stores into rbmemptr(ring, fence) memory). So masking the
	 * lo-nibble of what we write to SCRATCH_REG2 is functionally
	 * a no-op - except that the GPU's internal state machinery
	 * apparently uses some bits of this register, producing the
	 * 16-cycle variance we observe.
	 *
	 * Mask the seqno to (seqno & ~0xF) so SCRATCH_REG2 always lands
	 * in the lo=0 "stable" slot. The CACHE_FLUSH_TS path below
	 * keeps the unmasked seqno so fence completion still works.
	 *
	 * If this collapses the 50-run variance to a single hash, we've
	 * confirmed SCRATCH_REG2's low bits drive a HW state machine
	 * that affects rendering.
	 */
	/*
	 * Aggressive test: write 0 unconditionally. The earlier
	 * (seqno & ~0xFu) mask collapsed the 16-cycle to lo-nibble=0
	 * but a residual 8-cycle persists in the 100-cap test (8
	 * unique hashes per period). Write 0 always - if cycle
	 * collapses to 100/100, SCRATCH_REG2 is fully the source.
	 * If 8 unique hashes remain, the residual cycle is from
	 * something else entirely.
	 */
	OUT_PKT0(ring, REG_AXXX_CP_SCRATCH_REG2, 1);
	OUT_RING(ring, 0);

	/* wait for idle before cache flush/interrupt */
	OUT_PKT3(ring, CP_WAIT_FOR_IDLE, 1);
	OUT_RING(ring, 0x00000000);

	OUT_PKT3(ring, CP_EVENT_WRITE, 3);
	OUT_RING(ring, CACHE_FLUSH_TS);
	OUT_RING(ring, rbmemptr(ring, fence));
	OUT_RING(ring, submit->seqno);   /* unmasked - fence tracking */
	OUT_PKT3(ring, CP_INTERRUPT, 1);
	OUT_RING(ring, 0x80000000);

	/* Debug: force cache flush before notifying GPU */
	a2xx_debug_cache_flush();

	/*
	 * Pre-WPTR sync: targeted poll on RBBM_STATUS busy-bits to replace
	 * the empirical udelay(10000) hack.
	 *
	 * Empirical finding: A22X needs a "settle" period before the WPTR
	 * write or a deterministic 8-cycle of broken renderings emerges.
	 * The brute-force fix was udelay(10000) (10ms CPU busy-wait) which
	 * is unshippable. Try a hardware-driven poll first: spin on
	 * RBBM_STATUS until all busy-bits are clear (GPU is fully retired
	 * from the previous batch). Only fall back to udelay if the poll
	 * times out without idle.
	 *
	 * The previous batch's CACHE_FLUSH_TS + CP_INTERRUPT have already
	 * been issued at this point, so the GPU should retire quickly. The
	 * poll lets us wait only as long as needed.
	 *
	 * If this fails to fix the cycle, the race isn't pipeline-busy but
	 * something else (power/clock domain stabilization), and we'd need
	 * a different mechanism (e.g., poll a PLL-lock register or wait
	 * after pm_resume).
	 */
	if (a2xx_rbbm_poll_enable && a2xx_rbbm_poll_mask) {
		ktime_t start = ktime_get();
		u32 status;
		unsigned int spins = 0;

		while (1) {
			status = gpu_read(gpu, REG_A2XX_RBBM_STATUS);
			if (!(status & a2xx_rbbm_poll_mask))
				break;
			spins++;
			/* timeout at ~50ms to avoid hangs */
			if (ktime_us_delta(ktime_get(), start) > 50000) {
				/* fall back to brute-force mdelay (udelay > 2000 is rejected) */
				mdelay(10);
				break;
			}
			cpu_relax();
		}

		if (spins > 0)
			pr_debug_ratelimited(
				"a2xx submit: spun %u times waiting for RBBM idle (status=%08x mask=%08x)\n",
				spins, status, a2xx_rbbm_poll_mask);
	}

	/* Debug: optional EXTRA delay before WPTR write (knob for tests) */
	wptr_delay = a2xx_debug_get_wptr_delay();
	if (wptr_delay > 0)
		udelay(wptr_delay);

	/*
	 * Legacy KGSL WPTR-polling mirror: when enabled, the CP polls a
	 * coherent memory location for the WPTR value. Update it and barrier
	 * before the register write so either path reaches the CP coherently.
	 */
	if (a2xx_wptr_poll_enable) {
		ring->memptrs->wptr = get_wptr(ring);
		/* ensure CP sees the wptr mirror update before the register kick */
		wmb();
#ifdef CONFIG_OUTER_CACHE
		outer_sync();
#endif
	}

	/*
	 * Option D fix for the period-8 cycle (see report 23). Pulse
	 * GFX3D_RESET right before WPTR to clear SQ/VPC logic state
	 * (the seat of the 8-cycle wavefront-scheduler residue) WITHOUT
	 * touching the GDSC rail (which would wipe GMEM SRAM and break
	 * tile-based rendering, as we observed with Option C).
	 */
	a2xx_pulse_gfx3d_reset(gpu);

	adreno_flush(gpu, ring, REG_AXXX_CP_RB_WPTR);
}

static bool a2xx_me_init(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	struct msm_ringbuffer *ring = gpu->rb[0];

	OUT_PKT3(ring, CP_ME_INIT, 18);

	/* All fields present (bits 9:0) */
	OUT_RING(ring, 0x000003ff);
	/* Disable/Enable Real-Time Stream processing (present but ignored) */
	OUT_RING(ring, 0x00000000);
	/* Enable (2D <-> 3D) implicit synchronization (present but ignored) */
	OUT_RING(ring, 0x00000000);

	OUT_RING(ring, REG_A2XX_RB_SURFACE_INFO - 0x2000);
	OUT_RING(ring, REG_A2XX_PA_SC_WINDOW_OFFSET - 0x2000);
	OUT_RING(ring, REG_A2XX_VGT_MAX_VTX_INDX - 0x2000);
	OUT_RING(ring, REG_A2XX_SQ_PROGRAM_CNTL - 0x2000);
	OUT_RING(ring, REG_A2XX_RB_DEPTHCONTROL - 0x2000);
	OUT_RING(ring, REG_A2XX_PA_SU_POINT_SIZE - 0x2000);
	OUT_RING(ring, REG_A2XX_PA_SC_LINE_CNTL - 0x2000);
	OUT_RING(ring, REG_A2XX_PA_SU_POLY_OFFSET_FRONT_SCALE - 0x2000);

	/* Vertex and Pixel Shader Start Addresses in instructions
	 * (3 DWORDS per instruction) */
	OUT_RING(ring, 0x80000180);
	/* Maximum Contexts */
	OUT_RING(ring, 0x00000001);
	/* Write Confirm Interval and The CP will wait the
	 * wait_interval * 16 clocks between polling  */
	OUT_RING(ring, 0x00000000);
	/* NQ and External Memory Swap */
	OUT_RING(ring, 0x00000000);
	/* protected mode error checking (0x1f2 is REG_AXXX_CP_INT_CNTL) */
	if (a2xx_gpu->protection_disabled)
		OUT_RING(ring, 0x00000000);
	else
		OUT_RING(ring, 0x200001f2);
	/* Disable header dumping and Header dump address */
	OUT_RING(ring, 0x00000000);
	/* Header dump size */
	OUT_RING(ring, 0x00000000);

	if (!a2xx_gpu->protection_disabled) {
		/* enable protected mode */
		OUT_PKT3(ring, CP_SET_PROTECTED_MODE, 1);
		OUT_RING(ring, 1);
	}

	/*
	 * If WPTR-polling mode is enabled, the CP reads the wptr value from
	 * memptrs->wptr (programmed via REG_AXXX_CP_RB_WPTR_BASE in hw_init).
	 * me_init runs before any user submit, so we must update the mirror
	 * here too or the CP will poll a stale 0 value and never advance.
	 */
	if (a2xx_wptr_poll_enable) {
		ring->memptrs->wptr = get_wptr(ring);
		wmb();
#ifdef CONFIG_OUTER_CACHE
		outer_sync();
#endif
	}

	adreno_flush(gpu, ring, REG_AXXX_CP_RB_WPTR);
	return a2xx_idle(gpu);
}

/*
 * Option H one-shot boot-time GFX3D core reset.
 *
 * Replicates the webOS msm_clk_soc_init() reset sequence that mainline
 * never executes. At first a2xx_hw_init the GFX3D rail is on and the
 * core clock is running (pm_runtime resume fired), so we satisfy the
 * webOS pre-condition "clock enabled during reset".
 *
 * Runs exactly ONCE per kernel uptime, gated by a2xx_boot_reset_done.
 * The static flag survives pm_runtime cycles but resets on module
 * reload / reboot, mirroring webOS's "once at SoC bringup" semantics.
 *
 * Pulse is via MMCC SW_RESET_CORE_REG BIT(12) - the OUTER GFX3D core
 * reset that resets the entire power-domain logic block, including
 * the SQ wavefront SRAM that the INNER RBBM_SOFT_RESET (which we
 * already do at line ~735) cannot reach.
 */
static bool a2xx_boot_reset_done = false;

static void a2xx_one_shot_boot_reset(struct msm_gpu *gpu)
{
	void __iomem *resetr;
	u32 v;

	if (!a2xx_boot_reset_enable)
		return;
	if (a2xx_boot_reset_done)
		return;

	resetr = ioremap(A2XX_MMCC_GFX3D_RESET, 4);
	if (!resetr) {
		dev_warn(gpu->dev->dev,
			 "a2xx_one_shot_boot_reset: ioremap MMCC reset failed\n");
		return;
	}

	v = readl(resetr);
	writel(v | A2XX_GFX3D_RESET_BIT, resetr);
	(void)readl(resetr); /* posting read */
	udelay(5);           /* matches webOS clock-8x60.c:2563 */
	writel(v & ~A2XX_GFX3D_RESET_BIT, resetr);
	(void)readl(resetr);
	udelay(5);           /* settle */
	iounmap(resetr);

	a2xx_boot_reset_done = true;
	dev_info(gpu->dev->dev,
		 "a2xx: one-shot GFX3D boot reset pulsed (Option H)\n");
}

static int a2xx_hw_init(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	dma_addr_t pt_base, tran_error;
	uint32_t *ptr, len;
	int i, ret;

	a2xx_gpummu_params(to_msm_vm(gpu->vm)->mmu, &pt_base, &tran_error);

	DBG("%s", gpu->name);

	/*
	 * Option H: one-shot boot-time MMCC GFX3D core reset. Done BEFORE
	 * any other hw_init work because it resets the entire GFX3D power-
	 * domain logic block including state RBBM_SOFT_RESET cannot reach.
	 */
	a2xx_one_shot_boot_reset(gpu);

	/* halt ME to avoid ucode upload issues on a20x */
	gpu_write(gpu, REG_AXXX_CP_ME_CNTL, AXXX_CP_ME_CNTL_HALT);

	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE1, 0xfffffffe);
	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, 0xffffffff);

	/* note: kgsl uses 0x00000001 after first reset on a22x */
	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0xffffffff);
	msleep(30);
	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0x00000000);

	if (adreno_is_a225(adreno_gpu))
		gpu_write(gpu, REG_A2XX_SQ_FLOW_CONTROL, 0x18000000);

	/* note: kgsl uses 0x0000ffff for a20x */
	gpu_write(gpu, REG_A2XX_RBBM_CNTL, 0x00004442);

	/* MPU: physical range */
	gpu_write(gpu, REG_A2XX_MH_MMU_MPU_BASE, 0x00000000);
	gpu_write(gpu, REG_A2XX_MH_MMU_MPU_END, 0xfffff000);

	/*
	 * Match legacy webOS KGSL: configure ALL MH MMU client ports to
	 * BEH_TRAN_FLT (translate, fault on miss) instead of BEH_TRAN_RNG
	 * (translate, silently bypass on miss).
	 *
	 * Legacy msm8660_defconfig had CONFIG_MSM_KGSL_MMU_PAGE_FAULT=y, which
	 * sets MMU_CONFIG=2 = BEH_TRAN_FLT in kgsl_yamato.c YAMATO_MMU_CONFIG.
	 *
	 * BEH_TRAN_RNG is dangerous: an out-of-range / unmapped GPU access is
	 * silently passed through to raw physical address space, so the GPU
	 * reads garbage memory instead of faulting. On Adreno 220 this maps
	 * onto the intermittent faceted-rendering glmark2 symptom — the GPU
	 * pulls garbage in place of real vertex/normal/uniform data and we
	 * see no kernel-side warning.
	 *
	 * BEH_TRAN_FLT will turn those silent garbage reads into visible
	 * MH page faults via the MH interrupt path, which both eliminates
	 * the wrong-data outcome and gives us real diagnostics.
	 */
	gpu_write(gpu, REG_A2XX_MH_MMU_CONFIG, A2XX_MH_MMU_CONFIG_MMU_ENABLE |
		A2XX_MH_MMU_CONFIG_RB_W_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_W_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R0_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R1_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R2_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R3_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_CP_R4_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_VGT_R0_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_VGT_R1_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_TC_R_CLNT_BEHAVIOR(BEH_TRAN_FLT) |
		A2XX_MH_MMU_CONFIG_PA_W_CLNT_BEHAVIOR(BEH_TRAN_FLT));

	/*
	 * VA range. Match webOS/KGSL live readback (0x66000fff) instead
	 * of mainline's historical SZ_16M base, paired with the matching
	 * GPUMMU_VA_START change in a2xx_gpummu.c. Hypothesis: the upper
	 * VA bits index the L2 / MH cache, and mainline's low-RAM base
	 * may hit "dirty" cache lines webOS never touches.
	 */
	gpu_write(gpu, REG_A2XX_MH_MMU_VA_RANGE, 0x66000000UL |
		A2XX_MH_MMU_VA_RANGE_NUM_64KB_REGIONS(0xfff));

	gpu_write(gpu, REG_A2XX_MH_MMU_PT_BASE, pt_base);
	gpu_write(gpu, REG_A2XX_MH_MMU_TRAN_ERROR, tran_error);

	gpu_write(gpu, REG_A2XX_MH_MMU_INVALIDATE,
		A2XX_MH_MMU_INVALIDATE_INVALIDATE_ALL |
		A2XX_MH_MMU_INVALIDATE_INVALIDATE_TC);

	/*
	 * MH ARBITER config - matches legacy KGSL's KGSL_CFG_YAMATO_MHARB
	 * for both Yamato (a20x) and Leia (a22x = REV470). Live readback
	 * from webOS/KGSL on a Leia REV470 (HP TouchPad) confirms
	 * MH_ARBITER_CONFIG = 0x07c86590 for both generations.
	 *
	 * IN_FLIGHT_LIMIT_ENABLE (bit 15) is intentionally NOT set:
	 * mainline used to set it (with IN_FLIGHT_LIMIT=8), but the MH
	 * arbiter's per-tag tracking with the limit enforced was producing
	 * a deterministic period-8 rendering cycle on a22x where 1/8 of
	 * fresh DRM contexts rendered correctly and 7/8 had channel-drop
	 * + GMEM-tile artifacts. KGSL leaves the limit unenforced (the
	 * IN_FLIGHT_LIMIT(8) field is still written but the enable bit
	 * is off, so the field is dead). Mirror KGSL exactly.
	 */
	gpu_write(gpu, REG_A2XX_MH_ARBITER_CONFIG,
		A2XX_MH_ARBITER_CONFIG_SAME_PAGE_LIMIT(16) |
		A2XX_MH_ARBITER_CONFIG_L1_ARB_ENABLE |
		A2XX_MH_ARBITER_CONFIG_L1_ARB_HOLD_ENABLE |
		A2XX_MH_ARBITER_CONFIG_PAGE_SIZE(1) |
		A2XX_MH_ARBITER_CONFIG_TC_REORDER_ENABLE |
		A2XX_MH_ARBITER_CONFIG_TC_ARB_HOLD_ENABLE |
		A2XX_MH_ARBITER_CONFIG_IN_FLIGHT_LIMIT(8) |
		A2XX_MH_ARBITER_CONFIG_CP_CLNT_ENABLE |
		A2XX_MH_ARBITER_CONFIG_VGT_CLNT_ENABLE |
		A2XX_MH_ARBITER_CONFIG_TC_CLNT_ENABLE |
		A2XX_MH_ARBITER_CONFIG_RB_CLNT_ENABLE |
		A2XX_MH_ARBITER_CONFIG_PA_CLNT_ENABLE);
	if (!adreno_is_a20x(adreno_gpu))
		gpu_write(gpu, REG_A2XX_MH_CLNT_INTF_CTRL_CONFIG1, 0x00032f07);

	gpu_write(gpu, REG_A2XX_SQ_VS_PROGRAM, 0x00000000);
	gpu_write(gpu, REG_A2XX_SQ_PS_PROGRAM, 0x00000000);

	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE1, 0); /* 0x200 for msm8960? */
	/* A22x (Leia) requires 0x1a0 for proper clock gating per Palm kernel */
	if (!adreno_is_a20x(adreno_gpu))
		gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, 0x1a0);
	else
		gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, 0);

	/* A22X: Initialize GRAS and LRZ/VSC control registers to 0.
	 * KGSL initializes all registers via 18KB shadow memory, but freedreno
	 * doesn't have shadowing. Without explicit initialization, these
	 * registers can have random values causing intermittent rendering
	 * issues (e.g., faceted vs smooth surfaces in glmark2).
	 */
	if (!adreno_is_a20x(adreno_gpu)) {
		gpu_write(gpu, REG_A2XX_A220_RB_LRZ_VSC_CONTROL, 0);
		gpu_write(gpu, REG_A2XX_A220_GRAS_CONTROL, 0);
	}

	/* Initialize SQ_INTERPOLATOR_CNTL to 0xffffffff (all smooth interpolation).
	 * Debug logging revealed that the first submit happens before Mesa sets
	 * this register, leaving it at 0x00000000 (all flat shading). This causes
	 * intermittent faceted rendering when the GPU state from the first draw
	 * affects subsequent draws.
	 */
	gpu_write(gpu, REG_A2XX_SQ_INTERPOLATOR_CNTL, 0xffffffff);

	/* Initialize SQ_GPR_MANAGEMENT to allocate 64 GPRs each for VS/PS.
	 * KGSL initializes this to 0x00040400. Without proper initialization,
	 * random values from GPU power-on could starve one shader type of GPRs.
	 */
	gpu_write(gpu, REG_A2XX_SQ_GPR_MANAGEMENT, 0x00040400);

	/* note: gsl doesn't set this */
	gpu_write(gpu, REG_A2XX_RBBM_DEBUG, 0x00080000);

	gpu_write(gpu, REG_A2XX_RBBM_INT_CNTL,
		A2XX_RBBM_INT_CNTL_RDERR_INT_MASK);
	gpu_write(gpu, REG_AXXX_CP_INT_CNTL,
		AXXX_CP_INT_CNTL_T0_PACKET_IN_IB_MASK |
		AXXX_CP_INT_CNTL_OPCODE_ERROR_MASK |
		AXXX_CP_INT_CNTL_PROTECTED_MODE_ERROR_MASK |
		AXXX_CP_INT_CNTL_RESERVED_BIT_ERROR_MASK |
		AXXX_CP_INT_CNTL_IB_ERROR_MASK |
		AXXX_CP_INT_CNTL_IB1_INT_MASK |
		AXXX_CP_INT_CNTL_RB_INT_MASK);
	gpu_write(gpu, REG_A2XX_SQ_INT_CNTL, 0);
	gpu_write(gpu, REG_A2XX_MH_INTERRUPT_MASK,
		A2XX_MH_INTERRUPT_MASK_AXI_READ_ERROR |
		A2XX_MH_INTERRUPT_MASK_AXI_WRITE_ERROR |
		A2XX_MH_INTERRUPT_MASK_MMU_PAGE_FAULT);

	for (i = 3; i <= 5; i++)
		if ((SZ_16K << i) == adreno_gpu->info->gmem)
			break;
	gpu_write(gpu, REG_A2XX_RB_EDRAM_INFO, i);

	/* Set up performance counter 1 to count busy cycles for devfreq
	 * RBBM1_RB_BUSY counts when render backend is active (graphics work)
	 */
	gpu_write(gpu, REG_A2XX_RBBM_PERFCOUNTER1_SELECT, RBBM1_RB_BUSY);

	ret = adreno_hw_init(gpu);
	if (ret)
		return ret;

	{
		u32 rb_cntl = MSM_GPU_RB_CNTL_DEFAULT | AXXX_CP_RB_CNTL_NO_UPDATE;

		if (a2xx_wptr_poll_enable) {
			/* Match legacy KGSL setup: program WPTR mirror BEFORE
			 * enabling POLL_EN so the CP doesn't read a stale
			 * address as the polling target. */
			gpu_write(gpu, REG_AXXX_CP_RB_WPTR_BASE,
				lower_32_bits(rbmemptr(gpu->rb[0], wptr)));
			gpu_write(gpu, REG_AXXX_CP_RB_WPTR_DELAY,
				a2xx_wptr_poll_delay);
			rb_cntl |= AXXX_CP_RB_CNTL_POLL_EN;
		}

		gpu_write(gpu, REG_AXXX_CP_RB_CNTL, rb_cntl);
	}

	gpu_write(gpu, REG_AXXX_CP_RB_BASE, lower_32_bits(gpu->rb[0]->iova));

	/* NOTE: PM4/micro-engine firmware registers look to be the same
	 * for a2xx and a3xx.. we could possibly push that part down to
	 * adreno_gpu base class.  Or push both PM4 and PFP but
	 * parameterize the pfp ucode addr/data registers..
	 */

	/* Load PM4: */
	ptr = (uint32_t *)(adreno_gpu->fw[ADRENO_FW_PM4]->data);
	len = adreno_gpu->fw[ADRENO_FW_PM4]->size / 4;
	DBG("loading PM4 ucode version: %x", ptr[1]);

	/*
	 * New firmware files seem to have GPU and firmware version in this
	 * word (0x20xxxx for A200, 0x220xxx for A220, 0x225xxx for A225).
	 * Older firmware files, which lack protection support, have 0 instead.
	 */
	if (ptr[1] == 0) {
		dev_warn(gpu->dev->dev,
			 "Legacy firmware detected, disabling protection support\n");
		a2xx_gpu->protection_disabled = true;
	}

	gpu_write(gpu, REG_AXXX_CP_DEBUG,
			AXXX_CP_DEBUG_MIU_128BIT_WRITE_ENABLE);
	gpu_write(gpu, REG_AXXX_CP_ME_RAM_WADDR, 0);
	for (i = 1; i < len; i++)
		gpu_write(gpu, REG_AXXX_CP_ME_RAM_DATA, ptr[i]);

	/* Load PFP: */
	ptr = (uint32_t *)(adreno_gpu->fw[ADRENO_FW_PFP]->data);
	len = adreno_gpu->fw[ADRENO_FW_PFP]->size / 4;
	DBG("loading PFP ucode version: %x", ptr[5]);

	gpu_write(gpu, REG_A2XX_CP_PFP_UCODE_ADDR, 0);
	for (i = 1; i < len; i++)
		gpu_write(gpu, REG_A2XX_CP_PFP_UCODE_DATA, ptr[i]);

	gpu_write(gpu, REG_AXXX_CP_QUEUE_THRESHOLDS, 0x000C0804);

	/*
	 * Clear any pending CP interrupts before starting the micro engine.
	 * This matches the KGSL driver sequence and ensures the CP starts
	 * with a clean interrupt state, which is important for recovery.
	 */
	gpu_write(gpu, REG_AXXX_CP_INT_ACK, 0xFFFFFFFF);

	/*
	 * Reset ring pointers immediately before starting the ME.
	 * This matches the KGSL sequence where rb->rptr = rb->wptr = 0
	 * is set just before clearing ME_HALT. Critical for recovery.
	 */
	gpu->rb[0]->cur = gpu->rb[0]->next = gpu->rb[0]->start;
	gpu->rb[0]->memptrs->rptr = 0;
	gpu_write(gpu, REG_AXXX_CP_RB_WPTR, 0);

	/* clear ME_HALT to start micro engine */
	gpu_write(gpu, REG_AXXX_CP_ME_CNTL, 0);

	/*
	 * DIAGNOSTIC: dump key A2XX state at end of every hw_init. Fires once
	 * per pm_resume cycle, so each session start prints exactly one line.
	 * Use this to compare register state across sessions (kmscube on fresh
	 * boot vs kmscube after surface-manager).
	 */
	{
		static unsigned int hw_init_seq;

		pr_info("a2xx hw_init seq=%u: PT_BASE=%08x MMU_CONFIG=%08x "
			"TRAN_ERROR=%08x RBBM_STATUS=%08x "
			"PM_OVERRIDE1=%08x PM_OVERRIDE2=%08x "
			"SQ_INTERP=%08x SQ_GPR_MGMT=%08x\n",
			++hw_init_seq,
			gpu_read(gpu, REG_A2XX_MH_MMU_PT_BASE),
			gpu_read(gpu, REG_A2XX_MH_MMU_CONFIG),
			gpu_read(gpu, REG_A2XX_MH_MMU_TRAN_ERROR),
			gpu_read(gpu, REG_A2XX_RBBM_STATUS),
			gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE1),
			gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE2),
			gpu_read(gpu, REG_A2XX_SQ_INTERPOLATOR_CNTL),
			gpu_read(gpu, REG_A2XX_SQ_GPR_MANAGEMENT));

		/*
		 * MH (Memory Hub) diagnostic dump - investigating period-8
		 * cycle in rendering output. The MH ARBITER is configured for
		 * IN_FLIGHT_LIMIT=8 (8 in-flight memory transactions). Per
		 * Gemini's hypothesis the MH may use seqno-modulo-8 to select
		 * an internal write buffer / transaction tag, with buffers
		 * 1-7 holding stale config from bootloader/prior state.
		 *
		 * Read CLNT_INTF_CTRL_CONFIG1 + CONFIG2 and sweep MH_DEBUG_CNTL
		 * (0x0a4e) writing values 0..31 and reading MH_DEBUG_DATA
		 * (0x0a4f) to dump all hidden MH state on every hw_init.
		 */
		{
			u32 i, vals[64];
			pr_info("a2xx MH probe: CLNT_INTF_CFG1=%08x CFG2=%08x\n",
				gpu_read(gpu, REG_A2XX_MH_CLNT_INTF_CTRL_CONFIG1),
				gpu_read(gpu, REG_A2XX_MH_CLNT_INTF_CTRL_CONFIG2));
			pr_info("a2xx MH probe: AXI_ERR=%08x INT_STATUS=%08x\n",
				gpu_read(gpu, 0x0a45),
				gpu_read(gpu, 0x0a43));
			/* Undocumented MH regs - webOS/KGSL readback shows:
			 * 0x0a56=0x765cab98, 0x0a57=0x00043210, 0x0a58=0x00000020
			 * (the latter looks like an 8-port routing table). */
			pr_info("a2xx MH probe: 0x0a56=%08x 0x0a57=%08x 0x0a58=%08x\n",
				gpu_read(gpu, 0x0a56),
				gpu_read(gpu, 0x0a57),
				gpu_read(gpu, 0x0a58));
			/*
			 * SQ slot/state probes per Gemini's analysis - the
			 * cycle-of-8 may reflect SQ wavefront slot rotation
			 * with 7 of 8 slots holding stale parameter SRAM.
			 * SQ_INST_STORE_MANAGMENT (0x0d02) shows VS/PIX
			 * instruction-base offsets; SQ_DEBUG_MISC (0x0d05)
			 * exposes internal SQ debug state. SQ_FLOW_CONTROL
			 * (0x0d01) may indicate which slot is current.
			 */
			pr_info("a2xx SQ probe: GPR_MGMT=%08x INST_STORE_MGMT=%08x FLOW_CTRL=%08x DEBUG_MISC=%08x\n",
				gpu_read(gpu, 0x0d00),
				gpu_read(gpu, 0x0d02),
				gpu_read(gpu, 0x0d01),
				gpu_read(gpu, 0x0d05));
			/* Extended sweep 0..63 - matches KGSL's postmortem dump.
			 * Values 32..63 may expose hidden state hw_init alone misses. */
			for (i = 0; i < 64; i++) {
				gpu_write(gpu, 0x0a4e, i); /* MH_DEBUG_CNTL */
				vals[i] = gpu_read(gpu, 0x0a4f); /* MH_DEBUG_DATA */
			}
			pr_info("a2xx MH_DEBUG[ 0..7]=%08x %08x %08x %08x %08x %08x %08x %08x\n",
				vals[0], vals[1], vals[2], vals[3],
				vals[4], vals[5], vals[6], vals[7]);
			pr_info("a2xx MH_DEBUG[ 8..15]=%08x %08x %08x %08x %08x %08x %08x %08x\n",
				vals[8], vals[9], vals[10], vals[11],
				vals[12], vals[13], vals[14], vals[15]);
			pr_info("a2xx MH_DEBUG[16..23]=%08x %08x %08x %08x %08x %08x %08x %08x\n",
				vals[16], vals[17], vals[18], vals[19],
				vals[20], vals[21], vals[22], vals[23]);
			pr_info("a2xx MH_DEBUG[24..31]=%08x %08x %08x %08x %08x %08x %08x %08x\n",
				vals[24], vals[25], vals[26], vals[27],
				vals[28], vals[29], vals[30], vals[31]);
			pr_info("a2xx MH_DEBUG[32..39]=%08x %08x %08x %08x %08x %08x %08x %08x\n",
				vals[32], vals[33], vals[34], vals[35],
				vals[36], vals[37], vals[38], vals[39]);
			pr_info("a2xx MH_DEBUG[40..47]=%08x %08x %08x %08x %08x %08x %08x %08x\n",
				vals[40], vals[41], vals[42], vals[43],
				vals[44], vals[45], vals[46], vals[47]);
			pr_info("a2xx MH_DEBUG[48..55]=%08x %08x %08x %08x %08x %08x %08x %08x\n",
				vals[48], vals[49], vals[50], vals[51],
				vals[52], vals[53], vals[54], vals[55]);
			pr_info("a2xx MH_DEBUG[56..63]=%08x %08x %08x %08x %08x %08x %08x %08x\n",
				vals[56], vals[57], vals[58], vals[59],
				vals[60], vals[61], vals[62], vals[63]);
		}
	}

	return a2xx_me_init(gpu) ? 0 : -EINVAL;
}

static void a2xx_recover(struct msm_gpu *gpu)
{
	int i;

	adreno_dump_info(gpu);

	for (i = 0; i < 8; i++) {
		printk("CP_SCRATCH_REG%d: %u\n", i,
			gpu_read(gpu, REG_AXXX_CP_SCRATCH_REG0 + i));
	}

	/* dump registers before resetting gpu, if enabled: */
	if (hang_debug)
		a2xx_dump(gpu);

	/*
	 * Perform a full GPU reset matching the sequence in a2xx_hw_init()
	 * and the legacy KGSL driver. A partial reset (0x1 = CP only) is
	 * insufficient when the GPU is truly hung.
	 *
	 * The sequence is:
	 * 1. Halt the micro engine to stop any in-flight operations
	 * 2. Power on all blocks via PM_OVERRIDE to ensure they can be reset
	 * 3. Assert full reset on ALL blocks (0xffffffff), not just CP
	 * 4. Wait 30ms for the reset to complete (per KGSL driver)
	 * 5. Deassert reset
	 */
	gpu_write(gpu, REG_AXXX_CP_ME_CNTL, AXXX_CP_ME_CNTL_HALT);

	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE1, 0xfffffffe);
	gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, 0xffffffff);

	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0xffffffff);
	msleep(30);
	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0);

	adreno_recover(gpu);
}

static void a2xx_destroy(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);

	DBG("%s", gpu->name);

	if (a2xx_gpu->shadow_bo) {
		msm_gem_kernel_put(a2xx_gpu->shadow_bo, gpu->vm);
		a2xx_gpu->shadow_bo = NULL;
	}

	adreno_gpu_cleanup(adreno_gpu);

	kfree(a2xx_gpu);
}

/*
 * Mask of all RBBM_STATUS bits that indicate the GPU is busy.
 * Derived from the webOS KGSL driver which checks RBBM_STATUS == 0x110
 * for idle (only CMDFIFO_AVAIL and HIRQ_PENDING are allowed to be set).
 * All these bits must be clear for the gfx3d_axi_clk to halt properly.
 */
#define A2XX_RBBM_BUSY_MASK ( \
	A2XX_RBBM_STATUS_TC_BUSY | \
	A2XX_RBBM_STATUS_CPRQ_PENDING | \
	A2XX_RBBM_STATUS_CFRQ_PENDING | \
	A2XX_RBBM_STATUS_PFRQ_PENDING | \
	A2XX_RBBM_STATUS_VGT_BUSY_NO_DMA | \
	A2XX_RBBM_STATUS_RBBM_WU_BUSY | \
	A2XX_RBBM_STATUS_CP_NRT_BUSY | \
	A2XX_RBBM_STATUS_MH_BUSY | \
	A2XX_RBBM_STATUS_MH_COHERENCY_BUSY | \
	A2XX_RBBM_STATUS_SX_BUSY | \
	A2XX_RBBM_STATUS_TPC_BUSY | \
	A2XX_RBBM_STATUS_SC_CNTX_BUSY | \
	A2XX_RBBM_STATUS_PA_BUSY | \
	A2XX_RBBM_STATUS_VGT_BUSY | \
	A2XX_RBBM_STATUS_SQ_CNTX17_BUSY | \
	A2XX_RBBM_STATUS_SQ_CNTX0_BUSY | \
	A2XX_RBBM_STATUS_RB_CNTX_BUSY | \
	A2XX_RBBM_STATUS_GUI_ACTIVE)

static bool a2xx_idle(struct msm_gpu *gpu)
{
	uint32_t status;

	/* wait for ringbuffer to drain: */
	if (!adreno_idle(gpu, gpu->rb[0]))
		return false;

	/* then wait for GPU to finish: */
	if (spin_until(!(gpu_read(gpu, REG_A2XX_RBBM_STATUS) &
			A2XX_RBBM_STATUS_GUI_ACTIVE))) {
		DRM_ERROR("%s: timeout waiting for GPU to idle!\n", gpu->name);

		/* TODO maybe we need to reset GPU here to recover from hang? */
		return false;
	}

	/*
	 * Wait for ALL busy bits to clear, not just the obvious ones.
	 * The webOS KGSL driver waits for RBBM_STATUS == 0x110 (only
	 * CMDFIFO_AVAIL and HIRQ_PENDING set). If any busy bit remains
	 * set, the gfx3d_axi_clk branch clock cannot halt properly.
	 */
	if (spin_until(!((status = gpu_read(gpu, REG_A2XX_RBBM_STATUS)) &
			 A2XX_RBBM_BUSY_MASK))) {
		DRM_ERROR("%s: timeout waiting for GPU idle, RBBM_STATUS=%08x\n",
			  gpu->name, status);
		return false;
	}

	return true;
}

static irqreturn_t a2xx_irq(struct msm_gpu *gpu)
{
	uint32_t mstatus, status;

	mstatus = gpu_read(gpu, REG_A2XX_MASTER_INT_SIGNAL);

	if (mstatus & A2XX_MASTER_INT_SIGNAL_MH_INT_STAT) {
		uint32_t fault_addr, tran_err, rbbm_st;
		uint32_t rb_base, rb_rptr, rb_wptr;
		uint32_t ib1_base, ib1_bufsz;
		uint32_t clnt_cfg1, clnt_cfg2;

		status = gpu_read(gpu, REG_A2XX_MH_INTERRUPT_STATUS);
		fault_addr = gpu_read(gpu, REG_A2XX_MH_MMU_PAGE_FAULT);

		dev_warn(gpu->dev->dev, "MH_INT: %08X\n", status);
		dev_warn(gpu->dev->dev, "MMU_PAGE_FAULT: %08X\n", fault_addr);

		if (status & A2XX_MH_INTERRUPT_MASK_MMU_PAGE_FAULT) {
			/*
			 * Extra diagnostics for the deterministic
			 * 0xc000428b fault. Dumps where the CP was in
			 * the cmdstream, which IB, which MH client
			 * generated the bad access, and the AXI
			 * translation-error code.
			 */
			tran_err  = gpu_read(gpu, REG_A2XX_MH_MMU_TRAN_ERROR);
			rbbm_st   = gpu_read(gpu, REG_A2XX_RBBM_STATUS);
			rb_base   = gpu_read(gpu, REG_AXXX_CP_RB_BASE);
			rb_rptr   = gpu_read(gpu, REG_AXXX_CP_RB_RPTR);
			rb_wptr   = gpu_read(gpu, REG_AXXX_CP_RB_WPTR);
			ib1_base  = gpu_read(gpu, REG_AXXX_CP_IB1_BASE);
			ib1_bufsz = gpu_read(gpu, REG_AXXX_CP_IB1_BUFSZ);
			clnt_cfg1 = gpu_read(gpu, REG_A2XX_MH_CLNT_INTF_CTRL_CONFIG1);
			clnt_cfg2 = gpu_read(gpu, REG_A2XX_MH_CLNT_INTF_CTRL_CONFIG2);

			dev_warn(gpu->dev->dev,
				 "  TRAN_ERROR=%08x RBBM_STATUS=%08x\n",
				 tran_err, rbbm_st);
			dev_warn(gpu->dev->dev,
				 "  RB_BASE=%08x RPTR=%08x WPTR=%08x\n",
				 rb_base, rb_rptr, rb_wptr);
			dev_warn(gpu->dev->dev,
				 "  IB1_BASE=%08x IB1_BUFSZ=%08x\n",
				 ib1_base, ib1_bufsz);
			dev_warn(gpu->dev->dev,
				 "  MH_CLNT_INTF_CFG1=%08x CFG2=%08x\n",
				 clnt_cfg1, clnt_cfg2);

			a2xx_gpummu_debug_fault(to_msm_vm(gpu->vm)->mmu, fault_addr);

			/*
			 * Dump up to 64 dwords of the last submitted user IB1
			 * so we can grep for the offending pointer (0xc000428b)
			 * and find which packet / descriptor placed it there.
			 *
			 * Resolve IOVA -> kvirt at fault time via the gpummu
			 * page table (no GEM locks taken). A single page (4 KB
			 * = 1024 dwords) is enough; we cap at 64 dwords below.
			 */
			if (a2xx_last_ib.ib1_iova && a2xx_last_ib.ib1_size) {
				u32 *ib_kv = a2xx_gpummu_iova_to_kvirt(
					to_msm_vm(gpu->vm)->mmu,
					a2xx_last_ib.ib1_iova);
				u32 dwords = min(a2xx_last_ib.ib1_size, 64u);
				u32 j;

				dev_warn(gpu->dev->dev,
					 "  last IB1 iova=%016llx size=%u dwords kvirt=%p (dumping %u)\n",
					 a2xx_last_ib.ib1_iova,
					 a2xx_last_ib.ib1_size, ib_kv, dwords);

				if (ib_kv) {
					for (j = 0; j < dwords; j += 8) {
						dev_warn(gpu->dev->dev,
						    "  +%03x: %08x %08x %08x %08x %08x %08x %08x %08x\n",
						    j * 4,
						    ib_kv[j + 0],
						    j + 1 < dwords ? ib_kv[j + 1] : 0,
						    j + 2 < dwords ? ib_kv[j + 2] : 0,
						    j + 3 < dwords ? ib_kv[j + 3] : 0,
						    j + 4 < dwords ? ib_kv[j + 4] : 0,
						    j + 5 < dwords ? ib_kv[j + 5] : 0,
						    j + 6 < dwords ? ib_kv[j + 6] : 0,
						    j + 7 < dwords ? ib_kv[j + 7] : 0);
					}
				}
			}
		}

		gpu_write(gpu, REG_A2XX_MH_INTERRUPT_CLEAR, status);
	}

	if (mstatus & A2XX_MASTER_INT_SIGNAL_CP_INT_STAT) {
		status = gpu_read(gpu, REG_AXXX_CP_INT_STATUS);

		/* only RB_INT is expected */
		if (status & ~AXXX_CP_INT_CNTL_RB_INT_MASK)
			dev_warn(gpu->dev->dev, "CP_INT: %08X\n", status);

		gpu_write(gpu, REG_AXXX_CP_INT_ACK, status);
	}

	if (mstatus & A2XX_MASTER_INT_SIGNAL_RBBM_INT_STAT) {
		status = gpu_read(gpu, REG_A2XX_RBBM_INT_STATUS);

		dev_dbg(gpu->dev->dev, "RBBM_INT: %08X\n", status);

		gpu_write(gpu, REG_A2XX_RBBM_INT_ACK, status);
	}

	msm_gpu_retire(gpu);

	return IRQ_HANDLED;
}

static const unsigned int a200_registers[] = {
	0x0000, 0x0002, 0x0004, 0x000B, 0x003B, 0x003D, 0x0040, 0x0044,
	0x0046, 0x0047, 0x01C0, 0x01C1, 0x01C3, 0x01C8, 0x01D5, 0x01D9,
	0x01DC, 0x01DD, 0x01EA, 0x01EA, 0x01EE, 0x01F3, 0x01F6, 0x01F7,
	0x01FC, 0x01FF, 0x0391, 0x0392, 0x039B, 0x039E, 0x03B2, 0x03B5,
	0x03B7, 0x03B7, 0x03F8, 0x03FB, 0x0440, 0x0440, 0x0443, 0x0444,
	0x044B, 0x044B, 0x044D, 0x044F, 0x0452, 0x0452, 0x0454, 0x045B,
	0x047F, 0x047F, 0x0578, 0x0587, 0x05C9, 0x05C9, 0x05D0, 0x05D0,
	0x0601, 0x0604, 0x0606, 0x0609, 0x060B, 0x060E, 0x0613, 0x0614,
	0x0A29, 0x0A2B, 0x0A2F, 0x0A31, 0x0A40, 0x0A43, 0x0A45, 0x0A45,
	0x0A4E, 0x0A4F, 0x0C2C, 0x0C2C, 0x0C30, 0x0C30, 0x0C38, 0x0C3C,
	0x0C40, 0x0C40, 0x0C44, 0x0C44, 0x0C80, 0x0C86, 0x0C88, 0x0C94,
	0x0C99, 0x0C9A, 0x0CA4, 0x0CA5, 0x0D00, 0x0D03, 0x0D06, 0x0D06,
	0x0D08, 0x0D0B, 0x0D34, 0x0D35, 0x0DAE, 0x0DC1, 0x0DC8, 0x0DD4,
	0x0DD8, 0x0DD9, 0x0E00, 0x0E00, 0x0E02, 0x0E04, 0x0E17, 0x0E1E,
	0x0EC0, 0x0EC9, 0x0ECB, 0x0ECC, 0x0ED0, 0x0ED0, 0x0ED4, 0x0ED7,
	0x0EE0, 0x0EE2, 0x0F01, 0x0F02, 0x0F0C, 0x0F0C, 0x0F0E, 0x0F12,
	0x0F26, 0x0F2A, 0x0F2C, 0x0F2C, 0x2000, 0x2002, 0x2006, 0x200F,
	0x2080, 0x2082, 0x2100, 0x2109, 0x210C, 0x2114, 0x2180, 0x2184,
	0x21F5, 0x21F7, 0x2200, 0x2208, 0x2280, 0x2283, 0x2293, 0x2294,
	0x2300, 0x2308, 0x2312, 0x2312, 0x2316, 0x231D, 0x2324, 0x2326,
	0x2380, 0x2383, 0x2400, 0x2402, 0x2406, 0x240F, 0x2480, 0x2482,
	0x2500, 0x2509, 0x250C, 0x2514, 0x2580, 0x2584, 0x25F5, 0x25F7,
	0x2600, 0x2608, 0x2680, 0x2683, 0x2693, 0x2694, 0x2700, 0x2708,
	0x2712, 0x2712, 0x2716, 0x271D, 0x2724, 0x2726, 0x2780, 0x2783,
	0x4000, 0x4003, 0x4800, 0x4805, 0x4900, 0x4900, 0x4908, 0x4908,
	~0   /* sentinel */
};

static const unsigned int a220_registers[] = {
	0x0000, 0x0002, 0x0004, 0x000B, 0x003B, 0x003D, 0x0040, 0x0044,
	0x0046, 0x0047, 0x01C0, 0x01C1, 0x01C3, 0x01C8, 0x01D5, 0x01D9,
	0x01DC, 0x01DD, 0x01EA, 0x01EA, 0x01EE, 0x01F3, 0x01F6, 0x01F7,
	0x01FC, 0x01FF, 0x0391, 0x0392, 0x039B, 0x039E, 0x03B2, 0x03B5,
	0x03B7, 0x03B7, 0x03F8, 0x03FB, 0x0440, 0x0440, 0x0443, 0x0444,
	0x044B, 0x044B, 0x044D, 0x044F, 0x0452, 0x0452, 0x0454, 0x045B,
	0x047F, 0x047F, 0x0578, 0x0587, 0x05C9, 0x05C9, 0x05D0, 0x05D0,
	0x0601, 0x0604, 0x0606, 0x0609, 0x060B, 0x060E, 0x0613, 0x0614,
	0x0A29, 0x0A2B, 0x0A2F, 0x0A31, 0x0A40, 0x0A40, 0x0A42, 0x0A43,
	0x0A45, 0x0A45, 0x0A4E, 0x0A4F, 0x0C30, 0x0C30, 0x0C38, 0x0C39,
	0x0C3C, 0x0C3C, 0x0C80, 0x0C81, 0x0C88, 0x0C93, 0x0D00, 0x0D03,
	0x0D05, 0x0D06, 0x0D08, 0x0D0B, 0x0D34, 0x0D35, 0x0DAE, 0x0DC1,
	0x0DC8, 0x0DD4, 0x0DD8, 0x0DD9, 0x0E00, 0x0E00, 0x0E02, 0x0E04,
	0x0E17, 0x0E1E, 0x0EC0, 0x0EC9, 0x0ECB, 0x0ECC, 0x0ED0, 0x0ED0,
	0x0ED4, 0x0ED7, 0x0EE0, 0x0EE2, 0x0F01, 0x0F02, 0x2000, 0x2002,
	0x2006, 0x200F, 0x2080, 0x2082, 0x2100, 0x2102, 0x2104, 0x2109,
	0x210C, 0x2114, 0x2180, 0x2184, 0x21F5, 0x21F7, 0x2200, 0x2202,
	0x2204, 0x2204, 0x2208, 0x2208, 0x2280, 0x2282, 0x2294, 0x2294,
	0x2300, 0x2308, 0x2309, 0x230A, 0x2312, 0x2312, 0x2316, 0x2316,
	0x2318, 0x231D, 0x2324, 0x2326, 0x2380, 0x2383, 0x2400, 0x2402,
	0x2406, 0x240F, 0x2480, 0x2482, 0x2500, 0x2502, 0x2504, 0x2509,
	0x250C, 0x2514, 0x2580, 0x2584, 0x25F5, 0x25F7, 0x2600, 0x2602,
	0x2604, 0x2606, 0x2608, 0x2608, 0x2680, 0x2682, 0x2694, 0x2694,
	0x2700, 0x2708, 0x2712, 0x2712, 0x2716, 0x2716, 0x2718, 0x271D,
	0x2724, 0x2726, 0x2780, 0x2783,
	/*
	 * Extended constant-memory coverage for state-leak debugging.
	 * Covers the full A2XX shader-constant SRAM as MMIO so the
	 * /sys/kernel/debug/dri/0/gpu hangdump shows whether stale
	 * constant data leaks across DRM-client transitions.
	 *
	 *   0x4000..0x40FF  256 vec4 ALU constants (64 dwords each
	 *                   for VS at offset 0x20, PS at offset 0x120
	 *                   per Mesa's PS_CONST_BASE / VS_CONST_BASE)
	 *   0x4800..0x48BF  32 texture-fetch constants (6 dwords each)
	 *   0x4900..0x4907  8 dwords boolean constants (256 bool flags)
	 *   0x4908..0x493F  56 dwords loop control constants
	 */
	0x4000, 0x40FF, 0x4800, 0x48BF, 0x4900, 0x4907, 0x4908, 0x493F,
	~0   /* sentinel */
};

static const unsigned int a225_registers[] = {
	0x0000, 0x0002, 0x0004, 0x000B, 0x003B, 0x003D, 0x0040, 0x0044,
	0x0046, 0x0047, 0x013C, 0x013C, 0x0140, 0x014F, 0x01C0, 0x01C1,
	0x01C3, 0x01C8, 0x01D5, 0x01D9, 0x01DC, 0x01DD, 0x01EA, 0x01EA,
	0x01EE, 0x01F3, 0x01F6, 0x01F7, 0x01FC, 0x01FF, 0x0391, 0x0392,
	0x039B, 0x039E, 0x03B2, 0x03B5, 0x03B7, 0x03B7, 0x03F8, 0x03FB,
	0x0440, 0x0440, 0x0443, 0x0444, 0x044B, 0x044B, 0x044D, 0x044F,
	0x0452, 0x0452, 0x0454, 0x045B, 0x047F, 0x047F, 0x0578, 0x0587,
	0x05C9, 0x05C9, 0x05D0, 0x05D0, 0x0601, 0x0604, 0x0606, 0x0609,
	0x060B, 0x060E, 0x0613, 0x0614, 0x0A29, 0x0A2B, 0x0A2F, 0x0A31,
	0x0A40, 0x0A40, 0x0A42, 0x0A43, 0x0A45, 0x0A45, 0x0A4E, 0x0A4F,
	0x0C01, 0x0C1D, 0x0C30, 0x0C30, 0x0C38, 0x0C39, 0x0C3C, 0x0C3C,
	0x0C80, 0x0C81, 0x0C88, 0x0C93, 0x0D00, 0x0D03, 0x0D05, 0x0D06,
	0x0D08, 0x0D0B, 0x0D34, 0x0D35, 0x0DAE, 0x0DC1, 0x0DC8, 0x0DD4,
	0x0DD8, 0x0DD9, 0x0E00, 0x0E00, 0x0E02, 0x0E04, 0x0E17, 0x0E1E,
	0x0EC0, 0x0EC9, 0x0ECB, 0x0ECC, 0x0ED0, 0x0ED0, 0x0ED4, 0x0ED7,
	0x0EE0, 0x0EE2, 0x0F01, 0x0F02, 0x2000, 0x200F, 0x2080, 0x2082,
	0x2100, 0x2109, 0x210C, 0x2114, 0x2180, 0x2184, 0x21F5, 0x21F7,
	0x2200, 0x2202, 0x2204, 0x2206, 0x2208, 0x2210, 0x2220, 0x2222,
	0x2280, 0x2282, 0x2294, 0x2294, 0x2297, 0x2297, 0x2300, 0x230A,
	0x2312, 0x2312, 0x2315, 0x2316, 0x2318, 0x231D, 0x2324, 0x2326,
	0x2340, 0x2357, 0x2360, 0x2360, 0x2380, 0x2383, 0x2400, 0x240F,
	0x2480, 0x2482, 0x2500, 0x2509, 0x250C, 0x2514, 0x2580, 0x2584,
	0x25F5, 0x25F7, 0x2600, 0x2602, 0x2604, 0x2606, 0x2608, 0x2610,
	0x2620, 0x2622, 0x2680, 0x2682, 0x2694, 0x2694, 0x2697, 0x2697,
	0x2700, 0x270A, 0x2712, 0x2712, 0x2715, 0x2716, 0x2718, 0x271D,
	0x2724, 0x2726, 0x2740, 0x2757, 0x2760, 0x2760, 0x2780, 0x2783,
	0x4000, 0x4003, 0x4800, 0x4806, 0x4808, 0x4808, 0x4900, 0x4900,
	0x4908, 0x4908,
	~0   /* sentinel */
};

/* would be nice to not have to duplicate the _show() stuff with printk(): */
static void a2xx_dump(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);

	printk("======== A2XX GPU Register Dump ========\n");
	printk("GPU: %s\n", adreno_is_a20x(adreno_gpu) ? "A20X (Yamato)" : "A22X (Leia)");

	/* Status registers */
	printk("STATUS REGISTERS:\n");
	printk("  RBBM_STATUS (0x05d0) = %08x\n",
			gpu_read(gpu, REG_A2XX_RBBM_STATUS));
	printk("  CP_RB_RPTR = %08x, CP_RB_WPTR = %08x\n",
			gpu_read(gpu, REG_AXXX_CP_RB_RPTR),
			gpu_read(gpu, REG_AXXX_CP_RB_WPTR));

	/* Critical shader registers - these affect rendering quality */
	printk("SHADER REGISTERS:\n");
	printk("  SQ_GPR_MANAGEMENT (0x0d00) = %08x\n",
			gpu_read(gpu, REG_A2XX_SQ_GPR_MANAGEMENT));
	printk("  SQ_INST_STORE_MANAGMENT (0x0d02) = %08x\n",
			gpu_read(gpu, REG_A2XX_SQ_INST_STORE_MANAGMENT));
	printk("  SQ_INTERPOLATOR_CNTL (0x2182) = %08x\n",
			gpu_read(gpu, REG_A2XX_SQ_INTERPOLATOR_CNTL));

	/* Power management */
	printk("POWER MANAGEMENT:\n");
	printk("  RBBM_PM_OVERRIDE1 (0x039c) = %08x\n",
			gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE1));
	printk("  RBBM_PM_OVERRIDE2 (0x039d) = %08x\n",
			gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE2));

	/* A22X specific */
	if (!adreno_is_a20x(adreno_gpu)) {
		printk("A22X SPECIFIC:\n");
		printk("  A220_RB_LRZ_VSC_CONTROL (0x2209) = %08x\n",
				gpu_read(gpu, REG_A2XX_A220_RB_LRZ_VSC_CONTROL));
		printk("  A220_GRAS_CONTROL (0x2210) = %08x\n",
				gpu_read(gpu, REG_A2XX_A220_GRAS_CONTROL));
	}

	printk("========================================\n");
	adreno_dump(gpu);
}

static struct msm_gpu_state *a2xx_gpu_state_get(struct msm_gpu *gpu)
{
	struct msm_gpu_state *state = kzalloc(sizeof(*state), GFP_KERNEL);

	if (!state)
		return ERR_PTR(-ENOMEM);

	adreno_gpu_state_get(gpu, state);

	state->rbbm_status = gpu_read(gpu, REG_A2XX_RBBM_STATUS);

	return state;
}

static u64 a2xx_gpu_busy(struct msm_gpu *gpu, unsigned long *out_sample_rate)
{
	u64 busy_cycles;

	busy_cycles = gpu_read64(gpu, REG_A2XX_RBBM_PERFCOUNTER1_LO);
	*out_sample_rate = clk_get_rate(gpu->core_clk);

	return busy_cycles;
}

static struct drm_gpuvm *
a2xx_create_vm(struct msm_gpu *gpu, struct platform_device *pdev)
{
	struct msm_mmu *mmu = a2xx_gpummu_new(&pdev->dev, gpu);
	struct drm_gpuvm *vm;

	/* VA base must match GPUMMU_VA_START in a2xx_gpummu.c and the
	 * MH_MMU_VA_RANGE write in a2xx_hw_init - all three need to agree
	 * or BOs get IOVAs outside the configured MMU range and fault. */
	vm = msm_gem_vm_create(gpu->dev, mmu, "gpu", 0x66000000UL,
			       0xfff * SZ_64K, true);

	if (IS_ERR(vm) && !IS_ERR(mmu))
		mmu->funcs->destroy(mmu);

	return vm;
}

static u32 a2xx_get_rptr(struct msm_gpu *gpu, struct msm_ringbuffer *ring)
{
	ring->memptrs->rptr = gpu_read(gpu, REG_AXXX_CP_RB_RPTR);
	return ring->memptrs->rptr;
}

/*
 * Force-collapse the GFX3D GDSC on every runtime suspend, and pulse
 * GFX3D_RESET on every runtime resume.
 *
 * Background: the QCOM gdsc driver registers all MSM8660 MMCC GDSCs
 * with gov=NULL, so the genpd framework never actually fires the
 * gdsc_disable callback on idle. The GFX3D rail therefore stays
 * permanently in "Logic-Off-Memory-On" retention mode (GDSCR bits
 * ENABLE+RETENTION both set), preserving SQ wavefront scheduler and
 * VPC SRAM state across submits. Symptom: deterministic period-8
 * cycle of rendering nondeterminism, fingerprinted across many
 * weeks of investigation (see reports/gpu-cycle-of-8-*.md).
 *
 * Mainline's gdsc_disable LEGACY_FOOTSWITCH path only clears ENABLE
 * (BIT 8). Mainline's gdsc_enable only pulses the AHB reset
 * (GFX3D_AHB_RESET); the core_clk reset (GFX3D_RESET) is never
 * touched. Both are required for a true cold-rail cycle.
 *
 * Rather than patch generic gdsc.c (which serves many platforms),
 * isolate the workaround here. Direct register writes via ioremap
 * are layering violations but acceptable for an MSM8660-only quirk;
 * the genpd state intentionally stays "on" since gov=NULL means it
 * never actually transitions and the framework doesn't depend on
 * the hardware-side state matching its software-side bookkeeping.
 */
/* MMCC register addresses + GFX3D bits - defined near top of file for
 * use by a2xx_one_shot_boot_reset (called early in a2xx_hw_init) as
 * well as a2xx_force_gdsc_*. Moved here from inline GDSC block.
 */

/*
 * Initial Option C (force GDSC collapse on pm_runtime suspend + core
 * reset pulse on resume) successfully cleared the SQ/VPC logic state
 * that was driving the period-8 cycle - but it also wiped the GMEM
 * SRAM which is on the same GFX3D power rail. Result: tile-boundary
 * artefacts (vertical stripe at x=512), edge spurs, off-triangle
 * garbage. We traded one bug for another.
 *
 * Option D (Gemini AI update-23 reply): keep the GDSC permanently
 * powered (preserving GMEM), and pulse just GFX3D_RESET (the
 * core_clk reset that resets the LOGIC blocks SQ/VPC) at the start
 * of every submit, right before the WPTR write. This clears the
 * toxic Wavefront Scheduler state without losing the GMEM tile
 * routing SRAM.
 *
 * Default true - this is the shippable knob.
 */
bool a2xx_force_collapse_on_suspend = false;
module_param(a2xx_force_collapse_on_suspend, bool, 0644);
MODULE_PARM_DESC(a2xx_force_collapse_on_suspend,
		 "force GFX3D GDSC collapse + core reset pulse on every "
		 "pm_runtime cycle. Clears the SQ wavefront residue but "
		 "wipes GMEM SRAM, producing tile-boundary artefacts. Per "
		 "Gemini update 27 the tile noise is *more distracting* "
		 "than the baseline 8-cycle's wrong-colour renders, so the "
		 "shippable default is OFF. Kept as A/B knob for testing. "
		 "The proper fix is the Mesa-side SQ scrub (Option E).");

bool a2xx_pulse_reset_on_submit = true;
module_param(a2xx_pulse_reset_on_submit, bool, 0644);
MODULE_PARM_DESC(a2xx_pulse_reset_on_submit,
		 "pulse RBBM_SOFT_RESET before each WPTR write to clear "
		 "SQ/VPC state without wiping GMEM (1=enable)");

uint a2xx_pulse_reset_mask = 0x0000003F;
module_param(a2xx_pulse_reset_mask, uint, 0644);
MODULE_PARM_DESC(a2xx_pulse_reset_mask,
		 "mask written to RBBM_SOFT_RESET during the per-submit "
		 "pulse. A2XX bit-map: BIT(0)=VGT BIT(1)=PA/VPC BIT(2)=SQ "
		 "BIT(3)=SX BIT(4)=TC BIT(5)=RB BIT(6)=BC BIT(7)=MH (DO "
		 "NOT TOUCH) BIT(8)=CP (DO NOT TOUCH). Default 0x3F = "
		 "VGT|PA|SQ|SX|TC|RB (per Gemini update 25 - RB needed "
		 "because the 8-cycle is GMEM-tile aligned).");

uint a2xx_pulse_reset_udelay = 10;
module_param(a2xx_pulse_reset_udelay, uint, 0644);
MODULE_PARM_DESC(a2xx_pulse_reset_udelay,
		 "udelay (microseconds) for both halves of the per-submit "
		 "RBBM_SOFT_RESET pulse. Default 10us.");

bool a2xx_pulse_reset_force_clocks = true;
module_param(a2xx_pulse_reset_force_clocks, bool, 0644);
MODULE_PARM_DESC(a2xx_pulse_reset_force_clocks,
		 "force all sub-block clocks on via PM_OVERRIDE1/2 before "
		 "the reset pulse. Without this, dynamic clock gating may "
		 "leave target sub-blocks clock-gated and the reset signal "
		 "won't propagate through the flip-flops (the reset write "
		 "'takes' but the logic never resets).");

bool a2xx_pulse_reset_halt_cp = false;
module_param(a2xx_pulse_reset_halt_cp, bool, 0644);
MODULE_PARM_DESC(a2xx_pulse_reset_halt_cp,
		 "additionally halt the CP via CP_ME_CNTL.HALT before the "
		 "pulse and unhalt after. Optional safety measure if the "
		 "pulse races with CP activity. Default off.");

/*
 * Pulse RBBM_SOFT_RESET with a SURGICAL mask that clears only the
 * sub-blocks responsible for the period-8 cycle and per-pixel
 * jitter, WITHOUT touching CP (would wipe microcode), MH (would
 * lose IOMMU state), or the GDSC rail (would wipe GMEM SRAM).
 *
 * Per Gemini AI's A2XX bit-map (update 24 reply):
 *
 *   BIT(0) - VGT (Vertex Geometry Tester)
 *   BIT(1) - PA/VPC (Primitive Assembly / Vertex Parameter Cache)
 *   BIT(2) - SQ (Shader / Wavefront Scheduler)
 *   BIT(3) - SX (Shader Export)
 *   BIT(4) - TC (Texture Cache)
 *   BIT(5) - ROP (Render Backend)
 *   BIT(7) - MH (Memory Hub) -- DO NOT TOUCH
 *   BIT(8) - CP (Command Processor) -- DO NOT TOUCH
 *
 * Target mask = 0x1F = VGT | PA/VPC | SQ | SX | TC. This is the
 * recommended scrub set: it kills the wavefront-scheduler state
 * (the 8-cycle), the varying interpolator state (per-pixel jitter),
 * and the texture cache, while leaving CP, MH, ROP, and GMEM SRAM
 * untouched.
 *
 * Called from a2xx_submit right before adreno_flush() writes WPTR.
 * The CP is idle at this point (waiting for new work), so the
 * sub-block resets are safe.
 *
 * Earlier attempts that didn't work:
 *   - GFX3D_RESET (MMCC 0x0210 bit 12): wipes CP, hangs at rptr=20
 *   - RBBM_SOFT_RESET=0xFFFFFFFE: too broad, resets MH (IOMMU)
 */
static void a2xx_pulse_gfx3d_reset(struct msm_gpu *gpu)
{
	u32 saved_pm1 = 0, saved_pm2 = 0;
	u32 saved_me_cntl = 0;

	if (!a2xx_pulse_reset_on_submit)
		return;

	/*
	 * Force all sub-block clocks on before pulsing the reset.
	 * Without this, dynamic clock gating leaves target sub-blocks
	 * with their clocks off, and the synchronous reset signal can't
	 * propagate through the flip-flops. The reset register write
	 * "takes" but the logic never actually resets. This is the
	 * primary suspect for our previous bit-identical Phase A/B
	 * result with mask=0x1F (per Gemini update 25 reply).
	 */
	if (a2xx_pulse_reset_force_clocks) {
		saved_pm1 = gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE1);
		saved_pm2 = gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE2);
		gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE1, 0xFFFFFFFF);
		gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, 0xFFFFFFFF);
		(void)gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE2);
	}

	/*
	 * Optionally halt the CP first so it can't race the pulse.
	 * Off by default - the pulse is supposed to happen pre-WPTR
	 * when the CP is idle waiting for new work anyway.
	 */
	if (a2xx_pulse_reset_halt_cp) {
		saved_me_cntl = gpu_read(gpu, REG_AXXX_CP_ME_CNTL);
		gpu_write(gpu, REG_AXXX_CP_ME_CNTL,
			  saved_me_cntl | AXXX_CP_ME_CNTL_HALT);
		(void)gpu_read(gpu, REG_AXXX_CP_ME_CNTL);
	}

	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, a2xx_pulse_reset_mask);
	(void)gpu_read(gpu, REG_A2XX_RBBM_SOFT_RESET);
	udelay(a2xx_pulse_reset_udelay);
	gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0x00000000);
	(void)gpu_read(gpu, REG_A2XX_RBBM_SOFT_RESET);
	udelay(a2xx_pulse_reset_udelay);

	if (a2xx_pulse_reset_halt_cp) {
		gpu_write(gpu, REG_AXXX_CP_ME_CNTL, saved_me_cntl);
		(void)gpu_read(gpu, REG_AXXX_CP_ME_CNTL);
	}

	if (a2xx_pulse_reset_force_clocks) {
		gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE1, saved_pm1);
		gpu_write(gpu, REG_A2XX_RBBM_PM_OVERRIDE2, saved_pm2);
		(void)gpu_read(gpu, REG_A2XX_RBBM_PM_OVERRIDE2);
	}
}

static void a2xx_force_gdsc_collapse(struct msm_gpu *gpu)
{
	void __iomem *gdscr;
	u32 v;

	if (!a2xx_force_collapse_on_suspend)
		return;

	gdscr = ioremap(A2XX_MMCC_GFX3D_GDSCR, 4);
	if (!gdscr)
		return;

	v = readl(gdscr);
	/* Clamp I/O first, then drop ENABLE + RETENTION together. */
	writel(v | A2XX_GDSCR_CLAMP, gdscr);
	writel((v | A2XX_GDSCR_CLAMP)
	       & ~(A2XX_GDSCR_ENABLE | A2XX_GDSCR_RETENTION), gdscr);
	(void)readl(gdscr); /* posting read */
	iounmap(gdscr);

	udelay(50); /* allow rail to fully drain */
}

static void a2xx_force_gdsc_enable_and_reset(struct msm_gpu *gpu)
{
	void __iomem *gdscr, *resetr;
	u32 v;

	if (!a2xx_force_collapse_on_suspend)
		return;

	gdscr = ioremap(A2XX_MMCC_GFX3D_GDSCR, 4);
	if (gdscr) {
		v = readl(gdscr);
		writel(v | A2XX_GDSCR_ENABLE, gdscr);
		(void)readl(gdscr);
		udelay(2); /* rail charge */
		writel((v | A2XX_GDSCR_ENABLE) & ~A2XX_GDSCR_CLAMP, gdscr);
		(void)readl(gdscr);
		udelay(5); /* clamp settle */
		iounmap(gdscr);
	}

	/*
	 * Pulse GFX3D_RESET (core_clk reset) AFTER the rail is on but
	 * BEFORE the clock controllers turn on the GFX3D clocks. This
	 * mirrors arch/arm/mach-msm/footswitch-8x60.c's "Toggle core
	 * reset now that power is on (required for some cores)" step
	 * which mainline gdsc_enable skips for LEGACY_FOOTSWITCH.
	 */
	resetr = ioremap(A2XX_MMCC_GFX3D_RESET, 4);
	if (resetr) {
		v = readl(resetr);
		writel(v | A2XX_GFX3D_RESET_BIT, resetr);
		(void)readl(resetr);
		udelay(5);
		writel(v & ~A2XX_GFX3D_RESET_BIT, resetr);
		(void)readl(resetr);
		udelay(5);
		iounmap(resetr);
	}
}

static int a2xx_pm_suspend(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);

	/*
	 * Idle the GPU and wait for all AXI transactions to complete.
	 * Without this the gfx3d_axi_clk branch clock cannot halt
	 * because the AXI bus is still servicing GPU requests.
	 */
	if (!a2xx_idle(gpu)) {
		dev_warn(gpu->dev->dev, "GPU didn't idle before suspend\n");

		/*
		 * GPU failed to idle normally. Halt the command processor
		 * and perform a soft reset to force the AXI interface into
		 * a quiescent state. This ensures the gfx3d_axi_clk branch
		 * clock can be disabled even if the GPU was stuck.
		 */
		gpu_write(gpu, REG_AXXX_CP_ME_CNTL, AXXX_CP_ME_CNTL_HALT);

		gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 1);
		gpu_read(gpu, REG_A2XX_RBBM_SOFT_RESET);
		gpu_write(gpu, REG_A2XX_RBBM_SOFT_RESET, 0);

		/* Wait for reset to complete */
		udelay(100);
	}

	/*
	 * Memory barrier to ensure all AXI transactions have completed
	 * before we clear the interconnect vote. This is critical on
	 * non-coherent platforms like MSM8660.
	 */
	wmb();

	/*
	 * Clear interconnect bandwidth vote before disabling clocks.
	 * This tells the bus fabric we no longer need memory bandwidth,
	 * allowing the AXI clock to halt properly. The legacy KGSL
	 * driver did this via msm_bus_scale_client_update_request(BW_INIT).
	 */
	if (a2xx_gpu->icc_path)
		icc_set_bw(a2xx_gpu->icc_path, 0, 0);

	/*
	 * Allow time for the interconnect state change to propagate
	 * through the bus fabric before disabling clocks.
	 */
	udelay(10);

	{
		int ret = msm_gpu_pm_suspend(gpu);

		/*
		 * After clocks are down and AXI is quiescent, force the
		 * GFX3D rail to fully collapse. This clears the SQ
		 * wavefront scheduler and VPC SRAM that would otherwise
		 * persist in retention mode and drive the period-8 cycle.
		 */
		a2xx_force_gdsc_collapse(gpu);

		return ret;
	}
}

static int a2xx_pm_resume(struct msm_gpu *gpu)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	int ret;

	/*
	 * Bring the GFX3D rail back BEFORE msm_gpu_pm_resume enables
	 * the gfx3d clocks. The legacy MSM8660 footswitch power-on
	 * sequence is: set ENABLE -> rail charge -> deassert clamp ->
	 * pulse core reset. We do that here directly via ioremap (see
	 * a2xx_force_gdsc_enable_and_reset for the full rationale) and
	 * then let msm_gpu_pm_resume turn the clocks on as normal.
	 */
	a2xx_force_gdsc_enable_and_reset(gpu);

	ret = msm_gpu_pm_resume(gpu);
	if (ret)
		return ret;

	/* Restore bandwidth after resume (cleared in suspend) */
	if (a2xx_gpu->icc_path) {
		u32 bw = a2xx_icc_bw_for_freq(gpu->fast_rate);

		icc_set_bw(a2xx_gpu->icc_path, bw, bw);
	}

	return 0;
}

/*
 * Set GPU frequency and bandwidth via OPP framework.
 * This is called by devfreq when scaling frequency.
 */
static void a2xx_gpu_set_freq(struct msm_gpu *gpu, struct dev_pm_opp *opp,
			      bool suspended)
{
	struct adreno_gpu *adreno_gpu = to_adreno_gpu(gpu);
	struct a2xx_gpu *a2xx_gpu = to_a2xx_gpu(adreno_gpu);
	unsigned long freq = dev_pm_opp_get_freq(opp);

	/*
	 * Don't change bandwidth when suspended - pm_resume will restore it.
	 * Only update our manual ICC path bandwidth to match the new frequency.
	 */
	if (suspended)
		return;

	/*
	 * Set both avg and peak bandwidth proportional to frequency,
	 * matching the legacy webOS msm_bus grp3d_max_vectors pattern
	 * (ab = ib = clock × 8 bytes/cycle).
	 */
	if (a2xx_gpu->icc_path) {
		u32 bw = a2xx_icc_bw_for_freq(freq);

		icc_set_bw(a2xx_gpu->icc_path, bw, bw);
	}

	dev_pm_opp_set_opp(&gpu->pdev->dev, opp);
}

static const struct adreno_gpu_funcs funcs = {
	.base = {
		.get_param = adreno_get_param,
		.set_param = adreno_set_param,
		.hw_init = a2xx_hw_init,
		.pm_suspend = a2xx_pm_suspend,
		.pm_resume = a2xx_pm_resume,
		.recover = a2xx_recover,
		.submit = a2xx_submit,
		.active_ring = adreno_active_ring,
		.irq = a2xx_irq,
		.destroy = a2xx_destroy,
#if defined(CONFIG_DEBUG_FS) || defined(CONFIG_DEV_COREDUMP)
		.show = adreno_show,
#endif
#if defined(CONFIG_DEBUG_FS)
		.debugfs_init = a2xx_debugfs_init,
#endif
		.gpu_busy = a2xx_gpu_busy,
		.gpu_state_get = a2xx_gpu_state_get,
		.gpu_state_put = adreno_gpu_state_put,
		.create_vm = a2xx_create_vm,
		.get_rptr = a2xx_get_rptr,
		.gpu_set_freq = a2xx_gpu_set_freq,
	},
};

static const struct msm_gpu_perfcntr perfcntrs[] = {
/* TODO */
};

struct msm_gpu *a2xx_gpu_init(struct drm_device *dev)
{
	struct a2xx_gpu *a2xx_gpu = NULL;
	struct adreno_gpu *adreno_gpu;
	struct msm_gpu *gpu;
	struct msm_drm_private *priv = dev->dev_private;
	struct platform_device *pdev = priv->gpu_pdev;
	int ret;

	if (!pdev) {
		dev_err(dev->dev, "no a2xx device\n");
		ret = -ENXIO;
		goto fail;
	}

	a2xx_gpu = kzalloc(sizeof(*a2xx_gpu), GFP_KERNEL);
	if (!a2xx_gpu) {
		ret = -ENOMEM;
		goto fail;
	}

	adreno_gpu = &a2xx_gpu->base;
	gpu = &adreno_gpu->base;

	gpu->perfcntrs = perfcntrs;
	gpu->num_perfcntrs = ARRAY_SIZE(perfcntrs);

	ret = adreno_gpu_init(dev, pdev, adreno_gpu, &funcs, 1);
	if (ret)
		goto fail;

	/* Get interconnect path for memory bandwidth voting */
	a2xx_gpu->icc_path = devm_of_icc_get(&pdev->dev, "gfx-mem");
	if (IS_ERR(a2xx_gpu->icc_path)) {
		ret = PTR_ERR(a2xx_gpu->icc_path);
		/* Allow -ENODATA, interconnect is optional for older DTs */
		if (ret != -ENODATA) {
			DRM_DEV_ERROR(dev->dev, "failed to get interconnect path: %d\n", ret);
			goto fail;
		}
		a2xx_gpu->icc_path = NULL;
	}

	/*
	 * Set initial interconnect bandwidth to max (avg = peak), matching
	 * legacy webOS grp3d_max_vectors. Adjusted during runtime PM and
	 * devfreq scaling.
	 */
	if (a2xx_gpu->icc_path) {
		u32 bw = a2xx_icc_bw_for_freq(gpu->fast_rate);

		icc_set_bw(a2xx_gpu->icc_path, bw, bw);
	}

	if (adreno_is_a20x(adreno_gpu))
		adreno_gpu->registers = a200_registers;
	else if (adreno_is_a225(adreno_gpu))
		adreno_gpu->registers = a225_registers;
	else
		adreno_gpu->registers = a220_registers;

	return gpu;

fail:
	if (a2xx_gpu)
		a2xx_destroy(&a2xx_gpu->base.base);

	return ERR_PTR(ret);
}
