ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
obj-y := icm42607_accel.o
obj-y += icm42607_share.o
obj-y += icm42607_share_interface.o
