// Ghidra script to export decompiled functions to a file
// @category Export

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import java.io.FileWriter;
import java.io.PrintWriter;

public class ExportDecompiled extends GhidraScript {
    @Override
    public void run() throws Exception {
        String outputPath = getScriptArgs()[0];
        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);
        
        PrintWriter writer = new PrintWriter(new FileWriter(outputPath));
        writer.println("// Decompiled from: " + currentProgram.getName());
        writer.println("// Generated by Ghidra\n");
        
        FunctionIterator funcs = currentProgram.getFunctionManager().getFunctions(true);
        int count = 0;
        while (funcs.hasNext() && !monitor.isCancelled()) {
            Function func = funcs.next();
            DecompileResults results = decomp.decompileFunction(func, 30, monitor);
            if (results.decompileCompleted()) {
                String code = results.getDecompiledFunction().getC();
                writer.println("\n// Function: " + func.getName() + " @ " + func.getEntryPoint());
                writer.println(code);
                count++;
            }
            if (count % 100 == 0) {
                println("Decompiled " + count + " functions...");
            }
        }
        writer.close();
        decomp.dispose();
        println("Exported " + count + " functions to " + outputPath);
    }
}
