#!/bin/bash
#
# Audio Test Script for HP TouchPad
# Deploys firmware, tools, configures mixer, and tests playback
#
# Usage: ./scripts/test-audio.sh [OPTIONS]
#
# Options:
#   --skip-transfer-firmware  Skip firmware transfer (Q6, WM8958)
#   --skip-transfer-audio     Skip audio file transfer (test WAV files)
#   --skip-transfer           Skip all transfers (equivalent to both above)
#   --dump-regs               Dump codec registers and exit
#   --dapm                    Show DAPM widget states and exit
#   --simple                  (Default on current mainline DT.) Direct AIF1
#                             playback via the wm8994 codec without Q6 DSP.
#   --with-q6                 Full Q6 LPASS pipeline path. ONLY useful when the
#                             DT exposes a Q6/LPASS sound-card with SEC_MI2S_RX
#                             routes — this is NOT the case on the current
#                             tenderloin mainline (apq8060-lpaif-sndcard), so
#                             this mode currently no-ops or fails. Kept for
#                             future Q6 work.
#
# Requirements:
# - Device accessible at 172.16.42.2 via USB network
# - HTTP server files in /tmp on host (or use --skip-transfer if already deployed)
#

set -e

DEVICE_IP="172.16.42.2"
SSH_PORT="22"
TIMEOUT=10
# Where to stage files on the device. /tmp on luneos is a 477 MB tmpfs but
# gets filled by bandwidth-test artifacts (dl.bin etc.); /var/tmp is a
# separate tmpfs with the same size and stays clean. Override via env.
REMOTE_TMP="${REMOTE_TMP:-/var/tmp}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_step() {
    echo -e "${GREEN}[STEP]${NC} $1"
}

log_info() {
    echo -e "${YELLOW}[INFO]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_result() {
    echo -e "${GREEN}[RESULT]${NC} $1"
}

# Run command on device via SSH
run_on_device() {
    local cmd="$1"
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=$TIMEOUT -p $SSH_PORT root@$DEVICE_IP "$cmd" 2>/dev/null
}

# Transfer file to device via SCP
scp_to_device() {
    local src="$1"
    local dst="$2"
    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $SSH_PORT "$src" root@$DEVICE_IP:"$dst" 2>/dev/null
}

# Check device connectivity
check_device() {
    log_step "Checking device connectivity..."
    if timeout 3 bash -c "echo > /dev/tcp/$DEVICE_IP/$SSH_PORT" 2>/dev/null; then
        log_info "Device is reachable at $DEVICE_IP (SSH port $SSH_PORT)"
        return 0
    else
        log_error "Cannot connect to device at $DEVICE_IP port $SSH_PORT"
        return 1
    fi
}

# Path resolution — find the repo root so we can reach scripts/audio-samples/
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
SAMPLES_DIR="$REPO_ROOT/scripts/audio-samples"

# Generate the WAV samples in scripts/audio-samples/ if any are missing.
# This is the inline tone generator — no host sox/ffmpeg dependency.
#
# PYTHON GEN BEGIN — keep this block parseable for re-run via:
#   python3 -c "$(sed -n '/PYTHON GEN BEGIN/,/PYTHON GEN END/p' scripts/test-audio.sh)"
generate_samples_if_missing() {
    local need=0
    for f in sine-440hz-1s.wav stereo-1khz-440hz-1s.wav sweep-200-2000hz-500ms.wav; do
        [ -f "$SAMPLES_DIR/$f" ] || need=1
    done
    [ $need -eq 0 ] && return 0

    log_info "Generating missing test WAV samples in $SAMPLES_DIR ..."
    mkdir -p "$SAMPLES_DIR"
    OUT_DIR="$SAMPLES_DIR" python3 - <<'PYEOF'
import math, struct, wave, os
OUT_DIR = os.environ.get("OUT_DIR", "scripts/audio-samples")
SR = 48000
AMP = 23000  # -3 dBFS
def wavout(path, dur, fn_l, fn_r):
    with wave.open(path, "wb") as w:
        w.setnchannels(2); w.setsampwidth(2); w.setframerate(SR)
        for n in range(int(SR*dur)):
            t = n / SR
            w.writeframesraw(struct.pack("<hh", fn_l(t), fn_r(t)))
wavout(f"{OUT_DIR}/sine-440hz-1s.wav", 1.0,
       lambda t: int(AMP*math.sin(2*math.pi*440*t)),
       lambda t: int(AMP*math.sin(2*math.pi*440*t)))
wavout(f"{OUT_DIR}/stereo-1khz-440hz-1s.wav", 1.0,
       lambda t: int(AMP*math.sin(2*math.pi*1000*t)),
       lambda t: int(AMP*math.sin(2*math.pi*440*t)))
def sweep(t):
    f_start, f_end, dur = 200, 2000, 0.5
    phase = 2*math.pi*(f_start*t + 0.5*(f_end - f_start)*t*t/dur)
    return int(AMP * math.sin(phase))
wavout(f"{OUT_DIR}/sweep-200-2000hz-500ms.wav", 0.5, sweep, sweep)
PYEOF
}
# PYTHON GEN END

# Prepare host files
prepare_host_files() {
    log_step "Preparing host files..."

    # Make sure samples exist locally — they live in the repo at
    # scripts/audio-samples/ and are regenerated by Python if missing.
    generate_samples_if_missing

    log_info "Samples available:"
    ls -la "$SAMPLES_DIR"/*.wav 2>/dev/null || true
}

# Transfer firmware files to device via SCP
transfer_firmware() {
    log_step "Transferring firmware to device via SCP..."

    # Transfer Q6 firmware
    if [ -f /tmp/q6-firmware.tar.gz ]; then
        log_info "Transferring Q6 firmware..."
        scp_to_device /tmp/q6-firmware.tar.gz /tmp/
        run_on_device "cd /tmp && tar xzf q6-firmware.tar.gz && ls q6.mdt"
    fi

    # Transfer WM8958 firmware (optional)
    if [ -f /tmp/wm8958-firmware.tar.gz ]; then
        log_info "Transferring WM8958 firmware..."
        scp_to_device /tmp/wm8958-firmware.tar.gz /tmp/
        run_on_device "cd /tmp && tar xzf wm8958-firmware.tar.gz 2>/dev/null" || true
    fi

    # Transfer TinyALSA tools
    if [ -f /tmp/tinyplay ]; then
        log_info "Transferring tinyplay..."
        scp_to_device /tmp/tinyplay /tmp/
        run_on_device "chmod +x /tmp/tinyplay"
    fi

    if [ -f /tmp/tinymix ]; then
        log_info "Transferring tinymix..."
        scp_to_device /tmp/tinymix /tmp/
        run_on_device "chmod +x /tmp/tinymix"
    fi
}

# Transfer audio sample files to device via SCP
transfer_audio_files() {
    log_step "Transferring audio sample files to $REMOTE_TMP via SCP..."

    run_on_device "mkdir -p $REMOTE_TMP"
    local avail=$(run_on_device "df -P $REMOTE_TMP | awk 'NR==2{print \$4}'")
    log_info "Device $REMOTE_TMP available: ${avail} kB"

    for f in sine-440hz-1s.wav stereo-1khz-440hz-1s.wav sweep-200-2000hz-500ms.wav; do
        if [ -f "$SAMPLES_DIR/$f" ]; then
            log_info "Transferring $f..."
            scp_to_device "$SAMPLES_DIR/$f" "$REMOTE_TMP/"
        else
            log_error "Missing sample: $SAMPLES_DIR/$f"
        fi
    done

    log_info "Verifying audio file transfers..."
    run_on_device "ls -la $REMOTE_TMP/sine-440hz-1s.wav $REMOTE_TMP/stereo-1khz-440hz-1s.wav $REMOTE_TMP/sweep-200-2000hz-500ms.wav 2>/dev/null" || true
}

# Deploy firmware to /lib/firmware
deploy_firmware() {
    log_step "Deploying firmware to /lib/firmware..."

    run_on_device "mkdir -p /lib/firmware && cp /tmp/q6.* /lib/firmware/"

    # WM8958 firmware (optional)
    run_on_device "cp /tmp/wm8958*.wfw /lib/firmware/ 2>/dev/null || true"

    log_info "Firmware deployed:"
    run_on_device "ls /lib/firmware/"
}

# Start LPASS
start_lpass() {
    log_step "Starting LPASS (Q6 DSP)..."

    local state=$(run_on_device "cat /sys/class/remoteproc/remoteproc0/state")
    if echo "$state" | grep -q "running"; then
        log_info "LPASS already running"
        return 0
    fi

    run_on_device "echo start > /sys/class/remoteproc/remoteproc0/state"
    sleep 2

    state=$(run_on_device "cat /sys/class/remoteproc/remoteproc0/state")
    if echo "$state" | grep -q "running"; then
        log_result "LPASS started successfully"
    else
        log_error "LPASS failed to start: $state"
        return 1
    fi
}

# Check sound card
check_sound_card() {
    log_step "Checking sound card..."

    local cards=$(run_on_device "cat /proc/asound/cards")
    echo "$cards"

    if echo "$cards" | grep -q "HPTouchPad"; then
        log_result "Sound card detected: HP TouchPad"
    else
        log_error "Sound card not detected"
        return 1
    fi
}

# Configure mixer routing
configure_mixer() {
    log_step "Configuring audio mixer routing..."

    # Enable LPASS to codec routing (Q6 DSP -> Secondary MI2S -> Codec)
    # Note: DT uses SECONDARY_MI2S for the codec link, so we need SEC_MI2S_RX
    log_info "Enabling SEC_MI2S_RX Audio Mixer..."
    run_on_device "cd /tmp && ./tinymix set 'SEC_MI2S_RX Audio Mixer MultiMedia1' 1"

    # Enable DAC paths (AIF1 -> DAC1)
    log_info "Enabling DAC mixer paths..."
    run_on_device "cd /tmp && ./tinymix set 'DAC1L Mixer AIF1.1 Switch' 1"
    run_on_device "cd /tmp && ./tinymix set 'DAC1R Mixer AIF1.1 Switch' 1"
    run_on_device "cd /tmp && ./tinymix set 'DAC1 Switch' 1 1"  # Both channels!

    # Enable output mixers (DAC -> Output Mixer)
    log_info "Enabling output mixers..."
    run_on_device "cd /tmp && ./tinymix set 'Left Output Mixer DAC Switch' 1"
    run_on_device "cd /tmp && ./tinymix set 'Right Output Mixer DAC Switch' 1"

    # Enable LINEOUT paths (Output Mixer -> Line Mixer -> LINEOUT -> External Amp)
    # NOTE: TouchPad speakers use LINEOUT connected to external Class-D amplifier
    # SPKOUT (internal Class-D) is NOT connected on this board.
    # Evidence: webOS msm8x60.c DAPM routes use LINEOUT, marks SPKOUT as NC.
    log_info "Enabling LINEOUT mixer paths..."
    run_on_device "cd /tmp && ./tinymix set 'MIXOUTL MIXINL Volume' 1" 2>/dev/null || true
    run_on_device "cd /tmp && ./tinymix set 'MIXOUTR MIXINR Volume' 1" 2>/dev/null || true

    # Set volumes to maximum
    log_info "Setting volumes..."
    run_on_device "cd /tmp && ./tinymix set 'LINEOUT1 Volume' 1" 2>/dev/null || true
    run_on_device "cd /tmp && ./tinymix set 'LINEOUT2 Volume' 1" 2>/dev/null || true
    run_on_device "cd /tmp && ./tinymix set 'Output Volume' 63 63" 2>/dev/null || true
    run_on_device "cd /tmp && ./tinymix set 'AIF1DAC1 Volume' 96 96"
    run_on_device "cd /tmp && ./tinymix set 'DAC1 Volume' 96 96"

    log_result "Mixer configured for LINEOUT path"
}

# Test audio playback
test_playback() {
    log_step "Testing audio playback..."

    # Use default buffer parameters - large buffers (-p 16384) fail hw_params constraints

    # Dump registers before playback
    dump_codec_registers "Codec registers BEFORE playback"

    # Check DAPM widget states before playback
    check_dapm_widgets

    log_info "Playing notification_48k.wav (short, 48kHz)..."
    local result=$(run_on_device "cd /tmp && ./tinyplay notification_48k.wav 2>&1")
    echo "$result"

    if echo "$result" | grep -q "Played.*bytes"; then
        log_result "Notification playback completed"
    fi

    sleep 1

    # Start register monitor before longer playback
    start_register_monitor

    sleep 1

    log_info "Playing phone_48k.wav (long, 48kHz)..."
    result=$(run_on_device "cd /tmp && ./tinyplay phone_48k.wav 2>&1")
    echo "$result"

    # Wait for monitor to finish collecting data
    sleep 2

    if echo "$result" | grep -q "error\|Error\|cannot"; then
        log_error "Playback encountered errors"

        # Get dmesg errors
        log_info "Checking kernel log for errors..."
        run_on_device "dmesg | grep -i 'error\|asm\|afe' | tail -10"
    else
        log_result "Phone playback completed"
    fi

    # Show register monitoring results
    show_register_monitor_results

    # Dump registers after playback
    dump_codec_registers "Codec registers AFTER playback"

    # Check DAPM widget states after playback
    check_dapm_widgets
}

# Dump key WM8958 codec registers
dump_codec_registers() {
    local label="${1:-Codec Register Dump}"
    log_step "$label"

    # Path to regmap debugfs
    local REGMAP="/sys/kernel/debug/regmap/wm8994/registers"

    run_on_device "cat <<'SCRIPT' > /tmp/dump_regs.sh
#!/bin/sh
REGMAP='/sys/kernel/debug/regmap/1-001a/registers'
if [ ! -f \"\$REGMAP\" ]; then
    echo 'Regmap not available'
    exit 1
fi

# Read all registers once
REGS=\$(cat \$REGMAP)

# Function to get register value
get_reg() {
    echo \"\$REGS\" | grep -i \"^\$1:\" | awk '{print \$2}'
}

echo '=== Power Management ==='
printf 'PM1 (0x01):     0x%s  (VMID, bias, outputs)\\n' \"\$(get_reg 1)\"
printf 'PM3 (0x03):     0x%s  (mixers, spk drivers)\\n' \"\$(get_reg 3)\"
printf 'PM5 (0x05):     0x%s  (DAC enables)\\n' \"\$(get_reg 5)\"

echo ''
echo '=== Output Path (LINEOUT) ==='
printf 'Out Mixer1 (0x2d):    0x%s  (left output mixer, bit0=DAC)\\n' \"\$(get_reg 2d)\"
printf 'Out Mixer2 (0x2e):    0x%s  (right output mixer, bit0=DAC)\\n' \"\$(get_reg 2e)\"
printf 'Line Mixer1 (0x34):   0x%s  (MIXOUT->LINEOUT1, bit6=ena)\\n' \"\$(get_reg 34)\"
printf 'Line Mixer2 (0x35):   0x%s  (MIXOUT->LINEOUT2, bit6=ena)\\n' \"\$(get_reg 35)\"
printf 'LINEOUT1 Vol (0x1e):  0x%s  (volume/enable)\\n' \"\$(get_reg 1e)\"
printf 'LINEOUT2 Vol (0x1f):  0x%s  (volume/enable)\\n' \"\$(get_reg 1f)\"

echo ''
echo '=== DAC/AIF Path ==='
printf 'DAC1L Mixer (0x601):  0x%s  (AIF->DAC1L select)\\n' \"\$(get_reg 601)\"
printf 'DAC1R Mixer (0x602):  0x%s  (AIF->DAC1R select)\\n' \"\$(get_reg 602)\"

echo ''
echo '=== Clocking ==='
printf 'AIF1CLK (0x200):      0x%s  (AIF1 clock source)\\n' \"\$(get_reg 200)\"
printf 'AIF1 Rate (0x210):    0x%s  (sample rate)\\n' \"\$(get_reg 210)\"
printf 'FLL1 Ctrl1 (0x220):   0x%s  (FLL enable)\\n' \"\$(get_reg 220)\"
printf 'FLL1 Ctrl5 (0x224):   0x%s  (FLL source)\\n' \"\$(get_reg 224)\"

echo ''
echo '=== Status ==='
printf 'Int Status2 (0x731):  0x%s  (FLL lock: bit5=1 is locked)\\n' \"\$(get_reg 731)\"
printf 'GPIO1 (0x700):        0x%s  (ext amp ctrl: 0x41=enabled)\\n' \"\$(get_reg 700)\"

echo ''
echo '=== Volume/Mute (check unmuted) ==='
printf 'AIF1DAC1 Filt (0x420): 0x%s  (bit9=mute, 0=unmuted)\\n' \"\$(get_reg 420)\"
printf 'AIF1DAC1L Vol (0x402): 0x%s  (bit9=0 unmuted)\\n' \"\$(get_reg 402)\"
printf 'AIF1DAC1R Vol (0x403): 0x%s  (bit9=0 unmuted)\\n' \"\$(get_reg 403)\"
printf 'DAC1L Vol (0x610):     0x%s  (bit9=0 unmuted)\\n' \"\$(get_reg 610)\"
printf 'DAC1R Vol (0x611):     0x%s  (bit9=0 unmuted)\\n' \"\$(get_reg 611)\"
SCRIPT
chmod +x /tmp/dump_regs.sh
/tmp/dump_regs.sh"
}

# Monitor registers during playback (runs in background on device)
start_register_monitor() {
    log_info "Starting register monitor in background..."

    run_on_device "cat <<'SCRIPT' > /tmp/monitor_regs.sh
#!/bin/sh
REGMAP='/sys/kernel/debug/regmap/1-001a/registers'
OUTFILE='/tmp/reg_monitor.log'
echo 'Register Monitor Started' > \$OUTFILE
echo '========================' >> \$OUTFILE

# Monitor key registers every 0.5 seconds for 10 seconds
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
    REGS=\$(cat \$REGMAP 2>/dev/null)
    if [ -z \"\$REGS\" ]; then
        echo 'Regmap read failed' >> \$OUTFILE
        break
    fi

    # Extract key registers for LINEOUT path
    PM1=\$(echo \"\$REGS\" | grep -i '^1:' | awk '{print \$2}')
    PM3=\$(echo \"\$REGS\" | grep -i '^3:' | awk '{print \$2}')
    PM5=\$(echo \"\$REGS\" | grep -i '^5:' | awk '{print \$2}')
    FLL=\$(echo \"\$REGS\" | grep -i '^731:' | awk '{print \$2}')
    DAC1L=\$(echo \"\$REGS\" | grep -i '^601:' | awk '{print \$2}')
    GPIO=\$(echo \"\$REGS\" | grep -i '^700:' | awk '{print \$2}')
    LINEMIX1=\$(echo \"\$REGS\" | grep -i '^34:' | awk '{print \$2}')
    AIF1FILT=\$(echo \"\$REGS\" | grep -i '^420:' | awk '{print \$2}')

    echo \"[\$(date +%H:%M:%S.\$((i*50)))] PM1=\$PM1 PM3=\$PM3 PM5=\$PM5 FLL=\$FLL DAC601=\$DAC1L LINEMIX=\$LINEMIX1 AIF420=\$AIF1FILT GPIO=\$GPIO\" >> \$OUTFILE
    sleep 0.5
done
echo 'Monitor Complete' >> \$OUTFILE
SCRIPT
chmod +x /tmp/monitor_regs.sh
nohup /tmp/monitor_regs.sh > /dev/null 2>&1 &
echo \$!"
}

# Show register monitor results
show_register_monitor_results() {
    log_step "Register monitor results:"
    run_on_device "cat /tmp/reg_monitor.log 2>/dev/null || echo 'No monitor log found'"
}

# Check DAPM widget states
check_dapm_widgets() {
    log_step "DAPM widget states..."

    run_on_device "cat <<'SCRIPT' > /tmp/check_dapm.sh
#!/bin/sh
# ASoC card debugfs path matches the truncated card name from
# /proc/asound/cards (kernel limit: 15 chars). DT card-name is
# 'HP-TouchPad-LPAIF' which the codec driver truncates to
# 'HP-TouchPad-LPA'. Verify with: ls /sys/kernel/debug/asoc/
DAPM_PATH='/sys/kernel/debug/asoc/HP-TouchPad-LPAIF/wm8994-codec/dapm'
[ -d \"\$DAPM_PATH\" ] || DAPM_PATH='/sys/kernel/debug/asoc/HP-TouchPad-LPA/wm8994-codec/dapm'
if [ ! -d \"\$DAPM_PATH\" ]; then
    echo 'DAPM debugfs not available'
    exit 1
fi

echo '=== Clock Widgets ==='
for w in AIF1CLK CLK_SYS; do
    state=\$(cat \"\$DAPM_PATH/\$w\" 2>/dev/null | head -1)
    printf '%-20s: %s\\n' \"\$w\" \"\$state\"
done

echo ''
echo '=== AIF/DAC Path Widgets ==='
for w in 'AIF1DAC1L' 'AIF1DAC1R' 'DAC1L Mixer' 'DAC1R Mixer' 'DAC1L' 'DAC1R'; do
    state=\$(cat \"\$DAPM_PATH/\$w\" 2>/dev/null | head -1)
    printf '%-20s: %s\\n' \"\$w\" \"\$state\"
done

echo ''
echo '=== Output Mixer/PGA Widgets ==='
for w in 'Left Output Mixer' 'Right Output Mixer' 'Left Output PGA' 'Right Output PGA'; do
    state=\$(cat \"\$DAPM_PATH/\$w\" 2>/dev/null | head -1)
    printf '%-20s: %s\\n' \"\$w\" \"\$state\"
done

echo ''
echo '=== LINEOUT Widgets (speakers via external amp) ==='
for w in 'LINEOUT1P' 'LINEOUT1N' 'LINEOUT2P' 'LINEOUT2N' 'LINEOUT1P Driver' 'LINEOUT1N Driver' 'LINEOUT2P Driver' 'LINEOUT2N Driver'; do
    state=\$(cat \"\$DAPM_PATH/\$w\" 2>/dev/null | head -1)
    printf '%-20s: %s\\n' \"\$w\" \"\$state\"
done
SCRIPT
chmod +x /tmp/check_dapm.sh
/tmp/check_dapm.sh"
}

# Configure mixer for simple direct playback (no Q6 DSP)
#
# Mainline ALSA path (verified against alsa-utils 1.2.11 on luneos):
#   AIF1 -> DAC1 -> Left/Right Output Mixer -> MIXOUTL/R
#        -> LINEOUT1[NP] / LINEOUT2[NP] (per-rail) -> ext TPA2016 Class-D amp
#
# IMPORTANT: On mainline the WM8994 codec driver splits the MIXOUT -> LINEOUT
# routing into FOUR per-rail switches (one for each N/P pin on each LINEOUT
# pair), NOT a single "LINEOUT[12] Mixer Output Switch" control as on webOS.
# A previous version of this script tried "Left Line Output Switch" and
# "Right Line Output Switch" which do not exist. Both swallowed by `|| true`.
#
# Control names verified by:
#   ssh root@172.16.42.2 'amixer -c 0 contents | grep -E "name="'
configure_mixer_simple() {
    log_step "Configuring audio mixer for simple direct playback..."

    # Helper: set a control by name using amixer cset.
    #
    # We MUST use `cset name=...` not `sset` here: alsa-utils 1.2.11 amixer's
    # `sset` only operates on the "simple control" namespace, which is a
    # curated subset (Master Volume, Capture, etc.) and DOES NOT expose any
    # of the WM8994 routing/switch controls we need. Trying `sset` returns
    # "Unable to find simple control" for every line we care about.
    #
    # `cset name=` operates on the full element-level control namespace, which
    # is exactly where the codec switches live. cset by numid would also work
    # but numids are dynamic per build, so we key by name.
    run_on_device "mkdir -p $REMOTE_TMP && cat > $REMOTE_TMP/aset.sh <<'EOF'
#!/bin/sh
# usage: aset.sh <name> <value>
name=\"\$1\"; val=\"\$2\"
amixer -c 0 cset name=\"\$name\" \"\$val\" >/dev/null 2>&1 && exit 0
echo \"WARN: cset failed for '\$name' <- '\$val'\" >&2
exit 1
EOF
chmod +x $REMOTE_TMP/aset.sh"

    # Stage 1: AIF1 -> DAC1 routing
    log_info "Enabling AIF1 -> DAC1 routing..."
    run_on_device "$REMOTE_TMP/aset.sh 'DAC1L Mixer AIF1.1 Switch' on"
    run_on_device "$REMOTE_TMP/aset.sh 'DAC1R Mixer AIF1.1 Switch' on"
    run_on_device "$REMOTE_TMP/aset.sh 'DAC1 Switch'              'on,on'"

    # Stage 2: DAC1 -> Output Mixer
    log_info "Enabling Output Mixer DAC path..."
    run_on_device "$REMOTE_TMP/aset.sh 'Left Output Mixer DAC Switch'  on"
    run_on_device "$REMOTE_TMP/aset.sh 'Right Output Mixer DAC Switch' on"

    # Stage 3: MIXOUT -> LINEOUT (per-rail Left/Right Output -> LINEOUT[12][NP])
    # These are the four switches the OLD version was missing.
    log_info "Enabling MIXOUT -> LINEOUT routing (per-rail)..."
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT1N Mixer Left Output Switch'  on"
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT1P Mixer Left Output Switch'  on"
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT2N Mixer Right Output Switch' on"
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT2P Mixer Right Output Switch' on"

    # Stage 4: LINEOUT driver enables (unmute the final pin drivers)
    log_info "Enabling LINEOUT pin drivers..."
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT1N Switch' on"
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT1P Switch' on"
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT2N Switch' on"
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT2P Switch' on"

    # Volumes
    log_info "Setting volumes..."
    run_on_device "$REMOTE_TMP/aset.sh 'AIF1DAC1 Volume' '96,96'"
    run_on_device "$REMOTE_TMP/aset.sh 'DAC1 Volume'     '96,96'"
    run_on_device "$REMOTE_TMP/aset.sh 'Output Volume'   '63,63'"
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT1 Volume' 1"
    run_on_device "$REMOTE_TMP/aset.sh 'LINEOUT2 Volume' 1"

    log_result "Simple mixer configured for direct LINEOUT playback"
}

# Test simple audio playback (no Q6 DSP)
test_playback_simple() {
    log_step "Testing simple audio playback (direct, no Q6 DSP)..."

    if ! run_on_device "which aplay" >/dev/null 2>&1; then
        log_error "aplay not present on device (expected alsa-utils-aplay)"
        return 1
    fi
    log_info "Using aplay for playback..."

    # Play each sample. We don't bail on the first failure — we want to know
    # which patterns produced sound and which didn't, so the user can
    # correlate audible vs. silent vs. erroring.
    local test_files="$REMOTE_TMP/sine-440hz-1s.wav $REMOTE_TMP/stereo-1khz-440hz-1s.wav $REMOTE_TMP/sweep-200-2000hz-500ms.wav"
    local any_ok=0
    for f in $test_files; do
        if ! run_on_device "test -f $f"; then
            log_info "skip $f — not staged on device"
            continue
        fi
        log_info "Playing $f via plughw:0,0 ..."
        # aplay -D plughw:0,0 forces direct hw access via plug (so SR/format
        # conversion is allowed) — bypasses pulseaudio entirely. If pulse is
        # holding the device, this will fail with EBUSY and we'll see it.
        local result=$(run_on_device "aplay -D plughw:0,0 $f 2>&1")
        echo "$result" | sed 's/^/  /'
        if echo "$result" | grep -qiE "error|fail|cannot|busy"; then
            log_error "  aplay reported a problem on $(basename $f)"
        else
            log_result "  aplay finished on $(basename $f)"
            any_ok=1
        fi
        # short gap so DAPM can settle between streams
        sleep 0.5
    done

    if [ $any_ok -eq 0 ]; then
        log_error "All playbacks errored. Check 'dmesg | tail -40' for ASoC/LPASS state."
        return 1
    fi
}

# Simple mode main function
run_simple_test() {
    log_step "Running simple audio test (direct playback, no Q6 DSP)..."

    # Transfer audio files if not skipped (firmware not needed for simple mode)
    if [ $SKIP_TRANSFER_AUDIO -eq 0 ]; then
        prepare_host_files
        transfer_audio_files
    fi

    check_sound_card || exit 1

    # Show current PCM devices
    log_info "Available PCM devices:"
    run_on_device "cat /proc/asound/pcm"

    # Enable amplifier
    enable_class_d_amplifier

    # Configure mixer
    configure_mixer_simple

    # Test playback
    test_playback_simple

    # Show status
    log_info "Checking for audio errors in dmesg..."
    run_on_device "dmesg | grep -iE 'wm8994|asoc|error' | tail -10" || true

    log_result "Simple audio test complete"
}

# Check dmesg for ASM/AFE status
check_dmesg() {
    log_step "Checking kernel messages..."

    log_info "Legacy protocol status:"
    run_on_device "dmesg | grep -i 'legacy' | tail -5"

    log_info "Recent audio errors:"
    run_on_device "dmesg | grep -iE 'error.*0x|returned error|asm|afe' | tail -10"

    log_info "APR header debug (if available):"
    run_on_device "dmesg | grep -i 'src_port\|dest_port\|open_write' | tail -5"
}

# Enable Class-D amplifier via PM8901 MPP3 GPIO
# The external Class-D amplifier (TPA2016) is controlled by PM8901 MPP3
# This GPIO must be set HIGH to enable speaker output
enable_class_d_amplifier() {
    log_step "Enabling Class-D amplifier (PM8901 MPP3)..."

    # Find the PM8901 MPP GPIO chip base
    # gpiochip with label containing "pmic8901:mpps" is what we need
    local gpio_base=$(run_on_device "for chip in /sys/class/gpio/gpiochip*; do
        label=\$(cat \$chip/label 2>/dev/null)
        if echo \"\$label\" | grep -q 'pmic8901.*mpps'; then
            cat \$chip/base
            break
        fi
    done")

    if [ -z "$gpio_base" ]; then
        log_error "Could not find PM8901 MPP GPIO chip"
        return 1
    fi

    # MPP3 is at base + 2 (MPP1=base+0, MPP2=base+1, MPP3=base+2)
    local gpio_num=$((gpio_base + 2))
    log_info "PM8901 MPP3 is GPIO $gpio_num (base=$gpio_base)"

    # Export GPIO if not already exported
    run_on_device "echo $gpio_num > /sys/class/gpio/export 2>/dev/null || true"

    # Set direction to output and value to HIGH
    run_on_device "echo out > /sys/class/gpio/gpio${gpio_num}/direction 2>/dev/null"
    run_on_device "echo 1 > /sys/class/gpio/gpio${gpio_num}/value"

    # Verify
    local value=$(run_on_device "cat /sys/class/gpio/gpio${gpio_num}/value 2>/dev/null")
    if [ "$value" = "1" ]; then
        log_result "Class-D amplifier GPIO $gpio_num set HIGH"
    else
        log_error "Failed to set Class-D amplifier GPIO"
        return 1
    fi

    # Also show the GPIO debug state for confirmation
    log_info "PM8901 MPP GPIO states:"
    run_on_device "cat /sys/kernel/debug/gpio 2>/dev/null | grep -A5 'pmic8901:mpps'"
}

# Main
main() {
    echo "=============================================="
    echo "  HP TouchPad Audio Test Script"
    echo "=============================================="
    echo ""

    SKIP_TRANSFER_FIRMWARE=0
    SKIP_TRANSFER_AUDIO=0
    DUMP_REGS_ONLY=0
    DAPM_ONLY=0
    # Default to simple mode — the current mainline DT (apq8060-lpaif-sndcard)
    # routes AIF1 directly from LPAIF CPU DAI to the WM8994 codec with no Q6
    # DSP in between. Override with --with-q6 if you have a DT variant that
    # actually exposes Q6 LPASS.
    SIMPLE_MODE=1

    # Parse arguments
    for arg in "$@"; do
        case $arg in
            --skip-transfer)
                SKIP_TRANSFER_FIRMWARE=1
                SKIP_TRANSFER_AUDIO=1
                log_info "Skipping all file transfers"
                ;;
            --skip-transfer-firmware)
                SKIP_TRANSFER_FIRMWARE=1
                log_info "Skipping firmware transfer"
                ;;
            --skip-transfer-audio)
                SKIP_TRANSFER_AUDIO=1
                log_info "Skipping audio file transfer"
                ;;
            --dump-regs)
                DUMP_REGS_ONLY=1
                log_info "Dump registers mode"
                ;;
            --dapm)
                DAPM_ONLY=1
                log_info "DAPM widgets mode"
                ;;
            --simple)
                SIMPLE_MODE=1
                log_info "Simple mode (direct playback, no Q6 DSP) — default"
                ;;
            --with-q6)
                SIMPLE_MODE=0
                log_info "Full Q6 LPASS mode — only works on Q6-enabled DT variants"
                ;;
        esac
    done

    check_device || exit 1

    # Quick modes for debugging
    if [ $DUMP_REGS_ONLY -eq 1 ]; then
        dump_codec_registers "Current codec register state"
        exit 0
    fi

    if [ $DAPM_ONLY -eq 1 ]; then
        check_dapm_widgets
        exit 0
    fi

    # Simple mode - direct playback without Q6 DSP
    if [ $SIMPLE_MODE -eq 1 ]; then
        run_simple_test
        exit 0
    fi

    # Full test flow (with Q6 DSP)
    if [ $SKIP_TRANSFER_FIRMWARE -eq 0 ] || [ $SKIP_TRANSFER_AUDIO -eq 0 ]; then
        prepare_host_files
    fi
    if [ $SKIP_TRANSFER_FIRMWARE -eq 0 ]; then
        transfer_firmware
    fi
    if [ $SKIP_TRANSFER_AUDIO -eq 0 ]; then
        transfer_audio_files
    fi

    deploy_firmware
    start_lpass
    sleep 2
    check_sound_card || exit 1
    enable_class_d_amplifier
    configure_mixer
    test_playback
    check_dmesg

    echo ""
    echo "=============================================="
    echo "  Test Complete"
    echo "=============================================="
}

main "$@"
