// SPDX-License-Identifier: GPL-2.0-only
/*
 * Palm A6 Battery Controller Driver - register descriptor tables
 *
 * Copyright (C) 2008-2011 Palm, Inc.
 * Copyright (C) 2010 Hewlett-Packard Co.
 *
 * Modernized for device tree and modern kernel APIs
 *
 * This file holds the static a6_register_desc_arr[] register map plus the
 * extra device_attribute entries (a6_diag, validate_cksum) used by the A6
 * battery controller. The table is large and stable; isolating it here keeps
 * the rest of the driver focused on behaviour rather than register layout.
 */

#include <linux/array_size.h>
#include <linux/device.h>
#include <linux/types.h>

#include "a6_internal.h"

/*
 * Note: 16-bit accesses comprising an LSB, MSB register pair must be specified
 * in LSB:MSB order in the corresponding a6_register_desc struct. This is
 * because an a6-fw constraint restricts 16-bit value accesses to MSB-leading
 * only. The a6_i2c_read_reg and the a6_i2c_write_reg functions take the
 * LSB:MSB definition in the a6_register_desc struct and re-orders the i2c txn
 * to read in MSB:LSB order.
 */
struct a6_register_desc a6_register_desc_arr[] = {
	/* interrupt control registers */
	[0] = { .debug_name = "TS2_I2C_INT_MASK_0",
		{{.name = "int_mask0", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_INT_MASK_0}, .num_ids = 1, .ro = 0},
	[1] = { .debug_name = "TS2_I2C_INT_MASK_1",
		{{.name = "int_mask1", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_INT_MASK_1}, .num_ids = 1, .ro = 0},
	[2] = { .debug_name = "TS2_I2C_INT_MASK_2",
		{{.name = "int_mask2", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_INT_MASK_2}, .num_ids = 1, .ro = 0},
	[3] = { .debug_name = "TS2_I2C_INT_MASK_3",
		{{.name = "int_mask3", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_INT_MASK_3}, .num_ids = 1, .ro = 0},
	[4] = { .debug_name = "TS2_I2C_INT_STATUS_0",
		{{.name = "int_status0", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_INT_STATUS_0}, .num_ids = 1, .ro = 0},
	[5] = { .debug_name = "TS2_I2C_INT_STATUS_1",
		{{.name = "int_status1", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_INT_STATUS_1}, .num_ids = 1, .ro = 0},
	[6] = { .debug_name = "TS2_I2C_INT_STATUS_2",
		{{.name = "int_status2", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_INT_STATUS_2}, .num_ids = 1, .ro = 0},
	[7] = { .debug_name = "TS2_I2C_INT_STATUS_3",
		{{.name = "int_status3", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_INT_STATUS_3}, .num_ids = 1, .ro = 0},

	/* battery control registers */
	[8] = { .debug_name = "TS2_I2C_BAT_STATUS",
		{{.name = "status", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.format = format_status,
		.id = {TS2_I2C_BAT_STATUS}, .num_ids = 1, .ro = 1},
	[9] = { .debug_name = "TS2_I2C_BAT_RARC",
		{{.name = "getpercent", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.id = {TS2_I2C_BAT_RARC}, .num_ids = 1, .ro = 1},
	[10] = { .debug_name = "TS2_I2C_BAT_RSRC",
		{{.name = "rsrc", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.id = {TS2_I2C_BAT_RSRC}, .num_ids = 1, .ro = 1},
	[11] = { .debug_name = "TS2_I2C_BAT_AVG_CUR_LSB_MSB",
		{{.name = "getavgcurrent", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.format = format_current,
		.id = {TS2_I2C_BAT_AVG_CUR_LSB, TS2_I2C_BAT_AVG_CUR_MSB},
			.num_ids = 2, .ro = 1},
	[12] = { .debug_name = "TS2_I2C_BAT_TEMP_LSB_MSB",
		{{.name = "gettemp", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.format = format_temp,
		.id = {TS2_I2C_BAT_TEMP_LSB, TS2_I2C_BAT_TEMP_MSB},
			.num_ids = 2, .ro = 1},
	[13] = { .debug_name = "TS2_I2C_BAT_VOLT_LSB_MSB",
		{{.name = "getvoltage", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.format = format_voltage,
		.id = {TS2_I2C_BAT_VOLT_LSB, TS2_I2C_BAT_VOLT_MSB},
			.num_ids = 2, .ro = 1},
	[14] = { .debug_name = "TS2_I2C_BAT_CUR_LSB_MSB",
		{{.name = "getcurrent", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.format = format_current,
		.id = {TS2_I2C_BAT_CUR_LSB, TS2_I2C_BAT_CUR_MSB},
			.num_ids = 2, .ro = 1},
	[15] = { .debug_name = "TS2_I2C_BAT_COULOMB_LSB_MSB",
		{{.name = "getrawcoulomb", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.format = format_rawcoulomb,
		.id = {TS2_I2C_BAT_COULOMB_LSB, TS2_I2C_BAT_COULOMB_MSB},
			.num_ids = 2, .ro = 1},
	[16] = { .debug_name = "TS2_I2C_BAT_AS",
		{{.name = "getage", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.format = format_age,
		.id = {TS2_I2C_BAT_AS}, .num_ids = 1, .ro = 0},
	[17] = { .debug_name = "TS2_I2C_BAT_FULL_LSB_MSB",
		{{.name = "getfull", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.format = format_fullx,
		.id = {TS2_I2C_BAT_FULL_LSB, TS2_I2C_BAT_FULL_MSB},
			.num_ids = 2, .ro = 1},
	[18] = {.debug_name = "TS2_I2C_BAT_FULL40_LSB_MSB",
		{{.name = "getfull40", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.format = format_fullx,
		.id = {TS2_I2C_BAT_FULL40_LSB, TS2_I2C_BAT_FULL40_MSB},
			.num_ids = 2, .ro = 1},
	[19] = {.debug_name = "TS2_I2C_BAT_RSNSP",
		{{.name = "getrsense", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_rsense,
		.id = {TS2_I2C_BAT_RSNSP}, .num_ids = 1, .ro = 1},

	[20] = {.debug_name = "TS2_I2C_BAT_ROMID_0",
		{{.name = "romid_0", .mode = 0444},
		 .show = a6_generic_show, .store = NULL},
		.id = {TS2_I2C_BAT_ROMID_0}, .num_ids = 1, .ro = 1},

	[21] = {.debug_name = "TS2_I2C_BAT_COMMAND_STATUS",
		{{.name = "command_status", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_BAT_COMMAND_STATUS}, .num_ids = 1, .ro = 0},


	[22] = {.debug_name = "TS2_I2C_BAT_TEMP_LOW_LSB_MSB",
		{{.name = "temp_low", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.format = format_temp,
		.r_format = r_format_temp,
		.id = {TS2_I2C_BAT_TEMP_LOW_LSB, TS2_I2C_BAT_TEMP_LOW_MSB},
			.num_ids = 2, .ro = 0},
	[23] = {.debug_name = "TS2_I2C_BAT_TEMP_HIGH_LSB_MSB",
		{{.name = "temp_high", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.format = format_temp,
		.r_format = r_format_temp,
		.id = {TS2_I2C_BAT_TEMP_HIGH_LSB, TS2_I2C_BAT_TEMP_HIGH_MSB},
			.num_ids = 2, .ro = 0},
	[24] = {.debug_name = "TS2_I2C_BAT_VOLT_LOW_LSB_MSB",
		{{.name = "volt_low", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.format = format_voltage,
		.r_format = r_format_voltage,
		.id = {TS2_I2C_BAT_VOLT_LOW_LSB, TS2_I2C_BAT_VOLT_LOW_MSB},
			.num_ids = 2, .ro = 0},
	[25] = {.debug_name = "TS2_I2C_BAT_RARC_CRIT",
		{{.name = "rarc_crit", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_BAT_RARC_CRIT}, .num_ids = 1, .ro = 0},
	[26] = {.debug_name = "TS2_I2C_BAT_RARC_LOW_2",
		{{.name = "rarc_low_2", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_BAT_RARC_LOW_2}, .num_ids = 1, .ro = 0},
	[27] = {.debug_name = "TS2_I2C_BAT_RARC_LOW_1",
		{{.name = "rarc_low_1", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_BAT_RARC_LOW_1}, .num_ids = 1, .ro = 0},
	[28] = {.debug_name = "TS2_I2C_BAT_RAAC_MSB",
		{{.name = "getcoulomb", .mode = 0666},
		 .show = a6_generic_show, .store = a6_generic_store},
		.format = format_coulomb,
		.id = {TS2_I2C_BAT_RAAC_LSB, TS2_I2C_BAT_RAAC_MSB},
			.num_ids = 2, .ro = 0},

	/* puck registers */
	[29] = {.debug_name = "TS2_I2C_ID",
		{{.name = "id", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.id = {TS2_I2C_ID}, .num_ids = 1, .ro = 1},
	[30] = {.debug_name = "TS2_I2C_FLAGS_0",
		{{.name = "puck_priority", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_FLAGS_0}, .num_ids = 1, .ro = 0},
	[31] = {.debug_name = "TS2_I2C_FLAGS_2",
		{{.name = "charger", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_charge_source_status,
		.id = {TS2_I2C_FLAGS_2}, .num_ids = 1, .ro = 1},

	/* enumeration registers */
	[32] = {.debug_name = "VERSION",
		{{.name = "getversion", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_version,
		.id = {	TS2_I2C_ENUM_MFGR_ID_LO, TS2_I2C_ENUM_MFGR_ID_HI,
			TS2_I2C_ENUM_PRODUCT_TYPE_LO, TS2_I2C_ENUM_PRODUCT_TYPE_HI,
			TS2_I2C_ENUM_SERNO_0, TS2_I2C_ENUM_SERNO_1,
			TS2_I2C_ENUM_SERNO_2, TS2_I2C_ENUM_SERNO_3,
			TS2_I2C_ENUM_SERNO_4, TS2_I2C_ENUM_SERNO_5,
			TS2_I2C_ENUM_SERNO_6, TS2_I2C_ENUM_SERNO_7,
			TS2_I2C_ENUM_ASSY_REV, TS2_I2C_ENUM_FW_VER_0,
			TS2_I2C_ENUM_FW_VER_1, TS2_I2C_ENUM_FW_VER_2},
		.num_ids = 16, .ro = 1},

	/* puck registers */
	[33] = {.debug_name = "TS2_I2C_V_OFFSET",
		{{.name = "v_offset", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_v_offset,
		.id = {TS2_I2C_V_OFFSET}, .num_ids = 1, .ro = 0},

	/* self-wake registers */
	[34] = {.debug_name = "TS2_I2C_WAKEUP_PERIOD",
		{{.name = "periodic_wake_bit_params", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_WAKEUP_PERIOD}, .num_ids = 1, .ro = 0},

	/* command registers */
	[35] = {.debug_name = "TS2_I2C_COMMAND",
		{{.name = "command", .mode = 0222},
		.show = NULL, .store = a6_generic_store},
		.id = {TS2_I2C_COMMAND}, .num_ids = 1, .ro = 0},

	/* remote enumeration registers */
	[36] = {.debug_name = "REMOTE_VERSION",
		{{.name = "getremoteversion", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_version,
		.id = {	TS2_I2C_ENUM_REMOTE_MFGR_ID_LO, TS2_I2C_ENUM_REMOTE_MFGR_ID_HI,
			TS2_I2C_ENUM_REMOTE_PRODUCT_TYPE_LO, TS2_I2C_ENUM_REMOTE_PRODUCT_TYPE_HI,
			TS2_I2C_ENUM_REMOTE_SERNO_0, TS2_I2C_ENUM_REMOTE_SERNO_1,
			TS2_I2C_ENUM_REMOTE_SERNO_2, TS2_I2C_ENUM_REMOTE_SERNO_3,
			TS2_I2C_ENUM_REMOTE_SERNO_4, TS2_I2C_ENUM_REMOTE_SERNO_5,
			TS2_I2C_ENUM_REMOTE_SERNO_6, TS2_I2C_ENUM_REMOTE_SERNO_7,
			TS2_I2C_ENUM_REMOTE_ASSY_REV, TS2_I2C_ENUM_REMOTE_FW_VER_0,
			TS2_I2C_ENUM_REMOTE_FW_VER_1, TS2_I2C_ENUM_REMOTE_FW_VER_2},
		.num_ids = 16, .ro = 1},

	/* accessory data registers */
	[37] = {.debug_name = "ACCESSORY_DATA_0",
		{{.name = "acc_data_0", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_0}, .num_ids = 1, .ro = 0},

	[38] = {.debug_name = "ACCESSORY_DATA_1",
		{{.name = "acc_data_1", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_1}, .num_ids = 1, .ro = 0},

	[39] = {.debug_name = "ACCESSORY_DATA_2",
		{{.name = "acc_data_2", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_2}, .num_ids = 1, .ro = 0},

	[40] = {.debug_name = "ACCESSORY_DATA_3",
		{{.name = "acc_data_3", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_3}, .num_ids = 1, .ro = 0},

	[41] = {.debug_name = "ACCESSORY_DATA_4",
		{{.name = "acc_data_4", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_4}, .num_ids = 1, .ro = 0},

	[42] = {.debug_name = "ACCESSORY_DATA_5",
		{{.name = "acc_data_5", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_5}, .num_ids = 1, .ro = 0},

	[43] = {.debug_name = "ACCESSORY_DATA_6",
		{{.name = "acc_data_6", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_6}, .num_ids = 1, .ro = 0},

	[44] = {.debug_name = "ACCESSORY_DATA_7",
		{{.name = "acc_data_7", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_7}, .num_ids = 1, .ro = 0},

	[45] = {.debug_name = "ACCESSORY_DATA_8",
		{{.name = "acc_data_8", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_8}, .num_ids = 1, .ro = 0},

	[46] = {.debug_name = "ACCESSORY_DATA_9",
		{{.name = "acc_data_9", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_9}, .num_ids = 1, .ro = 0},

	[47] = {.debug_name = "ACCESSORY_DATA_10",
		{{.name = "acc_data_10", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_10}, .num_ids = 1, .ro = 0},

	[48] = {.debug_name = "ACCESSORY_DATA_11",
		{{.name = "acc_data_11", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_11}, .num_ids = 1, .ro = 0},

	[49] = {.debug_name = "ACCESSORY_DATA_12",
		{{.name = "acc_data_12", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_12}, .num_ids = 1, .ro = 0},

	/* remote accessory data registers */
	[50] = {.debug_name = "REMOTE_ACCESSORY_DATA_0",
		{{.name = "remote_acc_data_0", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_0}, .num_ids = 1, .ro = 1},

	[51] = {.debug_name = "REMOTE_ACCESSORY_DATA_1",
		{{.name = "remote_acc_data_1", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_1}, .num_ids = 1, .ro = 1},

	[52] = {.debug_name = "REMOTE_ACCESSORY_DATA_2",
		{{.name = "remote_acc_data_2", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_2}, .num_ids = 1, .ro = 1},

	[53] = {.debug_name = "REMOTE_ACCESSORY_DATA_3",
		{{.name = "remote_acc_data_3", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_3}, .num_ids = 1, .ro = 1},

	[54] = {.debug_name = "REMOTE_ACCESSORY_DATA_4",
		{{.name = "remote_acc_data_4", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_4}, .num_ids = 1, .ro = 1},

	[55] = {.debug_name = "REMOTE_ACCESSORY_DATA_5",
		{{.name = "remote_acc_data_5", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_5}, .num_ids = 1, .ro = 1},

	[56] = {.debug_name = "REMOTE_ACCESSORY_DATA_6",
		{{.name = "remote_acc_data_6", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_6}, .num_ids = 1, .ro = 1},

	[57] = {.debug_name = "REMOTE_ACCESSORY_DATA_7",
		{{.name = "remote_acc_data_7", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_7}, .num_ids = 1, .ro = 1},

	[58] = {.debug_name = "REMOTE_ACCESSORY_DATA_8",
		{{.name = "remote_acc_data_8", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_8}, .num_ids = 1, .ro = 1},

	[59] = {.debug_name = "REMOTE_ACCESSORY_DATA_9",
		{{.name = "remote_acc_data_9", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_9}, .num_ids = 1, .ro = 1},

	[60] = {.debug_name = "REMOTE_ACCESSORY_DATA_10",
		{{.name = "remote_acc_data_10", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_10}, .num_ids = 1, .ro = 1},

	[61] = {.debug_name = "REMOTE_ACCESSORY_DATA_11",
		{{.name = "remote_acc_data_11", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_11}, .num_ids = 1, .ro = 1},

	[62] = {.debug_name = "REMOTE_ACCESSORY_DATA_12",
		{{.name = "remote_acc_data_12", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_12}, .num_ids = 1, .ro = 1},

	[63] = {.debug_name = "TS2_I2C_COMM_STATUS",
		{{.name = "get_comm_status", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_comm_status,
		.id = {TS2_I2C_COMM_STATUS}, .num_ids = 1, .ro = 1},

	[64] = {.debug_name = "TS2_I2C_COMM_TXDATA_RXDATA",
		{{.name = "comm_txdata_rx_data", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_comm_status,
		.id = {TS2_I2C_COMM_TXDATA_RXDATA}, .num_ids = 1, .ro = 0},

	[65] = { .debug_name = "TS2_I2C_BAT_SACR_LSB_MSB",
		{{.name = "getsacr", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_rawcoulomb,
		.id = {TS2_I2C_BAT_SACR_LSB, TS2_I2C_BAT_SACR_MSB},
			.num_ids = 2, .ro = 0},

	[66] = { .debug_name = "TS2_I2C_BAT_ASL",
		{{.name = "getasl", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_raw_unsigned,
		.id = {TS2_I2C_BAT_ASL}, .num_ids = 1, .ro = 0},

	[67] = { .debug_name = "TS2_I2C_BAT_AS",
		{{.name = "getrawas", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_raw_unsigned,
		.id = {TS2_I2C_BAT_AS}, .num_ids = 1, .ro = 0},

	[68] = { .debug_name = "TS2_I2C_BAT_FAC_LSB_MSB",
		{{.name = "getfac", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_rawcoulomb,
		.id = {TS2_I2C_BAT_FAC_LSB, TS2_I2C_BAT_FAC_MSB},
			.num_ids = 2, .ro = 0},

	[69] = {.debug_name = "MAX_POWER_AVAILABLE",
		{{.name = "getmaxpoweravail", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_max_power_available,
		.id = { TS2_I2C_ENUM_REMOTE_VNODE_MAX_LO, TS2_I2C_ENUM_REMOTE_VNODE_MAX_HI,
			TS2_I2C_ENUM_REMOTE_INODE_MAX_LO, TS2_I2C_ENUM_REMOTE_INODE_MAX_HI,
			TS2_I2C_ENUM_REMOTE_POWER_MAX},
		.num_ids = 5, .ro = 1},

	[70] = {.debug_name = "TS2_I2C_ENUM_REMOTE_STRUCT_VER",
		{{.name = "remote_struct_ver", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.id = {TS2_I2C_ENUM_REMOTE_STRUCT_VER}, .num_ids = 1, .ro = 1},

	[71] = {.debug_name = "ACCESSORY_DATA_13",
		{{.name = "acc_data_13", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_13}, .num_ids = 1, .ro = 0},

	[72] = {.debug_name = "ACCESSORY_DATA_14",
		{{.name = "acc_data_14", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_14}, .num_ids = 1, .ro = 0},

	[73] = {.debug_name = "ACCESSORY_DATA_15",
		{{.name = "acc_data_15", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_ACCE_15}, .num_ids = 1, .ro = 0},

	[74] = {.debug_name = "REMOTE_ACCESSORY_DATA_13",
		{{.name = "remote_acc_data_13", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_13}, .num_ids = 1, .ro = 1},

	[75] = {.debug_name = "REMOTE_ACCESSORY_DATA_14",
		{{.name = "remote_acc_data_14", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_14}, .num_ids = 1, .ro = 1},

	[76] = {.debug_name = "REMOTE_ACCESSORY_DATA_15",
		{{.name = "remote_acc_data_15", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory,
		.id = {	TS2_I2C_ENUM_REMOTE_ACCE_15}, .num_ids = 1, .ro = 1},

	[77] = {.debug_name = "TS2_I2C_ENUM_MIN_PWM",
		{{.name = "min_pwm", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.id = {	TS2_I2C_ENUM_MIN_PWM}, .num_ids = 1, .ro = 0},

	[78] = {.debug_name = "ACCESSORY_DATA_COMBO",
		{{.name = "acc_data_combo", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.format = format_accessory_combo,
		.id = { TS2_I2C_ENUM_ACCE_0, TS2_I2C_ENUM_ACCE_1, TS2_I2C_ENUM_ACCE_2,
			TS2_I2C_ENUM_ACCE_3, TS2_I2C_ENUM_ACCE_4, TS2_I2C_ENUM_ACCE_5,
			TS2_I2C_ENUM_ACCE_6, TS2_I2C_ENUM_ACCE_7, TS2_I2C_ENUM_ACCE_8,
			TS2_I2C_ENUM_ACCE_9, TS2_I2C_ENUM_ACCE_10, TS2_I2C_ENUM_ACCE_11,
			TS2_I2C_ENUM_ACCE_12, TS2_I2C_ENUM_ACCE_13, TS2_I2C_ENUM_ACCE_14,
			TS2_I2C_ENUM_ACCE_15},
		.num_ids = 16, .ro = 0},

	[79] = {.debug_name = "REMOTE_ACCESSORY_DATA_COMBO",
		{{.name = "remote_acc_data_combo", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_accessory_combo,
		.id = { TS2_I2C_ENUM_REMOTE_ACCE_0, TS2_I2C_ENUM_REMOTE_ACCE_1,
			TS2_I2C_ENUM_REMOTE_ACCE_2, TS2_I2C_ENUM_REMOTE_ACCE_3,
			TS2_I2C_ENUM_REMOTE_ACCE_4, TS2_I2C_ENUM_REMOTE_ACCE_5,
			TS2_I2C_ENUM_REMOTE_ACCE_6, TS2_I2C_ENUM_REMOTE_ACCE_7,
			TS2_I2C_ENUM_REMOTE_ACCE_8, TS2_I2C_ENUM_REMOTE_ACCE_9,
			TS2_I2C_ENUM_REMOTE_ACCE_10, TS2_I2C_ENUM_REMOTE_ACCE_11,
			TS2_I2C_ENUM_REMOTE_ACCE_12, TS2_I2C_ENUM_REMOTE_ACCE_13,
			TS2_I2C_ENUM_REMOTE_ACCE_14, TS2_I2C_ENUM_REMOTE_ACCE_15},
		.num_ids = 16, .ro = 1},

	[80] = {.debug_name = "TS2_I2C_COMMAND_ADDR_LSB_MSB",
		{{.name = "command_addr", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_COMMAND_ADDR_LSB, TS2_I2C_COMMAND_ADDR_MSB},
		.format = format_u16_hex,
		.num_ids = 2, .ro = 0},
	[81] = {.debug_name = "TS2_I2C_COMMAND_DATA_LSB_MSB",
		{{.name = "command_data", .mode = 0666},
		.show = a6_generic_show, .store = a6_generic_store},
		.id = {TS2_I2C_COMMAND_DATA_LSB, TS2_I2C_COMMAND_DATA_MSB},
		.format = format_u16_hex,
		.num_ids = 2, .ro = 0},

	[82] = {.debug_name = "REMOTE_MFGRID_V1",
		{{.name = "remote_mfgrid_v1", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_u16_hex,
		.id = { TS2_I2C_ENUM_REMOTE_MFGR_ID_LO_V1,
			TS2_I2C_ENUM_REMOTE_MFGR_ID_HI_V1},
		.num_ids = 2, .ro = 1},
	[83] = {.debug_name = "REMOTE_MFGRID_V2",
		{{.name = "remote_mfgrid_v2", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_u16_hex,
		.id = { TS2_I2C_ENUM_REMOTE_MFGR_ID_LO,
			TS2_I2C_ENUM_REMOTE_MFGR_ID_HI},
		.num_ids = 2, .ro = 1},
	[84] = {.debug_name = "REMOTE_PRODUCTID_V1",
		{{.name = "remote_productid_v1", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_u16_hex,
		.id = { TS2_I2C_ENUM_REMOTE_PRODUCT_TYPE_LO_V1,
			TS2_I2C_ENUM_REMOTE_PRODUCT_TYPE_HI_V1},
		.num_ids = 2, .ro = 1},
	[85] = {.debug_name = "REMOTE_PRODUCTID_V2",
		{{.name = "remote_productid_v2", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_u16_hex,
		.id = { TS2_I2C_ENUM_REMOTE_PRODUCT_TYPE_LO,
			TS2_I2C_ENUM_REMOTE_PRODUCT_TYPE_HI},
		.num_ids = 2, .ro = 1},
	[86] = {.debug_name = "REMOTE_SERNO_V1",
		{{.name = "remote_serno_v1", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_serno_v1,
		.id = { TS2_I2C_ENUM_REMOTE_SERNO_0, TS2_I2C_ENUM_REMOTE_SERNO_1,
			TS2_I2C_ENUM_REMOTE_SERNO_2, TS2_I2C_ENUM_REMOTE_SERNO_3,
			TS2_I2C_ENUM_REMOTE_SERNO_4, TS2_I2C_ENUM_REMOTE_SERNO_5},
		.num_ids = 6, .ro = 1},
	[87] = {.debug_name = "REMOTE_SERNO_V2",
		{{.name = "remote_serno_v2", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_serno_v2,
		.id = { TS2_I2C_ENUM_REMOTE_SERNO_0, TS2_I2C_ENUM_REMOTE_SERNO_1,
			TS2_I2C_ENUM_REMOTE_SERNO_2, TS2_I2C_ENUM_REMOTE_SERNO_3,
			TS2_I2C_ENUM_REMOTE_SERNO_4, TS2_I2C_ENUM_REMOTE_SERNO_5,
			TS2_I2C_ENUM_REMOTE_SERNO_6, TS2_I2C_ENUM_REMOTE_SERNO_7},
		.num_ids = 8, .ro = 1},
	[88] = {.debug_name = "LOCAL_MFGRID",
		{{.name = "local_mfgrid", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_u16_hex,
		.id = { TS2_I2C_ENUM_MFGR_ID_LO, TS2_I2C_ENUM_MFGR_ID_HI},
		.num_ids = 2, .ro = 1},
	[89] = {.debug_name = "LOCAL_PRODUCTID",
		{{.name = "local_productid", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_u16_hex,
		.id = { TS2_I2C_ENUM_PRODUCT_TYPE_LO, TS2_I2C_ENUM_PRODUCT_TYPE_HI},
		.num_ids = 2, .ro = 1},
	[90] = {.debug_name = "LOCAL_SERNO",
		{{.name = "local_serno", .mode = 0444},
		.show = a6_generic_show, .store = NULL},
		.format = format_serno_v2,
		.id = { TS2_I2C_ENUM_SERNO_0, TS2_I2C_ENUM_SERNO_1,
			TS2_I2C_ENUM_SERNO_2, TS2_I2C_ENUM_SERNO_3,
			TS2_I2C_ENUM_SERNO_4, TS2_I2C_ENUM_SERNO_5,
			TS2_I2C_ENUM_SERNO_6, TS2_I2C_ENUM_SERNO_7},
			.num_ids = 8, .ro = 1},
};


const size_t a6_register_desc_arr_size = ARRAY_SIZE(a6_register_desc_arr);

struct device_attribute custom_devattr[] = {
	{{.name = "a6_diag", .mode = 0666},
	 .show = a6_diag_show, .store = a6_diag_store},
	{{.name = "validate_cksum", .mode = 0444},
	 .show = a6_val_cksum_show, .store = NULL},
};

const size_t custom_devattr_size = ARRAY_SIZE(custom_devattr);
