# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_BATTERY_PALM_A6)		+= a6_battery.o
a6_battery-y			:= a6.o a6_regs.o a6_sbw_gpio.o a6_dispatch.o \
				   a6_sysfs.o a6_cdev.o a6_power_supply.o \
				   high_level_funcs.o low_level_funcs.o jtag_funcs.o
