# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_BATTERY_PALM_A6)		+= a6_battery.o
a6_battery-y				:= a6.o a6_dispatch.o a6_power_supply.o

obj-$(CONFIG_BATTERY_PALM_A6_A2A_COMM)	+= a6_a2a_comm.o
